### ISSUE TITLE
Can I transfer torch.tensor on cuda using ucx-py over infiniband?

### ISSUE THREAD

**Issue by sunkenQ** [rapidsai/ucx-py#1012]
I have tried code in https://ucx-py.readthedocs.io/en/latest/quickstart.html#send-recv-cupy-arrays, and it works well. But usually we use torch.tensor and dtype is torch.float32/float64/int32. If I want convert it to cupy binary form I need run torch.tensor.cuda -> cupy.ndarray ->  cupy.tobytes () -> ep.send(cupy_bytes), but cupy.tobytes() is very slow. Is there a better way to transfer torch.tensor on cuda?

**Comment by sunkenQ** [comment]
@wence- 
Thank you for your reply! I also want to ask whether numpy.ndarray must use tobytes() convert into binary before sent. I defined a protocol by myself and pre-allocated a fixed-size bytearray as buffer. The ndarray itself, dimension information, and so on are copied into this buffer on each transfer. The array is float32 and has a dimension of about 5000 x 10000, which takes a lot of time to do tobytes() and copy to buffer. Is there a better way?

There is my code
```
meta_bytes: bytes = bytes(meta)
meta_length: int = len(meta_bytes)
tensor_bytes: bytes = data.tobytes()
tensor_length: int = len(tensor_bytes)

self.update_buffer[:meta_length] = meta_bytes
self.update_buffer[
    meta_length : meta_length + tensor_length  # noqa: E203
] = tensor_bytes

# send
await ep.send(self.update_buffer)
```

**Comment by wence-** [comment]
Like the pytorch tensor case, you can also send anything zero-copy that implements the `__array_interface__` (like numpy arrays do). so `ep.send(numpy_array)` should also work fine.

**Comment by sunkenQ** [comment]
Send test were successful on both cuda torch.tensor and cpu np.ndarray, thanks a lot!
