### ISSUE TITLE
A little bit confused on how to use ucxpy in my case: Reuse endppoint, start client and server

### ISSUE THREAD

**Issue by HigashikataZhangsuke** [rapidsai/ucx-py#1033]
Hi all,

Thanks for your great work on ucx-py project. After reading the intro docs and naive sample cases, I'm kind of getting lost on how to build my own code, since it will be a little bit complicated. **The main point I was stuck at is: How to start/control ucxpy client and server in multi processes as use it like the sample code.** 

In my code logic, There will be 3 processes; **the main process will spawn the other 2 processes.  And main process will try to read some kind of tensor data infinitely, untill receives stop signal. And I just used torch multiprocessing queue to share tensor between it and the 1st sub-process. And then, i just want to let the 1st subprocess deal with data, send tensors through ucx-nvlink to 2nd sub-process.**

**For me, it's more like when using mp to create processes, I just pass the asyncio(main) term to the "target" parameter? Right? Besides, since I will pass data infinitely, I should reuse endpoint like Issue#1030?**

Thanks for any possible help!

**Comment by HigashikataZhangsuke** [comment]
Add ons: I was trying to do machine learning inference so the worst part here is I do not know the buffer size in advance, which is critical for ucxpy

**Comment by pentschev** [comment]
> In my code logic, There will be 3 processes; the main process will spawn the other 2 processes. And main process will try to read some kind of tensor data infinitely, untill receives stop signal. And I just used torch multiprocessing queue to share tensor between it and the 1st sub-process. And then, i just want to let the 1st subprocess deal with data, send tensors through ucx-nvlink to 2nd sub-process.

If I understand correctly, you'll have 3 processes:

1. Main/parent process `P`: send data to child process `A`;
2. Child process `A`: send data to child process `B`.
3. Child process `B`: only receives data from child process `A`.

You'll then need two listeners, which is up to the application to determine where they should live. For example:

1. Listener `P` in parent process;
2. Listener `A` in child process `A`.

With that, you then initiate a connection from the client to the respective listener:

1. Client `A`: connects to listener `P`;
2. Client `B`: connects to listener `A`.

> For me, it's more like when using mp to create processes, I just pass the asyncio(main) term to the "target" parameter?

No, each process must have its own asyncio loop, thus each process must create its own event loop. You can refer to [`test_send_recv_two_workers.py`](https://github.com/rapidsai/ucx-py/blob/branch-0.37/tests/test_send_recv_two_workers.py) to understand how that works.

> Besides, since I will pass data infinitely, I should reuse endpoint like Issue#1030?

You only disconnect when you are done transmitting data, establishing connections has always a cost and you don't want to do that for each bit of information you pass.

> I do not know the buffer size in advance, which is critical for ucxpy

What is the problem with that? In most communication patterns with and without UCX-Py data size is not known in advance, thus you [first send a message containing meta-data](https://github.com/rapidsai/ucx-py/blob/c8370ac98d2b5a02e493e1f5a5267c051b6eb9e1/tests/test_send_recv.py#L49) (size, type, whatever is important for the application) for which you know the size in advance, and the [follow-up message contains the actual data](https://github.com/rapidsai/ucx-py/blob/c8370ac98d2b5a02e493e1f5a5267c051b6eb9e1/tests/test_send_recv.py#L50). And the same on the receiver end, [create the buffer for the metadata which you know the size/type and receive it](https://github.com/rapidsai/ucx-py/blob/c8370ac98d2b5a02e493e1f5a5267c051b6eb9e1/tests/test_send_recv.py#L28-L29) and then [receive the data](https://github.com/rapidsai/ucx-py/blob/c8370ac98d2b5a02e493e1f5a5267c051b6eb9e1/tests/test_send_recv.py#L30-L31).

**Comment by HigashikataZhangsuke** [comment]
Hi pentschev,

Thanks for kind reply! This works for me!
