### ISSUE TITLE
ImportError raises 1.11 while check is for 1.15

### ISSUE THREAD

**Issue by praateekmahajan** [rapidsai/ucx-py#1068]
The check is for 1.15 however the error message raised is that 1.11+ is required. 

Bonus ask, it'll be great if we can show the path of the library that's being loaded and checked so that we can debug further if it's system library or environment library. 

https://github.com/rapidsai/ucx-py/blob/2ba56e587a83e5f664dfb6b891fc0fc428d5e16b/ucp/__init__.py#L113-L117

**Comment by pentschev** [comment]
What does `get_ucx_version()` print on that system?

**Comment by pentschev** [comment]
I've addressed this in https://github.com/rapidsai/ucx-py/pull/1069 , I'm not going to spend time on meddling with library loading mechanism to extract the path where UCX is being loaded from, but I did add to the exception instructions on how to properly do that with UCX log levels.

**Comment by pentschev** [comment]
Addressing the same in UCXX via https://github.com/rapidsai/ucxx/pull/277 .
