### ISSUE TITLE
Move this repository to an organization

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#113]
Presumably this would be either openucx or rapidsai.  The intention here would be that it would be come easier to attract development from other institutions that would want to partner.

cc @datametrician @Akshay-Venkatesh @TomAugspurger

**Comment by jakirkham** [comment]
My understanding is this was going to be upstreamed into [ucx]( https://github.com/openucx/ucx ) proper. Is that not correct?

**Comment by rjzamora** [comment]
I think the ideal location would be openucx (rather than rapidsai).  Getting the python bindings into ucx itself would be nice too, but a distinct repo has its advantages.

**Comment by mrocklin** [comment]
I think that everyone is on board with moving things to openucx.  However *if* that's going to take a while then moving it to rapidsai might be a good intermediate step.

**Comment by jakirkham** [comment]
To clarify, I'm basing my understanding of migrating this code to the ucx repo off of the conversation @quasiben, @Akshay-Venkatesh, and I had with the OpenUCX group a couple of weeks ago. Though if others understood this differently, please chime in.

Which part are we concerned about taking a while? Migrating stuff into a fork of the ucx repo? Or getting it upstreamed into the ucx repo?

What qualifies as a while here? What sort of timeline are you trying to get things done in?

**Comment by mrocklin** [comment]
If we can move this fork to the openucx org in a week or two then I think
that we should do that.  Otherwise I would be inclined to move it to
rapidsai.

I don't personally have a strict timeline here though, nor am I in charge
of this.

**Comment by jakirkham** [comment]
Apologies if I'm repeating myself below. What I understand the UCX devs wanting and what you are requesting here seem to be two different things. So I've tried to clearly layout below what they have requested and what that would entail.

The UCX devs recommended moving the Python bindings [here]( https://github.com/openucx/ucx/tree/master/bindings ). They were also ok hosting and maintaining the Conda recipe in that repo as well and updating Conda recipes in conda-forge based on their own copies of them. Again @quasiben and/or @Akshay-Venkatesh please correct me if any of this is off.

Based on where we are now, following their recommendation would entail making a friendly fork of [`ucx`]( https://github.com/openucx/ucx/ ), porting the code from `ucx-py` over to that fork, and PRing that work upstream. This fork could live in RAPIDS and thus be used independently of this upstreaming process. I don't know how long this migration process would take. Maybe someone else can comment on that?

Would this address the underlying motivation of this issue, @mrocklin? If not, how should we work with OpenUCX to upstream these features long term?

**Comment by Akshay-Venkatesh** [comment]
> Matt: If we can move this fork to the openucx org in a week or two then I think
that we should do that.  Otherwise I would be inclined to move it to
rapidsai.

Moving to openucx under `bindings` is not going to be a two weeks effort if we're talking about PR acceptance. Likely a month. If it is forking and porting changes then it can be done. 

> John: The UCX devs recommended moving the Python bindings [here](https://github.com/openucx/ucx/tree/master/bindings). They were also ok hosting and maintaining the Conda recipe in that repo as well and updating Conda recipes in conda-forge based on their own copies of them. Again @quasiben and/or @Akshay-Venkatesh please correct me if any of this is off.
> 
This is my understanding as well

> John: Based on where we are now, following their recommendation would entail making a friendly fork of [`ucx`](https://github.com/openucx/ucx/), porting the code from `ucx-py` over to that fork, and PRing that work upstream. This fork could live in RAPIDS and thus be used independently of this upstreaming process. 
> 
I don't follow what it means for a fork to live under RAPIDS. Can say `https://github.com/rapidsai/ucx-py` be forked repo? 

An alternate approach is we maintain ucx-py under RAPIDS and request OpenUCX to allow it live under `bindings` as a submodule. IIUC, this would be a smaller PR and we can ask UCX devs to review C code, while rapids folks can review python/cython code.

**Comment by jakirkham** [comment]
Thanks for sharing your thoughts, @Akshay-Venkatesh.

To clarify what I meant by fork, was meaning a fork of `ucx` where we do this work. This would probably not be too different to how RAPIDS handled xgboost for example.

Will we want to make changes to their build system as well (e.g. adding flags for the Python build in `configure.ac` or build steps in `Makefile.am`)?

**Comment by datametrician** [comment]
> Moving to openucx under `bindings` is not going to be a two weeks effort if we're talking about PR acceptance. Likely a month. If it is forking and porting changes then it can be done.
Given our next release is end of this month, moving this repo from your personal github to RAPIDS is useful if we want to point people to it to show what we're doing (and for them to jump in if they are inclined).  Similar to what we do with XGBoost, as I believe @jakirkham is suggesting, we can for UCX and modify it in the RAPIDS repo until all changes are upstreamed.

**Comment by Akshay-Venkatesh** [comment]
@datametrician If we start a skeleton repo under rapidsai, I'm happy to push ucx-py contents there.

**Comment by mrocklin** [comment]
We can transfer the entire repository if we have an individual that has ownership rights over both this repo and the rapidsai org.  

@Akshay-Venkatesh , perhaps you can give someone like @raydouglass ownership rights over this repository and then he can perform the transfer?

**Comment by mrocklin** [comment]
(this is a bit nicer because then we also keep the history of issues, prs, and so on)

**Comment by Akshay-Venkatesh** [comment]
@mrocklin It looks like I can transfer the ownership to rapidsai if I have the permission to create a repo there. If that's not ideal, I can try transferring to raydouglass

**Comment by mrocklin** [comment]
You should be able to go to settings, then add a collaborator and add ray
as a collaborator to this repository with owner permissions.  Then Ray can
probably handle everything.

**Comment by Akshay-Venkatesh** [comment]
Requested @raydouglass to accept ownership.

**Comment by raydouglass** [comment]
Sure, I can move this repository. @Akshay-Venkatesh I accepted the invite, please follow these steps to transfer the repo to my personal account: https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by raydouglass** [comment]
Whoops, my mistake, @Akshay-Venkatesh already did this. The repo is now in rapidsai: https://github.com/rapidsai/ucx-py
