### ISSUE TITLE
Provide getters for pointers to underlying ucp objects

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/ucx-py#117]
It would be very powerful if ucx-py could enable users to initialize and use endpoints in Python, while also being able to make use of the initialized comms underlying the UCP API.

For instance, once endpoints are initialized, it would be useful to be able to extract pointers to objects necessary for sending and receiving messages (eg `ucp_ep_h`, `ucp_context_h`, `ucp_worker_h`, `ucp_listener_h`).

I'll note that I'm still diving into ucx, so I'm still unsure of the actual objects that would need to be exposed. 

The idea is that we want to be able to use Dask to initialize UCP endpoints and send the initialized objects down to C++, but the cuML comms layer would not be aware that any initialization was done in Python or in Dask.

I am hopeful that the cuml comms API could just support the ucp API, but release deadlines might cause this priority to be lowered. At the present time, I do not believe we need to support messages being sent from Python->C++ or vice versa.

**Comment by Akshay-Venkatesh** [comment]
> For instance, once endpoints are initialized, it would be useful to be able to extract pointers to objects necessary for sending and receiving messages (eg ucp_ep_h, ucp_context_h, ucp_worker_h, ucp_listener_h).

@cjnolet As you may have seen we have an internal structure
```c

typedef struct ucp_py_internal_ep {
    ucp_ep_h  *ep_ptr;
    char      ep_tag_str[TAG_STR_MAX_LEN];
    ucp_tag_t send_tag;
    ucp_tag_t recv_tag;
} ucp_py_internal_ep_t;

```
We could add other fields (although listener at endpoint may not make sense at the client site which connects to a listener)
```c

typedef struct ucp_py_internal_ep {
    ucp_ep_h  *ep_ptr;
    ucp_worker_h  *worker_ptr;
    ucp_listener_h  *listener_ptr;
    ucp_context_h *ctx_ptr;
    char      ep_tag_str[TAG_STR_MAX_LEN];
    ucp_tag_t send_tag;
    ucp_tag_t recv_tag;
} ucp_py_internal_ep_t;

```

>The idea is that we want to be able to use Dask to initialize UCP endpoints and send the initialized objects down to C++, but the cuML comms layer should just support the UCP API, and not be aware that any initialization was done in Python or in Dask.

As long as we can pass down this structure from python -> C++, we should be able to reuse the initialized fields. 

> At the present time, I do not believe we need to support messages being sent from Python->C++ or vice versa.

Internally, we already pass from C -> python and then back from python -> C. I think we should be able to do that with C++ as well. This may be an example IIUC:
C->Python: https://github.com/rapidsai/ucx-py/blob/devel/ucp/_libs/ucp_py.pyx#L663
Python->C: https://github.com/rapidsai/ucx-py/blob/devel/ucp/_libs/ucp_py.pyx#L692

**Comment by cjnolet** [comment]
@Akshay-Venkatesh, these examples are great. If I understand them correctly, however, the pointers being passed into around have been hard-coded & compiled into the library.

I'll be the first to point out that I'm no expert at cython. I have been under the impression that in order for me to get access to the pointer to that struct on an `Endpoint` instance at runtime, without having to modify ucx-py specifically for cuml, we could just expose a function in the ucx-py library which returns this pointer as something that can convert the pointer address to a native python object (such as a `size_t`). 

I had done this in my little nccl-py example yesterday, actually [1]. This allowed me to have another cython object, assumed to be in a completely different library, that could accept this pointer at runtime.

In my experience with cython so far, I have found that when a cython-specific pointer (`void*` in this case, or `ncclComm_t*` in the case of my little nccl-py example) is casted to `size_t`, they can be passed around between Python objects at runtime. What I'm hoping for is something like this on the `Endpoint` object [2]:

```
def get_ep():
  return <size_t>self.ep
```

This _should_ allow the cuML comms python wrapper to accept an argument in Python at runtime and, using cython, cast it back to a `void*` [3]. 

What do you think about this approach?

[1]  https://github.com/cjnolet/dask-nccl/blob/master/nccl-example/nccl_example.pyx#L172
[2] https://github.com/rapidsai/ucx-py/blob/devel/ucp/_libs/ucp_py.pyx#L227
[3] https://github.com/cjnolet/dask-nccl/blob/master/nccl-example/nccl_example.pyx#L192

**Comment by Akshay-Venkatesh** [comment]
> @Akshay-Venkatesh, these examples are great. If I understand them correctly, however, the pointers being passed around have been hard-coded & compiled into the library.
> 

In the example I pointed, you're right that void pointers were being passed around.

> I'll be the first to point out that I'm no expert at cython. I have been under the impression that in order for me to get access to the pointer to that struct on an `Endpoint` instance at runtime, without having to modify ucx-py specifically for cuml, we could just expose a function in the ucx-py library which returns this pointer as something that can convert the pointer address to a native python object (such as a `size_t`).
> 
This is my understanding as well. We should be able to expose functions in ucx-py to return the pointer.

> I had done this in my little nccl-py example yesterday, actually [1]. This allowed me to have another cython object, assumed to be in a completely different library, that could accept this pointer at runtime.
> 
> In my experience with cython so far, I have found that when a cython-specific pointer (`void*` in this case, or `ncclComm_t*` in the case of my little nccl-py example) is casted to `size_t`, they can be passed around between Python objects at runtime. What I'm hoping for is something like this on the `Endpoint` object [2]:
> 
> ```
> def get_ep():
>   return <size_t>self.ep
> ```
> 

This should be possible. We can expose getter functions to return internal_ep as a <size_t> type. I've been silently assuming that this works and haven't run into issues yet. 
Did you happen to run into issues with the nccl-example? I see a familiar pattern in your usage as well.

@kkraus14 If you get a chance, can review this argument and comment if there are shortcomings in the above approach?

> This _should_ allow the cuML comms python wrapper to accept an argument in Python at runtime and, using cython, cast it back to a `void*` [3].
> 
> What do you think about this approach?
> 

Sounds good to me. Should I go ahead and expose that function? I can review and merge should you already have such a change.

> [1] https://github.com/cjnolet/dask-nccl/blob/master/nccl-example/nccl_example.pyx#L172
> [2] https://github.com/rapidsai/ucx-py/blob/devel/ucp/_libs/ucp_py.pyx#L227
> [3] https://github.com/cjnolet/dask-nccl/blob/master/nccl-example/nccl_example.pyx#L192

**Comment by jakirkham** [comment]
I wonder if it might make sense to create a wrapper object that allows Python users to pass around the relevant information, but hide the details of pointers and whatever else from Python and only expose this to Cython/C/C++. This is similar to how `memoryview`s behave for instance. If this is a reasonable approach, it might make sense to build a very small [Cython extension type]( https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html ). Thoughts?

**Comment by cjnolet** [comment]
Thank you, @jakirkham, I will take a look at that approach. 

I recently realized I will also need a pointer to the ucp_worker_h handle as well. While I’m working through examples for the cuml comms, I will try out John’s approach to see if it will work in this case.

**Comment by kkraus14** [comment]
I would agree with @jakirkham that if we have the ability to use Cython it will be much cleaner and clearer what's happening. If we can't use Cython and need to return to a pure Python context where we can't keep C++ objects in scope, then we haven't seen issues thus far of using Python integers to track pointers and then typecasting in Cython / C++ as needed to use them properly.
