### ISSUE TITLE
Testing with new RCs

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#118]
In the past week, the UCX team has made [v1.5.2-rc1]( https://github.com/openucx/ucx/releases/tag/v1.5.2-rc1 ) and [v1.6.0-rc1]( https://github.com/openucx/ucx/releases/tag/v1.6.0-rc1 ). It would be good to check if things are still working with those RCs and if not report issues upstream.

**Comment by mrocklin** [comment]
I suspect that it won't work until some of Akshay's work gets merged in.  Currently we're operating from a branch.

**Comment by jakirkham** [comment]
It sounds like the story is changing with the upcoming 1.7.0.

**Comment by quasiben** [comment]
I think we can close as we noow have 1.7.0rc1 out, correct ?

**Comment by jakirkham** [comment]
Yeah, let's close. Thanks!
