### ISSUE TITLE
We create poorly formed memoryview objects

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#119]
I occasionally get errors where we seem to be receiving zero-length messages in ucx-py.  I placed a breakpoint when this happened and investigated the object.  It looks like we're forming improper memoryview objects somehow:

```python
(Pdb) pp obj
<memory at 0x7f22051d4ac8>
(Pdb) pp len(obj)
0
(Pdb) pp bytes(obj)
(b'\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\xdd\x00\x00\x00\x00\x00\x00\x00')
(Pdb) pp bytes(obj[:8])
b''
```

I'll take a look briefly.

**Comment by mrocklin** [comment]
@TomAugspurger if you have suggestions on where this might be happening those would be welcome.

**Comment by TomAugspurger** [comment]
Is this GPU or CPU memory? For CPU, the bug is likely in
https://github.com/rapidsai/ucx-py/blob/devel/ucp/_libs/ucp_py_buffer_helper.pyx#L142,
but I'm not sure exactly where.

**Comment by mrocklin** [comment]
Yeah, I'm playing around in there now.  I can get it to fail in both CPU and GPU memory.

**Comment by mrocklin** [comment]
This seems to be fixed in https://github.com/rapidsai/ucx-py/pull/120
