### ISSUE TITLE
Adding license file

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#123]
Would be good to add a license file. Guessing it should be the same as UCX's license. Though please correct me if not.

**Comment by quasiben** [comment]
@mrocklin @Akshay-Venkatesh do you have an idea what the license should be ?

**Comment by jakirkham** [comment]
If we are upstreaming this to UCX, we might also want to touch base with them to see what kind of licensing would be acceptable.

**Comment by MattBBaker** [comment]
The main UCX repo is 3 clause BSD. Using that will be easiest.

**Comment by mrocklin** [comment]
At the same time most RAPIDS projects use Apache 2.

**Comment by pentschev** [comment]
If this repo will be long-maintained by RAPIDS, I would suggest sticking to Apache 2 license, per the reason pointed out by @mrocklin.

**Comment by jakirkham** [comment]
Are we still planning on upstreaming this to UCX? If so, I’d suggest just using the UCX license file here (i.e. BSD-3-Clause) as @MattBBaker has stated. Otherwise we are merely complicating the upstreaming process for ourselves later.

**Comment by mrocklin** [comment]
Sounds good. Go for it. You should probably check in with Akshay.

**Comment by jakirkham** [comment]
@Akshay-Venkatesh , can you please weigh in here (when you have a chance)?

**Comment by Akshay-Venkatesh** [comment]
The plan is still to upstream to UCX but those are probably aimed for post-UCX 1.7 release. Suggestion from @MattBBaker sounds reasonable to me as well.

**Comment by jakirkham** [comment]
Thanks all. Have submitted PR ( https://github.com/rapidsai/ucx-py/pull/182 ) to address this. Please take a look.
