### ISSUE TITLE
Fill out metadata in setup function

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#124]
We're currently missing some metadata in the [`setup` function]( https://github.com/rapidsai/ucx-py/blob/4030eff63438ac87d58fd009656198a184914041/setup.py#L69-L76 ). Would be good to include version, description, license, url, maintainer, classifiers, zip_safe (should be false), python version required, etc. Here's [an example]( https://github.com/dask/dask/blob/d8ff4c4d155d51cf275776c1ec8ef27c16d43f17/setup.py#L33-L55 ) for context.

**Comment by pentschev** [comment]
All the metadata mentioned in the description is in the setup function already. I'm closing this issue but feel free to reopen should I've missed something.

**Comment by jakirkham** [comment]
Thanks Peter! 😄
