### ISSUE TITLE
Handling buffer protocol requests

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#127]
With [Python's buffer protocol]( https://docs.python.org/3/c-api/buffer.html#buffer-protocol ), downstream consumers are able to make [requests about the buffer]( https://docs.python.org/3/c-api/buffer.html#buffer-request-types ). These include things like requiring it to be writable, requesting metadata, and requiring contiguity. As producers of the buffer, we are obliged to check what is requested and attempt to satisfy that request. If we are unable to meet the request, the protocol expects that we raise a `BufferError`. AFAICT it doesn't appear we are doing this in `__getbuffer__` currently.

**Comment by jakirkham** [comment]
Just to provide some additional context about what this entails, [here's how NumPy handles one possible request]( https://github.com/numpy/numpy/blob/7ebbc2ed3b4a388dd3942e1d8ef2de18074a09b3/numpy/core/src/multiarray/buffer.c#L747-L752 ). In this case C contiguity is being checked with an error raised if not met.

**Comment by quasiben** [comment]
closing

Fixed in #144
