### ISSUE TITLE
Build Cython extension type for passing UCP endpoint and worker information through Cython at runtime

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/ucx-py#130]
I wonder if it might make sense to create a wrapper object that allows Python users to pass around the relevant information, but hide the details of pointers and whatever else from Python and only expose this to Cython/C/C++. This is similar to how `memoryview`s behave for instance. If this is a reasonable approach, it might make sense to build a very small [Cython extension type]( https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html ). Thoughts?

_Originally posted by @jakirkham in https://github.com/rapidsai/ucx-py/issues/117#issuecomment-499970672_

**Comment by madsbk** [comment]
Is this something still of interest? Exposing the underlying UCX handles as Python integers is very easy and already done for the [worker](https://github.com/rapidsai/ucx-py/blob/b68e727bdc27edc326cf16ef8c36debdfbd8eb3f/ucp/public_api.py#L82). Is that sufficient?
