### ISSUE TITLE
Error with `recv_future` with large data

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#133]
@Akshay-Venkatesh I believe there is an issue with `recv_future` when trying to receive *largish* data.  That would be data > 500MB.  `recv_obj` does not seem to have a problem with this though there does seem to be an upper limit of around 2GBs.  My suspicion around the upper limit is that the buffer size uses a int rather than an unsigned int.  

In any case, do you know why `recv_future` may be having trouble with larger messages ?

**Comment by Akshay-Venkatesh** [comment]
@quasiben Basic question - Do you happen to know if the physical memory limits are exceeded when the error occurs?

You're also right about int usage and this may very well be the cause of the error. We should be switching to `ssize_t` for all sends/recvs to handle large count case. I'll have a PR for this soon.

**Comment by quasiben** [comment]
No, the physical limits were not exceeds.  I am using v100s (32GB) and the data size is just above 500MB.  I watched nvidia-smi to confirm

**Comment by quasiben** [comment]
@Akshay-Venkatesh thank you for looking into this!

**Comment by Akshay-Venkatesh** [comment]
@quasiben Can you try with this patch lmk if it helps?

https://gist.githubusercontent.com/Akshay-Venkatesh/95cb4ba2c9d4684200557563869fd701/raw/d2cf818e499d193d570f83cfe67f651fc8d6d71f/fix-int-length.diff

Thanks

**Comment by quasiben** [comment]
Trying now

**Comment by quasiben** [comment]
On small objects which previously worked I see errors:

```
GitRepos/ucx-py/tests/test_send_recv_obj.py:227: in read
    resp = await self.ep.recv_future()
ucp/_libs/ucp_py.pyx:242: in ucp_py.Endpoint.recv_future
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   OverflowError: can't convert negative value to size_t

ucp/_libs/ucp_py.pyx:417: OverflowError
```

And on larger objects (+500MB) I still see hanging issues

**Comment by Akshay-Venkatesh** [comment]
@quasiben Can you try again with this?

https://gist.githubusercontent.com/Akshay-Venkatesh/95cb4ba2c9d4684200557563869fd701/raw/da7c41246935303c3c0bcd857fb458a9d4bd28fa/fix-int-length2.diff

I'm using the signed version of `size_t` this time.

**Comment by quasiben** [comment]
I can't apply that patch cleanly:

```
(cudf-dev) bzaitlen@dgx15:~/GitRepos/ucx-py$ git apply fix-int-length2.diff
error: patch failed: ucp/_libs/src/ucp_py_ucp_fxns.c:353
error: ucp/_libs/src/ucp_py_ucp_fxns.c: patch does not apply
```

**Comment by mrocklin** [comment]
Is there a simple test that Ben can write that Akshay can run in order to
eliminate this interaction bottleneck?  Or is the software environment too
complex to easily recreate?

**Comment by quasiben** [comment]
I have a test here https://github.com/rapidsai/ucx-py/pull/129/files#r311244650 but the env is a little complex to setup.  

I manually applied the patch since it was small.  It did resolve the `can't convert negative` error but I am still seeing hangs with the large cudf dataframe
