### ISSUE TITLE
What is needed for UCX-py to work on a consumer linux machine

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#134]
I (and others I suspect) would like to start using UCX more regularly in my day-to-day development, both to provide acceleration, and to find and report bugs.  To facilitate this, it would be nice to use UCX-py on a consumer laptop running Linux (personally I have a ThinkPad Carbon).  Is this feasible today?  If not, what is needed?

For example, do I still need IB around?  If not, does the conda package that we're producing expect IB?

cc @Akshay-Venkatesh @jakirkham

**Comment by jakirkham** [comment]
The packages we build links to `libibverbs`, `librdmacm`, etc. So those libraries need to be installed, which you could do on another machine that lacks those features (that's how we did the builds initially anyways).

I guess the question is are those dependencies still used (even if the library was built with them) if the machine lacks the hardware. IOW is a runtime check performed to determine the capabilities of the machine UCX is working on. IDK the answer to that question. Maybe @Akshay-Venkatesh will know.

**Comment by TomAugspurger** [comment]
I think TCP lacked some layer needed for creating a client-server pair.
https://github.com/openucx/ucx/issues/3042.

**Comment by Akshay-Venkatesh** [comment]
`librdmacm`, `libibverbs` can be linked but it's not a hard requirement. UCX can be configured to build without the above but the necessary emulation is missing -- sockets based connection management.

TCP based connection management is scheduled for v1.7 (august 30 deadline) as per this list: https://github.com/openucx/ucx/milestone/12

This is the PR that aims to fill that gap https://github.com/openucx/ucx/pull/3570 and we're working towards finalizing this. 

At this point, I'm rethinking the approach behind UCXpy using client-server API from UCX. As this turning out to be longer than expected, I want to bring up the possibility of using our own sockets based backed to exchange UCX address handles. This would mean using our own OOB channel but maybe that suffices for dask over UCX. For UCXpy user there should be no visible change in usage but I think we can do this in about to 2-3 weeks if we have all the tools. The major disadvantage of not using client-server API is not being able to use callback mechanism that currently enables to us to load up a new coroutine when a connection request appears. 

@mrocklin What are your overall thoughts?

**Comment by mrocklin** [comment]
Sorry for the delay here.  

> The major disadvantage of not using client-server API is not being able to use callback mechanism that currently enables to us to load up a new coroutine when a connection request appears

What would happen when a new connection request comes in?

**Comment by mrocklin** [comment]
Or rather, let me say that handling many connection concurrently is probably a hard requirement for Dask usage.

**Comment by Akshay-Venkatesh** [comment]
> Sorry for the delay here.
> 
> > The major disadvantage of not using client-server API is not being able to use callback mechanism that currently enables to us to load up a new coroutine when a connection request appears
> 
> What would happen when a new connection request comes in?

We would need to have a handler thread that wakes on an `accept` call essentially. In essence, we recreate what ucx is doing behind the scenes. This would satisfy the Dask's need to handle connections concurrently as well.

**Comment by mrocklin** [comment]
Sure, I have no objection to having a handler thread that creates a coroutine, loads it onto the event loop, and then goes quiet again.  That seems reasonable to me.

**Comment by madsbk** [comment]
`branch-0.10` should work on machines without IB and GPUs

**Comment by mrocklin** [comment]
Nice.  I'm curious, have you tried it with a consumer linux machine?  If so, how did it go?

**Comment by quasiben** [comment]
I tried on an [Intel Nuc](https://en.wikipedia.org/wiki/Next_Unit_of_Computing) and things went smoothly wrt usability -- no benchmarks

**Comment by madsbk** [comment]
I have tried it on my laptop and it also went smoothly :)
