### ISSUE TITLE
Create cudatoolkit=10 compatible packages

### ISSUE THREAD

**Issue by randerzander** [rapidsai/ucx-py#141]
Many dev and test environments have upgraded to CUDA 10.x.

It'll be easier for users and developers to work with and test UCX if it supports CUDA 10.

**Comment by mrocklin** [comment]
cc @jakirkham

**Comment by jakirkham** [comment]
Yep, this is reasonable and desirable. Probably easier after some things I discovered when working on the CuPy packages.

That said, I want to make sure the existing UCX packages are working correctly before increasing how many we have.

**Comment by jakirkham** [comment]
Have done this in the recent build of the packages. That said, am seeing some issues with these packages that I'm asking @Akshay-Venkatesh about.
