### ISSUE TITLE
[QST] What's the most basic dask_cudf test for a successful ucx setup?

### ISSUE THREAD

**Issue by randerzander** [rapidsai/ucx-py#142]
I have conda installed ucx, ucx-py, and ucx-proc based on this repo's README.

Now I'm trying to setup a Dask cluster to do a basic test confirming GPUs are communicating over nvlink instead of tcp.

I followed [this post](https://blog.dask.org/2019/06/09/ucx-dgx) and started `dask-scheduler --protocol ucx`, but the dask-worker doesn't understand the protocol:
```
(rapids) root@8cec589efc7b:~# dask-worker ucx://127.0.0.1:8786
Traceback (most recent call last):
  File "/conda/envs/rapids/bin/dask-worker", line 10, in <module>
    sys.exit(go())
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 406, in go
    main()
  File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 373, in main
    for i in range(nprocs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 373, in <listcomp>
    for i in range(nprocs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 180, in __init__
    host = get_ip(get_address_host(self.scheduler.address))
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/addressing.py", line 142, in get_address_host
    backend = registry.get_backend(scheme)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/registry.py", line 69, in get_backend
    "unknown address scheme %r (known schemes: %s)" % (scheme, sorted(backends))
ValueError: unknown address scheme 'ucx' (known schemes: ['inproc', 'tcp', 'tls'])
```

Is there a newer guide for how to setup my cluster?

**Comment by mrocklin** [comment]
Can you verify that you can import `ucp` ?

Also you may want to try installing ucx-py from a conda package.  See https://github.com/rapidsai/ucx-py#installing-preliminary-conda-packages (thanks @jakirkham !)

**Comment by quasiben** [comment]
That is the current best way to get up and running.  There are recent PRs which will be merged into cudf/RMM before the 0.9 release.  If possible can we wait until then ?

**Comment by randerzander** [comment]
> Can you verify that you can import ucp ?
```
>>> import ucp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/ucp/__init__.py", line 2, in <module>
    from ._libs.ucp_py import *  # noqa
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
```
Looks like libnuma-dev is a dependency?

The ucx modules I'm using were installed from conda as described in the README.

**Comment by randerzander** [comment]
Installing `libnuma-dev` from apt lets me `import ucp` successfully.

Now, on starting the worker I get destination unreachable on 127.0.0.1 and the IP address the scheduler picked up automatically (172.17.0.2):

scheduler:
```
(rapids) root@8cec589efc7b:~# dask-scheduler --protocol ucx
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-hkigh8hd
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.dashboard.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: pip install jupyter-server-proxy
distributed.scheduler - INFO -   Scheduler at:     tcp://172.17.0.2:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
``

Worker:
```
(rapids) root@8cec589efc7b:/notebooks# dask-worker ucx://172.17.0.2:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.17.0.2:45781'
distributed.worker - INFO -       Start worker at:     tcp://172.17.0.2:46740
distributed.worker - INFO -          Listening to:     tcp://172.17.0.2:46740
distributed.worker - INFO -          dashboard at:           172.17.0.2:44286
distributed.worker - INFO - Waiting to connect to:      ucx://172.17.0.2:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         80
distributed.worker - INFO -                Memory:                  540.95 GB
distributed.worker - INFO -       Local Directory: /notebooks/worker-o0dpux5v
distributed.worker - INFO - -------------------------------------------------
[1565722626.441595] [8cec589efc7b:3225 :0]    ucp_context.c:603  UCX  WARN  transport 'rc' is not available
failed to connect to 172.17.0.2 (Destination is unreachable)
failed to connect to 172.17.0.2 (Destination is unreachable)
...
```

**Comment by mrocklin** [comment]
cc @jakirkham

**Comment by randerzander** [comment]
>  There are recent PRs which will be merged into cudf/RMM before the 0.9 release

[This one](https://github.com/rapidsai/rmm/pull/113)? I assume that wouldn't be impacting the issue I described above.

**Comment by mrocklin** [comment]
```
(rapids) root@8cec589efc7b:~# dask-scheduler --protocol ucx
...
distributed.scheduler - INFO -   Scheduler at:     tcp://172.17.0.2:8786
```

This is concerning.  It looks like it didn't use the ucx protocol, even though you specified it.  It used `tcp://` instead

**Comment by mrocklin** [comment]
> Now, on starting the worker I get destination unreachable 

If we don't yet support TCP (@Akshay-Venkatesh ?) then you'll also need to specify your infiniband network interface, often `ib` or `ib0` or `bond0`

**Comment by mrocklin** [comment]
(also, you do this with the `--interface` keyword, like `--interface ib0`)

**Comment by randerzander** [comment]
I should have clarified earlier, I'm attempting to get this working on a single node between multiple GPUs over nvlink.

Does that change how I need to configure something?

**Comment by mrocklin** [comment]
You should still specify an infiniband interface even on a single node, and
even if you mostly want to use NVLink for data communication.

**Comment by randerzander** [comment]
Does that mean an infiniband interface is required for GPU->GPU communication over nvlink?

**Comment by mrocklin** [comment]
It certainly was before, Akshay would know the status today.

**Comment by Akshay-Venkatesh** [comment]
@randerzander You would still need IB interfaces to startup the job -- at least until the end of this week. Once the startup completes, you would end up using just NVLINKs for single nodes where there exists the connectivity to achieve that.

**Comment by madsbk** [comment]
@randerzander, a basic test:
```
# TCP using "eth0" and CUDA support
export UCX_TLS=tcp,sockcm,cuda_copy,cuda_ipc
export UCX_SOCKADDR_TLS_PRIORITY=sockcm
export UCXPY_IFNAME="eth0"

# UCX-Py tests
pytest -v

# DASK UCX tests <https://github.com/dask/distributed>
pytest <path-to-distributed>/distributed/comm/tests/test_ucx.py
```
Where `eth0` is your network interface.

In order to test without GPU remove `cuda_copy,cuda_ipc` from `UCX_TLS`.

**Comment by madsbk** [comment]
@randerzander, please re-open this issue or open a new issue if it still doesn't work for you on `branch-0.10`.
