### ISSUE TITLE
Multiple Listener test hangs when running in succession 

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#151]
When running the `test_multiple_listeners.py` in succession the test hangs.  This is a problem when running bulks tests like the following:

> py.test -s -v test/

A smaller reproducible example would be:
> py.test -s -v tests/test_init_fin.py tests/test_multiple_listeners.py

Oddly, `test_multiple_listeners.py` runs without issue executing the test in isolation:

> py.test -s -v tests/test_multiple_listeners.py

Does this mean `test_init_fin.py` does not finish cleaning up ?

**Comment by quasiben** [comment]
This is resolved by putting the init() inside the test definition

**Comment by mrocklin** [comment]
Would it make sense to cleanly initialize and finalize ucp for each test as part of a pytest fixture?

**Comment by quasiben** [comment]
Yes!  Thank you for the suggestion

**Comment by quasiben** [comment]
I'll add that to my test cleanup PR: https://github.com/rapidsai/ucx-py/pull/152
