### ISSUE TITLE
`BufferRegion` perserving dtype and shape information?

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#153]
Currently, when creating a `BufferRegion` through the buffer protocol or `__cuda_array_interface__`, we preserve the dtype and shape of the buffer. 

Is this a feature we use? Or could we just as well return a 1-dim `byte` buffer always?
I ask, because it could reduce the complexity of `BufferRegion` if we didn't have to preserve `format`, `typestr`, and `descr` (which doesn't use the same symbols).

I don't think we use this feature at the moment beside in [`test_buffer_region.py`](https://github.com/rapidsai/ucx-py/blob/devel/tests/test_buffer_region.py). At least, `Message.get_obj()` comes with this warning:
```
Note that the metadata like ``typestr`` and ``shape`` may be incorrect. 
This will need to be manually fixed before consuming the buffer.
```

This issue relates to #71

**Comment by mrocklin** [comment]
I don't think that we use dtype and shape, although I could be wrong.  cc'ing @TomAugspurger and @Akshay-Venkatesh , who were more involved during this period.

**Comment by mrocklin** [comment]
Or rather, the Dask/RAPIDS use case doesn't need these attributes.  I don't know about other potential UCX uses though.  It could be that this is important for more MPI-style workloads.

**Comment by TomAugspurger** [comment]
I do recall being confused by shape, dtype, format, typestr... I think the
more we can do to simplify this, the better.

**Comment by quasiben** [comment]
@mrocklin, you are saying dask/rapids doesn't need these attributes in ucx-py because they are preserved in other ways ?

**Comment by mrocklin** [comment]
Yes.  We only use the buffer region to send bytes.  We keep track of shape, dtype, and other metadata in the header that Dask sends as a separate message.

**Comment by madsbk** [comment]
Because of #180, this is not relevant anymore.
