### ISSUE TITLE
[QST] No Deadlock - What am I misunderstanding?

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#175]
I cannot understand why our send/recv tests doesn't deadlock.

For instance, why does this test in [test_send_recv_obj.py](https://github.com/rapidsai/ucx-py/blob/devel/tests/test_send_recv_obj.py#L28) not deadlock when setting [`UCX_RNDV_THRESH=1`](https://github.com/openucx/ucx/wiki/Rendezvous-Protocol)?
```python
@pytest.mark.asyncio
@pytest.mark.parametrize("size", msg_sizes)
async def test_send_recv_bytes(size):
    x = "a"
    x = x * size
    msg = bytes(x, encoding="utf-8")

    async with echo_pair() as (_, client):
        await client.send_obj(bytes(str(size), encoding="utf-8"))
        await client.send_obj(msg)
        resp = await client.recv_obj(len(msg))
        result = ucp.get_obj_from_msg(resp)

    assert result.tobytes() == msg
```
I would expect that `await client.send_obj(msg)` would block until `msg` has been send, which would only happen when UCX can pair the send the with the later receive.

In order to avoid deadlock, I thought that we would have to do something like:
```python
asyncio.ensure_future(client.send_obj(bytes(str(size), encoding="utf-8")))
asyncio.ensure_future(client.send_obj(msg))
resp = await client.recv_obj(len(msg))
result = ucp.get_obj_from_msg(resp)
```

**Comment by Akshay-Venkatesh** [comment]
I this case the sender and receiver are running on two separate coroutines aren't they? If so, why is there an expectation of deadlock? The test above is different from that in https://github.com/rapidsai/ucx-py/issues/140#issuecomment-519596036

Lemme know if I've misunderstood your question.

**Comment by madsbk** [comment]
it is properly me that don't understand the semantic of `asyncio` but what do you mean with "running on two separate coroutines"? 
Ain't `await` blocking until the future is finished?

**Comment by madsbk** [comment]
I was expecting something like this behavior: https://stackoverflow.com/questions/43518504/multiple-async-calls-blocking

**Comment by mrocklin** [comment]
```python
    async with echo_pair() as (_, client):
        await client.send_obj(bytes(str(size), encoding="utf-8"))
        await client.send_obj(msg)
        resp = await client.recv_obj(len(msg))
```

There is another coroutine running in the background created by `echo_pair`.  What we're seeing here is only half of the communication.  The server running in the background echos any message sent to it back to the client.

**Comment by madsbk** [comment]
Right, now I get it :)

`await client.send_obj()` is talking to the [`echo_server`](https://github.com/rapidsai/ucx-py/blob/b1db504ec17ba4717f741344183020b9c8eec909/ucp/_utils.py#L42) and not to `await client.recv_obj()` :)

Thanks

**Comment by mrocklin** [comment]
Yes.  Exactly.

**Comment by MattBBaker** [comment]
One point I want to raise as well from a low level UCX perspective. The send and recv functions do not necessarily have to be paired before completing. It looks like the send_obj and recv_obj are implement with ucp_tag_recv_nb and ucp_tag_send_nb, and if the under laying uct transport buffers receives then it is possible for UCX to report a ucp_tag_send_nb as completed before the corresponding ucp_tag_recv_nb is called on the remote side, since the local node has finished sending. In such a case `await client.send_obj(bytes(str(size), encoding="utf-8"))` would only block until the size string could be freed.

**Comment by madsbk** [comment]
@MattBBaker, good point. 
Do you know if `UCX_RNDV_THRESH=1` changes this behavior? I would expect that using the [Rendezvous Protocol](https://github.com/openucx/ucx/wiki/Rendezvous-Protocol) would make the send/recv calls block until the pair has been established?

**Comment by MattBBaker** [comment]
@madsbk Yes, the Rendezvous Protocol uses zcopy mechanics so the recv part needs to have it's memory allocated already to copy into, so the sender won't complete until the remote side has finished it's transfer.

**Comment by madsbk** [comment]
Great, thanks for the clarification
