### ISSUE TITLE
[QST] Why not ucp_stream_send_nb and ucp_stream_recv_nb?

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#179]
Is there any reason why we are not using `ucp_stream_send_nb()` and `ucp_stream_recv_nb()` instead of `ucp_tag_recv_nb()` and `ucp_tag_recv_nb()` for communication?

A problem with `ucp_tag_recv_nb()` is that you cannot specify an endpoint to listen on. Instead, you have to use tags to differentiate the endpoint of the incoming messages.

cc @Akshay-Venkatesh

**Comment by Akshay-Venkatesh** [comment]
@madsbk

This is something we had considered before tag matching layer we added. Stream based operations on GPU buffers aren't performant yet due to internal UCP implementation.
