### ISSUE TITLE
New default branch that follows RAPIDS's branch/version convention 

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#188]
I suggest that we follow the RAPIDS's branch/version convention and create a new default branch `branch-0.10` and merge the new [Python bindings](https://github.com/rapidsai/ucx-py/pull/180) into it. That way, existing install descriptions that explicit pull the `devel` branch a not affected by the new bindings.

Thoughts?

**Comment by mrocklin** [comment]
cc @Akshay-Venkatesh

**Comment by quasiben** [comment]
While the work is done in this repo keeping things in sync with rapids make sense.  Luckily, the versions of rapids are behind that of core UCX which is currently at 1.6.1

**Comment by Akshay-Venkatesh** [comment]
I'm not familiar with RAPIDS branch/version convention. If there's enough confidence in https://github.com/rapidsai/ucx-py/pull/180 then I have no objections. That said, shouldn't it be the case that there's a main branch that you fork off of and create new branches like `branch-0.10`, `branch-0.20`... ? If so, should https://github.com/rapidsai/ucx-py/pull/180 be merged into devel and then fork off that to create `branch-0.10` ?

**Comment by quasiben** [comment]
RAPIDS takes the convention of continually building branches as the "main" branch.  For example, until recently, branch-0.9 was the main branch, 0.9 was released, and 0.10 became the main branch.  Dask/Distributed use the convention of a "master" branch and tagging releases.  I believe @madsbk suggestion is keeping the structure of `devel` intact should something happen.  

I personally like dask's model of a main master branch or what you, @Akshay-Venkatesh, have suggested but it's not a strongly held opinion

**Comment by Akshay-Venkatesh** [comment]
Thanks for clarifying. I didn't know about building branches as main. I don't know the pros and cons of the approach but if that's how RAPIDS does it, then I think remaining consistent with that approach makes sense.

**Comment by madsbk** [comment]
Agree, I also prefer the more traditional approach with "master" branch and tagging releases but since the other RAPIDS projects use the alternative approach, I think we should as well.

**Comment by mrocklin** [comment]
(+1 on using master and tagging releases generally)

I think that long-term ucx-py should probably follow conventions defined by
the UCX project rather than RAPIDS.  If there is some short term
alternative that makes folks more productive then that makes sense to me.

**Comment by madsbk** [comment]
Okay, let's use the "master and tagging releases" scheme, we can always change it later.

When it is ready, I will merge the new Python bindings into master

**Comment by madsbk** [comment]
I have merged #180 into `master` but I do not have permission to change default branch.

**Comment by quasiben** [comment]
Neither do I.  @Akshay-Venkatesh can you help with this ?

**Comment by Akshay-Venkatesh** [comment]
I don't own https://github.com/rapidsai/ucx-py
cc @raydouglass

**Comment by raydouglass** [comment]
gpuCI is designed to operate with the git methodology used by RAPIDS (see https://docs.rapids.ai/resources/git/). Using `master` as the main development branch isn't possible with gpuCI.

The best course of action is to follow RAPIDS. The development branch doesn't have to match the naming convention of `branch-x.y` though. Just let me know what your preferred dev branch is and I can set it as the default.

**Comment by quasiben** [comment]
@raydouglass can we do this at least temporarily while we sort out some issues ?  the default branch is currently tied to how we are building conda packages ?

**Comment by quasiben** [comment]
@raydouglass, disregard the last comment, we've created branch ` branch-0.10`.  Can this be set to default ?

**Comment by quasiben** [comment]
@mike-wendt if you have time can you set the default branch to be `branch-0.10` ?

**Comment by raydouglass** [comment]
Default branch is now `branch-0.10`

**Comment by quasiben** [comment]
Thanks @raydouglass -- closing
