### ISSUE TITLE
[QST] Getting ucx module not found error in python shell after successful installation

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [rapidsai/ucx-py#191]
Trying to build ucx and ucx-py from source in my devbox but for some reason, the ucx-py module is not installed even though it's saying the installation is successful. I have Ubuntu 18.05 and CUDA 10.0 in my devbox. Using conda environment.

"conda list ucp" output as follows;
# Name                    Version                   Build  Channel
ucp                       0.0.0                     <pip>

Any idea? 

Thanks!

**Comment by quasiben** [comment]
Can you verify ucx is installed correctly and post the output of the following:

```
ucx_info -d
which ucx_info
```

**Comment by oyilmaz-nvidia** [comment]
ucx_info -d

# Memory domain: posix
#     Component: posix
#             allocate: unlimited
#           remote key: 29 bytes
#           rkey_ptr is supported
#
#   Transport: posix
#      Device: memory
#
#      capabilities:
#            bandwidth: 12179.00 + 0.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 92
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 16 bytes
#       error handling: none
#
#
# Memory domain: sysv
#     Component: sysv
#             allocate: unlimited
#           remote key: 24 bytes
#           rkey_ptr is supported
#
#   Transport: sysv
#      Device: memory
#
#      capabilities:
#            bandwidth: 12179.00 + 0.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 92
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 16 bytes
#       error handling: none
#
#
# Memory domain: self
#     Component: self
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: self
#      Device: memory
#
#      capabilities:
#            bandwidth: 6911.00 + 0.00 MB/sec
#              latency: 0 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 8K
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: tcp
#     Component: tcp
#             register: <= 0, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: tcp
#      Device: eno1
#
#      capabilities:
#            bandwidth: 0.00 + 113.16 MB/sec
#              latency: 5776 nsec
#             overhead: 50000 nsec
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 128K, up to 6 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1500
#            am header: <= 8037
#           connection: to iface
#             priority: 1
#       device address: 4 bytes
#        iface address: 2 bytes
#       error handling: none
#
#
# Memory domain: sockcm
#     Component: sockcm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Memory domain: cuda_cpy
#     Component: cuda_cpy
#             register: unlimited, cost: 0 nsec
#
#   Transport: cuda_copy
#      Device: cuda
#
#      capabilities:
#            bandwidth: 0.00 + 6911.00 MB/sec
#              latency: 10000 nsec
#             overhead: 0 nsec
#            put_short: <= 4294967295
#            put_zcopy: unlimited, up to 1 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_short: <= 4294967295
#            get_zcopy: unlimited, up to 1 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: cuda_ipc
#     Component: cuda_ipc
#             register: <= 1G, cost: 0 nsec
#           remote key: 88 bytes
#
#   Transport: cuda_ipc
#      Device: cuda
#
#      capabilities:
#            bandwidth: 0.00 + 24000.00 MB/sec
#              latency: 1 nsec
#             overhead: 0 nsec
#            put_zcopy: <= 1G, up to 1 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_zcopy: <= 1G, up to 1 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 4 bytes
#       error handling: peer failure

which ucx_info
/home/oyilmaz/miniconda3/envs/cuml-0912/bin/ucx_info

**Comment by oyilmaz-nvidia** [comment]
Sorry for the character sizes in previous comment. Automatically enlarged it because of the "#" characters in the message.

**Comment by quasiben** [comment]
I edited the comment to handle sizing issue

**Comment by quasiben** [comment]
Ah, i think the issue maybe be that we have just switched the Python bindings and the the default branch is not `master` .  Can you pull the `master` branch and re-install (make clean; make install).  Then verify correctness with the following:

> python -c 'import ucp; print(ucp.__version__)'

**Comment by oyilmaz-nvidia** [comment]
Got this error from master branch.

```
In file included from ucp/_libs/utils.c:626:0:
ucp/_libs/src/c_util.h:8:10: fatal error: ucp/api/ucp.h: No such file or directory
 #include <ucp/api/ucp.h>
```

**Comment by oyilmaz-nvidia** [comment]
Never mind.  UCX_PATH wasn't set properly.

**Comment by quasiben** [comment]
You need to set UCX_PATH before you build:

```
export UCX_PATH=$CONDA_PREFIX
make install
```

**Comment by oyilmaz-nvidia** [comment]
Still not installed. Getting the following from make install;

```
(cuml-0912) oyilmaz@NVIDIA-PC:~/Documents/rapids/ucx-py$ make install
LDFLAGS="-L/home/oyilmaz/miniconda3/envs/cuml-0912/lib -L"/usr/local/cuda"/lib64" CFLAGS="-I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I"/usr/local/cuda"/include" python3 setup.py build_ext -i --with-cuda
Compiling ucp/_libs/utils.pyx because it changed.
Compiling ucp/_libs/send_recv.pyx because it changed.
Compiling ucp/_libs/core.pyx because it changed.
[1/3] Cythonizing ucp/_libs/core.pyx
[2/3] Cythonizing ucp/_libs/send_recv.pyx
[3/3] Cythonizing ucp/_libs/utils.pyx
running build_ext
building 'ucp._libs.utils' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/ucp
creating build/temp.linux-x86_64-3.7/ucp/_libs
creating build/temp.linux-x86_64-3.7/ucp/_libs/src
gcc -pthread -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include -fPIC -I/home/oyilmaz/miniconda3/envs/cuml-0912/include/python3.7m -c ucp/_libs/utils.c -o build/temp.linux-x86_64-3.7/ucp/_libs/utils.o -std=c99 -DUCX_PY_CUDA
gcc -pthread -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include -fPIC -I/home/oyilmaz/miniconda3/envs/cuml-0912/include/python3.7m -c ucp/_libs/src/c_util.c -o build/temp.linux-x86_64-3.7/ucp/_libs/src/c_util.o -std=c99 -DUCX_PY_CUDA
gcc -pthread -shared -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -L/home/oyilmaz/miniconda3/envs/cuml-0912/lib -Wl,-rpath=/home/oyilmaz/miniconda3/envs/cuml-0912/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L/home/oyilmaz/miniconda3/envs/cuml-0912/lib -L/usr/local/cuda/lib64 -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include build/temp.linux-x86_64-3.7/ucp/_libs/utils.o build/temp.linux-x86_64-3.7/ucp/_libs/src/c_util.o -lucp -luct -lucm -lucs -lcuda -lcudart -o /home/oyilmaz/Documents/rapids/ucx-py/ucp/_libs/utils.cpython-37m-x86_64-linux-gnu.so
building 'ucp._libs.send_recv' extension
gcc -pthread -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include -fPIC -I/home/oyilmaz/miniconda3/envs/cuml-0912/include/python3.7m -c ucp/_libs/send_recv.c -o build/temp.linux-x86_64-3.7/ucp/_libs/send_recv.o -std=c99 -DUCX_PY_CUDA
gcc -pthread -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include -fPIC -I/home/oyilmaz/miniconda3/envs/cuml-0912/include/python3.7m -c ucp/_libs/src/c_util.c -o build/temp.linux-x86_64-3.7/ucp/_libs/src/c_util.o -std=c99 -DUCX_PY_CUDA
gcc -pthread -shared -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -L/home/oyilmaz/miniconda3/envs/cuml-0912/lib -Wl,-rpath=/home/oyilmaz/miniconda3/envs/cuml-0912/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L/home/oyilmaz/miniconda3/envs/cuml-0912/lib -L/usr/local/cuda/lib64 -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include build/temp.linux-x86_64-3.7/ucp/_libs/send_recv.o build/temp.linux-x86_64-3.7/ucp/_libs/src/c_util.o -lucp -luct -lucm -lucs -lcuda -lcudart -o /home/oyilmaz/Documents/rapids/ucx-py/ucp/_libs/send_recv.cpython-37m-x86_64-linux-gnu.so
building 'ucp._libs.core' extension
gcc -pthread -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include -fPIC -I/home/oyilmaz/miniconda3/envs/cuml-0912/include/python3.7m -c ucp/_libs/core.c -o build/temp.linux-x86_64-3.7/ucp/_libs/core.o -std=c99 -DUCX_PY_CUDA
gcc -pthread -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include -fPIC -I/home/oyilmaz/miniconda3/envs/cuml-0912/include/python3.7m -c ucp/_libs/src/c_util.c -o build/temp.linux-x86_64-3.7/ucp/_libs/src/c_util.o -std=c99 -DUCX_PY_CUDA
gcc -pthread -shared -B /home/oyilmaz/miniconda3/envs/cuml-0912/compiler_compat -L/home/oyilmaz/miniconda3/envs/cuml-0912/lib -Wl,-rpath=/home/oyilmaz/miniconda3/envs/cuml-0912/lib -Wl,--no-as-needed -Wl,--sysroot=/ -L/home/oyilmaz/miniconda3/envs/cuml-0912/lib -L/usr/local/cuda/lib64 -I/home/oyilmaz/miniconda3/envs/cuml-0912/include -I/usr/local/cuda/include build/temp.linux-x86_64-3.7/ucp/_libs/core.o build/temp.linux-x86_64-3.7/ucp/_libs/src/c_util.o -lucp -luct -lucm -lucs -lcuda -lcudart -o /home/oyilmaz/Documents/rapids/ucx-py/ucp/_libs/core.cpython-37m-x86_64-linux-gnu.so
python3 -m pip install -e .
Obtaining file:///home/oyilmaz/Documents/rapids/ucx-py
Installing collected packages: ucp
  Found existing installation: ucp 0.0.0
    Uninstalling ucp-0.0.0:
      Successfully uninstalled ucp-0.0.0
  Running setup.py develop for ucp
Successfully installed ucp
```

**Comment by oyilmaz-nvidia** [comment]
I guess it's picking up the python2 rather than python3.

**Comment by quasiben** [comment]
sorry, the markdown messed up the syntax it should be :

```
python -c 'import ucp; print(ucp.__version__)
```

note the `__`

**Comment by oyilmaz-nvidia** [comment]
Ok, it's working now. Thanks!

**Comment by quasiben** [comment]
Thank you!   Note in https://github.com/rapidsai/ucx-py/pull/193 i've added versions to make things more clear
