### ISSUE TITLE
MultiNode UCX Test

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#200]
From @pentschev:

> Dask workers to connect to the scheduler and run without segfaults or other errors. However, I confirmed that there’s only traffic on one of the InfiniBand interfaces in each node, which was consistent with the ucp_client_server test. Running Dask over TCP is faster than running with UCX and I wasn’t able to identify why, but I suspect it’s related to only one IB interface getting traffic on each node. The behavior is exactly the same on our DGXs and Prometheus.
Summit nodes contain only ib0, there I was able to verify that UCX works and is faster than TCP. I haven’t looked at traffic details to verify the bandwidth gain, but running a simple SVD test (on an array of shape (1_000_000, 1_000)) takes 6.7 seconds on 4 nodes with IB and 11.3 seconds on 4 nodes on TCP (over Ethernet).

Testing with
```
# scheduler
UCXPY_IFNAME="enp1s0f0" UCX_TLS=tcp,sockcm,cuda_copy,cuda_ipc UCX_SOCKADDR_TLS_PRIORITY=sockcm /home/nfs/pentschev/miniconda3/envs/ucx101/bin/python -m distributed.cli.dask_scheduler --interface enp1s0f0 --dashboard-address :8797 --protocol ucx

# workers
UCXPY_IFNAME="enp1s0f0" UCX_TLS=tcp,sockcm,cuda_copy,cuda_ipc UCX_SOCKADDR_TLS_PRIORITY=sockcm /home/nfs/pentschev/miniconda3/envs/ucx101/bin/python -m dask_cuda.dask_cuda_worker ucx://10.33.227.161:8786
```

**Comment by Akshay-Venkatesh** [comment]
You need `UCX_TLS=rc,tcp,sockcm,cuda_copy,cuda_ipc` for IB. `rc` or `dc` is the preferred UCT to enable IB.

**Comment by pentschev** [comment]
Multinode UCX is working well lately. For future reference, the correct IB interface has to be set according to distance to each GPU, to help with that [TopologicalDistance](https://github.com/rapidsai/ucx-py/blob/branch-0.15/ucp/_libs/topological_distance.pyx) can be used.
