### ISSUE TITLE
Place Endpoint's tags in a struct

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#210]
As [tags used by `Endpoint`]( https://github.com/rapidsai/ucx-py/blob/14e93062da4419a66ac875d28f62863fdfa06416/ucp/_libs/core.pyx#L299-L302 ) seem to always be dealt with [in batches]( https://github.com/rapidsai/ucx-py/blob/14e93062da4419a66ac875d28f62863fdfa06416/ucp/_libs/core.pyx#L44 ), it might make sense to just create a `struct` to contain them all with appropriate names. This should help clarify the code in points where [the order of indices for tags is non-intuitive]( https://github.com/rapidsai/ucx-py/blob/14e93062da4419a66ac875d28f62863fdfa06416/ucp/_libs/core.pyx#L50 ).

**Comment by madsbk** [comment]
I totally agree :)

**Comment by jakirkham** [comment]
Put together PR ( https://github.com/rapidsai/ucx-py/pull/215 ) to address this.
