### ISSUE TITLE
CI: cupy tests skipped

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#213]
The cupy tests are [skipped](https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci-cuda101%2Fucx-py%2Fprb%2Fucx-py-gpu-build/detail/ucx-py-gpu-build/73/pipeline#log-2413) even though it is installed here: 
https://github.com/rapidsai/ucx-py/blob/branch-0.10/ci/gpu/build.sh#L49

Any ideas what is wrong?

cc. @quasiben @jakirkham

**Comment by quasiben** [comment]
Yes, CuPy is not included in the CI setup.  I'll get resolved today.

**Comment by jakirkham** [comment]
Thanks Ben! 😄
