### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#216]
The ucx-py has a number of stale branches.  @Akshay-Venkatesh any reason to keep the older branches.  This would mean keeping only `branch-0.10` and `devel`

cc @pentschev

**Comment by jakirkham** [comment]
What is the purpose of the `devel` branch currently? It appears to have diverged from `branch-0.10`. Are the changes in it relevant? Should we include them in `branch-0.10`? Also how should the `devel` branch be maintained going forward?

**Comment by quasiben** [comment]
`devel` is currently serving two purposes:

1) support legacy users/codebase should they exits
2) reference implementation while we work out problems with the new bindings

I don't think `devel` will be maintained moving forward

**Comment by jakirkham** [comment]
In that case, should we rename it to something like `legacy` or perhaps merge it into `branch-0.10` with a no change merge commit?

**Comment by jakirkham** [comment]
Thoughts?

**Comment by madsbk** [comment]
I think at renaming `devel` to `legacy` is a good idea

**Comment by quasiben** [comment]
I like that too -- @Akshay-Venkatesh do you have thoughts here ?

**Comment by jakirkham** [comment]
Sounds like everyone is on-board. So renamed `devel` to `legacy`.

To preserve the history (should we decide to delete `legacy` later), have done a no-op merge into `branch-0.10`. This leaves `branch-0.10` unchanged, but keeps the history from `legacy` accessible.

Should we close this issue?

**Comment by quasiben** [comment]
This has been resolved
