### ISSUE TITLE
TODO: exceptions in this callback is never showed when no get_exception_handler() is set

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#217]
Found the following TODO noted in the code. Am creating this issue as a placeholder for tracking it.

https://github.com/rapidsai/ucx-py/blob/bbe8d7be7a1a13e938a20a44355e85beb4693d6f/ucp/_libs/core.pyx#L34-L41

**Comment by pentschev** [comment]
A lot has changed in that code and neither the code nor the note exist anymore, tentatively closing but feel free to reopen if needed.
