### ISSUE TITLE
TODO: make sure that a potential shutdown message isn't cancelled

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#218]
Found the following TODO noted in the code. Am creating this issue as a placeholder for tracking it.

https://github.com/rapidsai/ucx-py/blob/bbe8d7be7a1a13e938a20a44355e85beb4693d6f/ucp/_libs/core.pyx#L361-L368

**Comment by pentschev** [comment]
The mechanism this issue refers to has been changed since, thus closing the issue. Feel free to reopen if necessary.
