### ISSUE TITLE
Alternatives to using UCX environment variables

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#221]
Today we recommend users set environment variables to configure UCX correctly. That said, those of us less familiar with UCX don’t always understand what they mean. Plus there is always the risk we forget to set these or use the wrong combination on a different machine. Finally it can complicate some deployment workflows to set these environment variables.

Given these challenges, I’m curious if we can eschew the use of environment variables in favor of some ucx-py level configuration. For instance could ucx-py call into UCX to enable or disable these features? Could ucx-py/UCX detect what a machine supports and set a sensible, performant default automatically? Thoughts?

cc @Akshay-Venkatesh @pentschev @quasiben

**Comment by mrocklin** [comment]
I'll echo this.  Less sophisticated Python users are often not culturally familiar with environment variables.

**Comment by pentschev** [comment]
I understand the points here, and I do agree that the environment variables are very inconvenient for Python users. I don't know if this is the "right way" forward, but I would just like to point out that I'm working on dask-cuda to allow enabling UCX via arguments, which ensures the correct variables are set, e.g., https://github.com/rapidsai/dask-cuda/blob/branch-0.10/dask_cuda/dgx.py#L14-L15.

This effort is not yet complete, but I hope to eventually have variables to control that in all necessary places of dask-cuda.

**Comment by MattBBaker** [comment]
Chiming in from the UCX perspective, the way those configs are adjusted at the ucp api level is through the function ucp_config_modify(). So for example, `status = ucp_config_modify(config, "MEMTYPE_CACHE", "n");` Will produce the desired result of setting `UCX_MEMTYPE_CACHE=n` in the environment. 

So the desired config mechanism could be a matter of implementing a set_config() function that takes a hash of desired config parameters and, when the ApplicationContext is initialized, pass that in as a parameter to be used to adjust the parameters before passing them to ucp_init()

**Comment by jakirkham** [comment]
Thanks for the work here Peter and info Matt.

What if a user decides to modify these after initializing a UCX session? Is there a way to do this? Or would it require shutting down the existing session and restarting.

**Comment by madsbk** [comment]
> Thanks for the work here Peter and info Matt.
> 
> What if a user decides to modify these after initializing a UCX session? Is there a way to do this? Or would it require shutting down the existing session and restarting.

I don't think so :/ @MattBBaker @Akshay-Venkatesh?

Regarding making config options programmable, checkout: https://github.com/rapidsai/ucx-py/pull/225

**Comment by MattBBaker** [comment]
@jakirkham Yes, since the config options affect how end points get wired up and how memory is managed the only way to make configuration changes apply is to tear down all the EPs and contexts anyways, so full reinitialzation is the only way of doing that.

**Comment by jakirkham** [comment]
Thanks for sharing that @madsbk! @pentschev, you may be interested in looking at PR ( https://github.com/rapidsai/ucx-py/pull/225 ) given it may be a useful hook for dask-cuda.

Thanks for confirming @MattBBaker! That's what I figured, but wanted to make sure I wasn't missing something. 🙂

**Comment by MattBBaker** [comment]
@mrocklin UCX should be able to make reasonable decisions with UCX_TLS=all. The UCP wireup protocol exchanges performance information of each node and they automatically agree on the best transport.

**Comment by jakirkham** [comment]
IOW we should be able to close issue ( https://github.com/rapidsai/ucx-py/issues/237 ) and just always set `UCX_TLS=all`. Is that correct Matt?

**Comment by MattBBaker** [comment]
Yes. If there is a case where UCX makes a bad choice we would like to try and fix it at the wire up level.
