### ISSUE TITLE
Document UCX usage with Dask

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#229]
UCX/UCX-py can be installed on linux machines with and without GPUs.  We should document and test using dask in non-GPU environments.  

## Create an env

> conda create -n ucx-dask -c conda-forge -c jakirkham/label/ucx-new  ucx-proc=*=cpu ucx ucx-py python=3.7 dask distributed

## Example usage of Distributed with UCX

> dask-scheduler --protocol ucx
> dask-worker ucx://127.0.0.1:8786

The above probably does not and will require some configuration changes to distributed.  @mrocklin do you have any time/interest in building a small example of distributed with ucx TCP only ?

**Comment by pentschev** [comment]
This will require https://github.com/rapidsai/dask-cuda/pull/152, a minimal (DGX) example would look like:

```python
import os
import time
import numpy as np
import dask.array as da
import cupy
from distributed import Client
from dask_cuda import DGX
from dask_cuda.utils import get_ucx_env


#ucx_env = get_ucx_env(interface="enp1s0f0", enable_infiniband=True, enable_nvlink=True)
ucx_env = get_ucx_env(interface="enp1s0f0", enable_tcp=True)
os.environ.update(ucx_env)


if __name__ == "__main__":
    #dgx = DGX(interface="enp1s0f0", protocol="ucx", enable_infiniband=True, enable_nvlink=True)
    dgx = DGX(interface="enp1s0f0", protocol="ucx", enable_tcp_over_ucx=True)
    client = Client(dgx)

    rs = da.random.RandomState(RandomState=cupy.random.RandomState)
    a = rs.normal(10, 1, (int(2e4), int(2e4)), chunks=(int(2.5e3), int(2.5e3)))
    x = a + a.T

    start = time.time()
    res = x.compute()
    print("x.compute() time:", time.time() - start)
```

But `dask-cuda-worker` is still not UCX-capable.

**Comment by quasiben** [comment]
Thank you @pentschev for laying out how this should work with dask-cuda.  If we are in a non-cuda environment (only TCP) do you think dask can use UCX without `dask-cuda`  or is the configuration management too high at the moment ?

**Comment by VibhuJawa** [comment]
> But `dask-cuda-worker` is still not UCX-capable.

I just want to confirm as the pr#152 is now merged, Is `dask-cuda`  worker now supposed to be `ucx` compatible  ? 

If yes, could you share a updated minimal example for a `dgx`  setup as i think does not have the `interface` argument which you show in above example. 

> ucx_env = get_ucx_env(interface="enp1s0f0", enable_tcp=True)

see: https://github.com/rapidsai/dask-cuda/blob/ac37fedbb01b81d99b3afe0038b5981b9f115ce7/dask_cuda/utils.py#L132-L134

**Comment by pentschev** [comment]
Sorry for the late reply @VibhuJawa . I started posting the example here, but I realized that's useful to file an issue for the bug we see consistently with UCX, please follow the example from https://github.com/rapidsai/ucx-py/issues/284.

A few notes about it:

* So far, `DGX` is the only way of running with UCX that includes all setup necessary, `LocalCUDACluster` _may_ work but I couldn't test it so far, and `dask-cuda-worker` is definitely not working yet;
* You can choose to enable TCP only, or have InfiniBand/NVLink (including both) with variables at the top. Enabling InfiniBand/NVLink implies TCP, so `enable_tcp_over_ucx=True` becomes redundant;
* We've been testing UCX to enable everything automatically, so the variables may be removed in the near future;
* The example uses CuPy and crashes after a few iterations (even zero at times) and we couldn't yet find the issue. I don't think cuDF was tested so far with dask-cuda, so please report any issues you find in the dask-cuda repo.

**Comment by VibhuJawa** [comment]
> 
> A few notes about it:
> 
> * So far, `DGX` is the only way of running with UCX that includes all setup necessary, `LocalCUDACluster` _may_ work but I couldn't test it so far, and `dask-cuda-worker` is definitely not working yet;
> * You can choose to enable TCP only, or have InfiniBand/NVLink (including both) with variables at the top. Enabling InfiniBand/NVLink implies TCP, so `enable_tcp_over_ucx=True` becomes redundant;
> * We've been testing UCX to enable everything automatically, so the variables may be removed in the near future;
> * The example uses CuPy and crashes after a few iterations (even zero at times) and we couldn't yet find the issue. I don't think cuDF was tested so far with dask-cuda, so please report any issues you find in the dask-cuda repo.

Thanks a lot for the detailed response @pentschev  .  Will be trying ucx with dask-cuda soon and will report back any bugs i find.

**Comment by quasiben** [comment]
Done:
https://ucx-py.readthedocs.io/en/latest/dask.html
