### ISSUE TITLE
Make Endpoint an extension type

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#232]
It would be useful to define `Endpoint` as an extension type. Particularly as its attributes can be defined as specific C-level types. This would simplify interactions with other C-level types and other extension types.

**Comment by madsbk** [comment]
I am not sure; since `Endpoint` is a public class I think it is more user-friendly to have it as a regular Python class. 
Alternatively, we could have a public regular Python class that exposes the public API and then have a  Cython endpoint class as back-end?

**Comment by jakirkham** [comment]
At least having some part of it be an extension type would be helpful as we can then type its attributes.

**Comment by madsbk** [comment]
> At least having some part of it be an extension type would be helpful as we can then type its attributes.

Agree, I will work on a PR tomorrow.

**Comment by jakirkham** [comment]
Now that there is a private portion, [`_Endpoint`]( https://github.com/rapidsai/ucx-py/blob/424206e0ff9ebdec8ecaf771f36a893b9eb76018/ucp/_libs/core.pyx#L366 ), would it make sense to turn that into an extension type?

**Comment by madsbk** [comment]
> Now that there is a private portion, [`_Endpoint`](https://github.com/rapidsai/ucx-py/blob/424206e0ff9ebdec8ecaf771f36a893b9eb76018/ucp/_libs/core.pyx#L366), would it make sense to turn that into an extension type?

Yes, if it makes the code cleaner.

**Comment by jakirkham** [comment]
Closing as this doesn't really seem to be needed any more. Can always reopen if that changes.
