### ISSUE TITLE
Inconsistent separation of public vs private API

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/ucx-py#235]
I just finished updating cuML to use the new ucx-py API and I'm really happy for the changes! I'm also happy for the more subtle changes, like no longer having to call `.encode()` on the IP for creating an endpoint.

While diving a bit further into the Cython, and seeing the the main entrypoint was renamed to `public_api.py`, I did find that I still needed to physically look through the underlying implementations of `Endpoint` and `Listener` in `core.pyx` to see how to use them. `core.pyx` doesn't look like it was documented for public consumption, though any user that wants to initialize endpoints and send messages w/ UCX are going to need to interact w/ these two classes.

It would be nice if we could bring these two classes closer to the public API, perhaps by making them available in the `public_api.py` file and wrapping all the underlying calls to the ucp c-api in `core.pyx`. At the very least, we should document them more heavily.

**Comment by madsbk** [comment]
Thanks!
Regarding the public API, I think you are right. Having both a public and a private class of `Endpoint` and `Listener` would also address @jakirkham issue: https://github.com/rapidsai/ucx-py/issues/232.

What is your thoughts @jakirkham?

**Comment by jakirkham** [comment]
Yeah was just reading this issue. That sounds reasonable.

Cython can also make extension types available from C code. Though IDK if we have a use case for that as well.

**Comment by jakirkham** [comment]
@cjnolet, do you have any particular thoughts on what should be part of that public Python API?

**Comment by cjnolet** [comment]
I think most users will interact with the `Endpoint` class, primarily using the functions `send`, `receive`, `closed` and `close()`.

cuML is a little bit of a special case because we also need to get the pointers to the underlying `ucp_ep_h` and `ucp_worker_h` instances. It would be nice to have a method to get this pointer with a similar API volatility guarantee as what the public API provides, so it might also be useful to expose this as well. 

Since we need to create a listener in order to create endpoints, it might make sense to at least expose a `Listener` wrapper with functions to test if a listener is closed and close it.
