### ISSUE TITLE
Discover connectivity of node(s)

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#237]
Currently configuring performant connectivity with UCX is a bit of a challenge and may require looking at the network topology and hardcoding connections as discussed a bit in [this blogpost]( https://blog.dask.org/2019/06/09/ucx-dgx ). Also other hardware may use a different configuration. This is a lot for the average user to keep track of and we are only discussing one node thus far. Of course this increases exponentially in complexity as more nodes are added.

To handle these issues and minimize configuration burden on the user, it would be useful to discover the topology programmatically. Once discovered this information could be shared with other libraries or could be used by default to maximize performance.

**Comment by jakirkham** [comment]
cc @pentschev @madsbk @quasiben @mrocklin

**Comment by pentschev** [comment]
Yeah, this is in my todo list, had no time yet. We already find CPU affinity automatically, next step is to find shortest-path InfiniBand automatically. The first is done via NVML (pynvml), but the latter doesn't seem to be possible directly with NVML -- even though nvidia-smi prints that -- and we may need to go to libnuma/libpci for that.

**Comment by pentschev** [comment]
The current CPU affinity work is in dask-cuda, but eventually we may move it here or keep in both places, which might make sense when they aren't used in conjunction with each other.

**Comment by quasiben** [comment]
I like the idea of auto-discovery.  We've fallen into a couple of pits but maybe those can be codified into auto-discovery as well.    Recent pits would include permissions around nvml, configuration challenges with IB interfaces (IP over IB).  There is some future where UCX is making these decisions for the user -- whether that future is months or years away is not something I know.

**Comment by pentschev** [comment]
> There is some future where UCX is making these decisions for the user -- whether that future is months or years away is not something I know.

That is good news, but is this future part of OpenUCX or UCX-Py? If the former, is there an issue filed for that already?

**Comment by jakirkham** [comment]
@Akshay-Venkatesh, do you have any thoughts on @pentschev's question above?

**Comment by jakirkham** [comment]
Assuming I'm reading ( https://github.com/rapidsai/ucx-py/issues/221#issuecomment-542351562 ) correctly. This already happens during setup as long as we set `UCX_TLS=all` beforehand.

**Comment by jakirkham** [comment]
Closing as this seems to be addressed by PR ( https://github.com/rapidsai/ucx-py/pull/342 ). Can follow up on any additions/refinements in subsequent issues.
