### ISSUE TITLE
Include non-GPU conda installation instructions in README

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#241]
@jakirkham , are we ready for this?

**Comment by jakirkham** [comment]
Sure. Instead of `ucx-proc=*=gpu` one might write `ucx-proc=*=<proc type>` and explain `<proc type>` is either `cpu` or `gpu`.

**Comment by mrocklin** [comment]
Is it too early to include this in the README?

**Comment by jakirkham** [comment]
I haven't been actively using these packages myself. So I can't really comment on how useable they are or are not. That would be a question for someone else I think. Alternatively if you have a use case for them, maybe you could try them out on that use case and see how well they behave. In either case the feedback would be welcome. 🙂

**Comment by mrocklin** [comment]
Sure.  I'll try things out locally and then report back.

**Comment by jakirkham** [comment]
Thanks for doing that 🙂

**Comment by pentschev** [comment]
I tried the packages, for a while and I didn't notice any difference from the ones I compiled from source, so I think they're fairly safe. Thanks @jakirkham for them! :)

**Comment by jakirkham** [comment]
Were those the CPU ones, the GPU ones, or both?

**Comment by pentschev** [comment]
GPU, I didn't test the CPU at all so far.

**Comment by mrocklin** [comment]
Hrm, I'm getting this

```
mrocklin@carbon:~$ conda create -n ucx -c conda-forge -c jakirkham/label/ucx  ucx-proc=*=cpu ucx ucx-py python=3.7 dask ipython
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                             
                                                                                                                   
UnsatisfiableError: The following specifications were found to be incompatible with each other:                    



Package ucx-proc conflicts for:
ucx-proc[build=cpu]
```

**Comment by mrocklin** [comment]
My guess is that while there are cpu-only ucx packages, the ucx-py packages in @jakirkham 's channel somehow need the GPU variants.

**Comment by quasiben** [comment]
@mrocklin can you trry with the channel `jakirkham/label/ucx-new` (notice the `new`)

**Comment by mrocklin** [comment]
That does work.  Thanks @quasiben .  

I'm happy to submit a PR to the README with this, but I'm also happy to wait if we're going to consolidate on a particular channel in the near future.

**Comment by jakirkham** [comment]
Was leaving the packages with the API pre-Mads rewrite in the `ucx` label in case it was important to people. So noting `ucx-new` in the README is probably worthwhile. Though I wouldn't object if we wanted to reorg the packages somehow.

**Comment by mrocklin** [comment]
Is the plan to move this to conda-forge at some point?  If so, when is that
likely to happen?  (no time pressure though)

**Comment by jakirkham** [comment]
That's the plan. We need OpenUCX to make a release though. Even an RC would help. Sound like in a couple weeks.

xref: https://github.com/openucx/ucx/issues/4262
xref: https://github.com/conda-forge/ucx-split-feedstock/issues/31

**Comment by jakirkham** [comment]
Short term we can add our stuff to the RAPIDS fork of the feedstock.

**Comment by jakirkham** [comment]
Once that does happen though we can fold in the ucx-py build at the same time. So both can be published to conda-forge then.

**Comment by jakirkham** [comment]
Handling this along with other things in PR ( https://github.com/rapidsai/ucx-py/pull/253 ).
