### ISSUE TITLE
[DOC] Readme Suggestions

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/ucx-py#248]
I was trying to build `ucx` using dask and ran into these issues: 

### 1. **Incorrect Dask URL:**
The below url for dask is incorrect i think as it should point to dask instead of rapidsai:

https://github.com/rapidsai/ucx-py/blob/branch-0.10/README.md#dask
```
    git clone git@github.com:rapidsai/dask.git
```

### 2. **http instead of git@**
Also, i am wondering if it will be better to have a `http` urls instead of `git@url` in docs as users wont always have `ssh` keys setup across containers. 

### 3. Dask-cuda conda seems to be pulling previous non ucx-version
Below seems to be pulling previous version of dask-cuda, we may want to add the installation command with with all the dependencies.

Instead of below:
```
conda install -c rapidsai dask-cuda
```

May be something like:
```
conda install -c rapidsai-nightly/label/cuda10.0 -c rapidsai -c nvidia -c numba -c conda-forge dask-cuda
```

### 4. Script to check if ucx is working for a non source installation

This issue may be similar to document UCX usage with dask issue but it will be nice to have test/script i can run which checks if ucx was set up correctly. 

https://github.com/rapidsai/ucx-py/issues/229

**Comment by quasiben** [comment]
Thanks @VibhuJawa for the issue! 

> I was trying to build `ucx` using dask and ran into these issues:
> 
> ### 1. **Incorrect Dask URL:**
> The below url for dask is incorrect i think as it should point to dask instead of rapidsai:
> 
> https://github.com/rapidsai/ucx-py/blob/branch-0.10/README.md#dask
> ```
>     git clone git@github.com:rapidsai/dask.git
> ```
> 

Yes, the url should is incorrect
> ### 2. **http instead of git@**
> Also, i am wondering if it will be better to have a `http` urls instead of `git@url` in docs as users wont always have `ssh` keys setup across containers.
> 

I think leaving as `git@url` is ok but I don't have a strong preference.  But I don't think we have to be to worried about ssh keys and containers.  My assumption here is that those using containers will be mostly using conda packages.  Do you think envs with containers will still want bleeding edge ?

> ### 3. Dask-cuda conda seems to be pulling previous non ucx-version
> Below seems to be pulling previous version of dask-cuda, we may want to add the installation command with with all the dependencies.
> 
> Instead of below:
> 
> ```
> conda install -c rapidsai dask-cuda
> ```
> 
> May be something like:
> 
> ```
> conda install -c rapidsai-nightly/label/cuda10.0 -c rapidsai -c nvidia -c numba -c conda-forge dask-cuda
> ```
> 
Agreed

> ### 4. Script to check if ucx is working for a non source installation
> This issue may be similar to document UCX usage with dask issue but it will be nice to have test/script i can run which checks if ucx was set up correctly.
> 
> #229

I'm retooling the benchmark code now hopefully that will suffice.  When I'm done I'll ping you on the PR

**Comment by VibhuJawa** [comment]
> I think leaving as `git@url` is ok but I don't have a strong preference. But I don't think we have to be to worried about ssh keys and containers. My assumption here is that those using containers will be mostly using conda packages. Do you think envs with containers will still want bleeding edge ?
> 
> >

FWIW, As a user who switches across containers nightly containers regularly i personally will like that , I am not sure about other users .   

4. Script to check if ucx is working for a non source installation
This issue may be similar to document UCX usage with dask issue but it will be nice to have test/script i can run which checks if ucx was set up correctly.


> I'm retooling the benchmark code now hopefully that will suffice. When I'm done I'll ping you on the PR

Thanks a lot , please let me know when you have the pr ready, I would love to give it a try.
