### ISSUE TITLE
Endpoint Creation Failure

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#250]
When creating a problematic endpoint ucp blocks all signals:

```
In [1]: import ucp
/home/nfs/bzaitlen/GitRepos/ucx-py/ucp/__init__.py:20: UCXWarning: Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX
  "Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX", UCXWarning

In [2]: await ucp.create_endpoint('10.33.227.165', 13399)
[1571082409.103697] [dgx15:75095:0]      sockcm_ep.c:143  UCX  ERROR failed to connect to 10.33.227.165:13399
^C^C^C^C^C^C^C^C^C^C
```

`crtl-c`  has no effect

**Comment by quasiben** [comment]
Thanks for the comment @MattBBaker . 

I am using a debug build of UCX, however with `UCX_HANDLE_ERRORS=bt` i still am unable crt-l c out of the process:

```
(cudf_dev10.1) bzaitlen@dgx15:~$ UCX_HANDLE_ERRORS=bt ipython
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ucp
/home/nfs/bzaitlen/GitRepos/ucx-py/ucp/__init__.py:20: UCXWarning: Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX
  "Setting env UCX_MEMTYPE_CACHE=n, which is required by UCX", UCXWarning

In [2]: await ucp.create_endpoint('10.33.227.165', 13399)
[1571169984.704046] [dgx15:53912:0]      sockcm_ep.c:143  UCX  ERROR failed to connect to 10.33.227.165:13399
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by jakirkham** [comment]
I think the morale of the story here is we need to start performing signal handling in ucx-py. UCX is doing the right thing from a C standpoint by raising these signals. We just need to handle them in ucx-py more gracefully. Possibly by converting the signals into Python exceptions.

I know the [`cysignals` library]( https://github.com/sagemath/cysignals ) provides [some useful utilities for signal handling in Cython]( https://cysignals.readthedocs.io/en/latest/signals.html#handling-other-signals ). These will promote the signals to Python exceptions, which can be handled more nicely. Perhaps using it would help us here? Though it is worth noting it is LGPL3.

Alternatively we might want to look into the [Python builtin `signal` module]( https://docs.python.org/3.7/library/signal.html ). Presumably we could roll our own solution with this.

There is probably a third solution here where we write some C code that acts as a signal handler and constructs a Python exception from it that it emits.

**Comment by jakirkham** [comment]
FWIW opened this upstream issue ( https://github.com/cython/cython/issues/3192 ) on signal handling in Cython.

**Comment by jakirkham** [comment]
Broke out the C signal handling point as its own issue. ( https://github.com/rapidsai/ucx-py/issues/283 )

**Comment by jakirkham** [comment]
Retried this today. The issue still occurs, but Ctrl+C did exit successfully. 🎉

Could you please retry @quasiben?

**Comment by quasiben** [comment]
Yes!  crt+c did exit successfully.  Any idea what resolved it ?

**Comment by pentschev** [comment]
I think this has been resolved, I can't recall seeing this recently. I'm tentatively closing, please reopen if I'm mistaken.
