### ISSUE TITLE
Drop `scripts` directory

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#264]
The [`scripts` directory in the ucx-py repo]( https://github.com/rapidsai/ucx-py/tree/c197da2fb6eb2f7b0a5541ec65a0d49950b5bcaf/scripts ) appears to contain a bunch of old scripts. While useful at the time, these don't appear to have been updated and may depend on patterns that no longer work. Given this, it seems reasonable to remove it. Thoughts?

**Comment by quasiben** [comment]
yes, I think we can delete this directory

**Comment by jakirkham** [comment]
Ok. Submitted PR ( https://github.com/rapidsai/ucx-py/pull/267 ) to drop it.
