### ISSUE TITLE
Build docs on CI

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#278]
We recently started adding docs to ucx-py. ( https://github.com/rapidsai/ucx-py/pull/273 ) Would be good to test that they build as part of CI. One option would be to do this as part of gpuCI. Not sure how this is handled. Another would be to [enable the beta ReadTheDocs feature for building PRs]( https://blog.readthedocs.com/building-docs-for-pull-requests/#getting-started ). We could also do both.

**Comment by pentschev** [comment]
@jakirkham could you confirm if this is still relevant? I'm not sure what's the current status.

**Comment by jakirkham** [comment]
It's not done currently. Would be nice to do.

**Comment by quasiben** [comment]
So folks are aware of what we are doing now:

1) RTD does not have libnuma installed on build machines and UCX throw an error on import if it does not exist.  To over come this issue I build and uploaded a UCX [conda package without numa](https://anaconda.org/quasiben/ucx/files)

2) RTD is currently pointed at my branch of ucx-py which points to the nonuma conda package: https://github.com/quasiben/ucx-py/blob/56482570fe37d99c2df73ba2e8c478c047052e74/conda/environments/builddocs_py37.yml#L19

3) when we merge doc edits I merge my branch with latest edits and manually trigger a build

This system is not great...

**Comment by jakirkham** [comment]
FWIW RTD is working on adding `apt-get` support ( https://github.com/readthedocs/readthedocs.org/pull/8065 ). So that might be another way to address installing `libnuma`

**Comment by jakirkham** [comment]
OPS recently enabled PR builds for RTD, which addresses the original issue.

On the `libnuma` point, have a rough PR ( https://github.com/rapidsai/ucx-py/pull/734 ) to use the new RTD `apt` support, which they are deploying next Tuesday afternoon. So that should address this secondary issue.

Given this will go ahead and close this out as the original issue was already addressed and the 2nd point soon will be
