### ISSUE TITLE
Failing cuDF + ucx example

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#297]
While repairs are being made to dask-cuda/distributed I wanted to test out some of the work.

With https://github.com/dask/distributed/pull/3171 and latest of ucx-py I manually setup a dask cluster:

### Scheduler
UCXPY_LOG_LEVEL=DEBUG CUDA_VISIBLE_DEVICES=0,1 UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm UCX_SOCKADDR_TLS_PRIORITY=sockcm dask-scheduler --protocol=ucx --interface=enp1s0f0

### Worker 1
UCXPY_LOG_LEVEL=DEBUG CUDA_VISIBLE_DEVICES=0,1 UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm UCX_SOCKADDR_TLS_PRIORITY=sockcm dask-worker ucx://10.33.225.165:8786 --interface=enp1s0f0 --no-nanny

### Worker 2
CUDA_VISIBLE_DEVICES=1,0 UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm UCX_SOCKADDR_TLS_PRIORITY=sockcm dask-worker ucx://10.33.225.165:8786 --interface=enp1s0f0 --protocol=ucx --no-nanny

After a cluster was created I ran the following notebook:
https://gist.github.com/1361607b1ba745764694eddc14c0553f

## Error on Scheduler

```
[1572297389.537917] [dgx15:79071]          cudamem.c:116  UCX  WARN cuMemGetAddressRange(devPtr=0x7fce15a00400) failed
/home/nfs/bzaitlen/miniconda3/envs/cudf_dev10.1/bin/python: symbol lookup error: /home/nfs/bzaitlen/miniconda3/envs/cudf_dev10.1/lib/ucx/libucm_cuda.so.0: undefined symbol: ucs_fatal_error_format
```

## Warning on Worker 1

> [1572294517.344223] [dgx15:44323]          cudamem.c:76   UCX  WARN cuPointerSetAttribute(0x0) failed: invalid argument

## Error on Worker 2
```
[1572297389.820405] [dgx15:79416:0]           sock.c:230  UCX  ERROR send(fd=-1) failed: Bad file descriptor
distributed.utils - ERROR - Comm Error "[Send #848] ep: 0x7f763814c0e0, tag: 0xc53d1ca974f4e54, nbytes: 8": Input/output error
Traceback (most recent call last):
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/utils.py", line 662, in log_errors
    yield
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/comm/ucx.py", line 126, in write
    await self.ep.send(np.array([len(frames)], dtype=np.uint64))
  File "/home/nfs/bzaitlen/GitRepos/ucx-py/ucp/public_api.py", line 270, in send
    await self._ep.send(buffer, nbytes=nbytes)
  File "ucp/_libs/core.pyx", line 630, in send
ucp.exceptions.UCXError: Comm Error "[Send #848] ep: 0x7f763814c0e0, tag: 0xc53d1ca974f4e54, nbytes: 8": Input/output error
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f7652218f28>>, <Task finished coro=<Worker.heartbeat() done, defined at /home/nfs/bzaitlen/GitRepos/
distributed/distributed/worker.py:855> exception=UCXError('Comm Error "[Send #848] ep: 0x7f763814c0e0, tag: 0xc53d1ca974f4e54, nbytes: 8": Input/output error')>)
```

I don't believe this are configuration errors.  @pentschev has suggested that these errors may be due to cuda context thread management

**Comment by jakirkham** [comment]
An undefined symbol usually suggests that a different version of a library is being used at runtime than was used at build time (hence why it is missing). Could you please share a bit more info about how things were built and installed here?

**Comment by pentschev** [comment]
The crash and both warnings should be solved after https://github.com/openucx/ucx/pull/4351 and https://github.com/openucx/ucx/pull/4374 got merged. Closing now, but feel free to reopen should you see any of those issues again.

**Comment by jakirkham** [comment]
@pentschev, could you please backport those patches to the `v1.7.x` branch of OpenUCX as well?

**Comment by pentschev** [comment]
They have been already: https://github.com/openucx/ucx/pull/4383, https://github.com/openucx/ucx/pull/4384.

**Comment by jakirkham** [comment]
That made my day. Thanks so much for staying on top of this Peter! 😀
