### ISSUE TITLE
New release: 0.2

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#298]
There has been a lot of development since we released 0.1. Also a fair bit of time has passed. It would be good to make another release. What do we think about doing a 0.2 release?

**Comment by pentschev** [comment]
IMO, I think we are close to getting Dask/UCX in a usable state. I believe/hope we are going to be in that state late this week or the next. I would definitely prefer to wait for that to do a new release, which we'll be able to use for some time to continue doing tests and perhaps have other people testing it further.

**Comment by jakirkham** [comment]
We could do a release now and a release then. 😉

The question from where I sit is when do we want usable Conda packages. If we want them now, it would be helpful to have a release now. If we don't want them now, then we can wait until we are ready to do a release. What do you think? 🙂

**Comment by quasiben** [comment]
Thanks for bringing this up @jakirkham!  First, I thought we were skipping right ahead to 0.10.  Second, i think would should do a release for 0.10 nowish.  Doing it now will help get all of the gpuCI setup and then we _should_ start having nightly conda packages built.  The question of stability will then largely go away because of the nightly packages.  Thoughts ?

**Comment by pentschev** [comment]
I thought we agreed on having nightly packages a few weeks ago already, no? Once there's the possibility of doing nightlies, then it doesn't matter when there's a release from a UCX-Py perspective, but only to match the release to RAPIDS release schedule.

**Comment by jakirkham** [comment]
Yeah we just haven't even done the 0.10 release that RAPIDS already did. It would also be valuable to capture the state of things here and align ourselves with the other projects.

Certainly we can do nightlies after that point. As note previously, these are not mutually exclusive.

**Comment by jakirkham** [comment]
Thoughts?

**Comment by jakirkham** [comment]
cc @madsbk

**Comment by jakirkham** [comment]
After talking with Ben earlier we are planning to go ahead with making a 0.2 release and build Conda packages. If there is anything critical that needs to go into that release, please let me know ASAP. Otherwise I'll plan on doing this in a few hours. Thanks all! 😄

**Comment by madsbk** [comment]
Fine by me :)

**Comment by jakirkham** [comment]
Have tagged the release. Publishing new packages with PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/40 ).

**Comment by jakirkham** [comment]
Closing as new packages have been published and are available on the CDN. Please give them a try. 🙂

**Comment by quasiben** [comment]
Thanks for pushing this out @jakirkham !
