### ISSUE TITLE
Running Examples on CI

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#308]
To help keep examples up-to-date, it would be useful to run these on CI to make sure they continue to work (in spite of changes to the API). Based on discussions with @quasiben and @pentschev, it sounds like we need multi-node CI to make this work. ( https://github.com/rapidsai/ops/issues/504 )

**Comment by pentschev** [comment]
I'll add these examples as well to my scripts running UCX-Py tests/benchmarks in our DGX machines for the time being, until we have multinode/multi-GPU CI support.

**Comment by pentschev** [comment]
This is now running on our Lab on a DGX-1. Results are published to https://github.com/pentschev/ucx-py-ci/issues .
