### ISSUE TITLE
NVLINK Memory Leak

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#315]
@pentschev found a memory link with UCXPY + cupy/cudf.  After a number of days @pentschev came across the config option `UCX_CUDA_IPC_CACHE=n` which seems to resolve the memory leak, however, we are now looking at another bug when using this option:

```
[1573072679.726035] [dgx15:28228:0] cuda_ipc_iface.c:361  UCX  ERROR cuIpcCloseMemHandle((CUdeviceptr)mapped_addr) is failed. ret:invalid argument
[dgx15:28228:0:28228] cuda_ipc_iface.c:208  Fatal: failed to unmap addr:0x7fabae000000
``

**Comment by MattBBaker** [comment]
I had a quick look in the UCT code for this, and it seems odd. The registration code seems to indicate that the same region may have the registration code called multiple times, but closes the CUdeviceptr unconditionally in the closing code. I'd look in the debug logs to see if this gets closed multiple times.

**Comment by quasiben** [comment]
Thanks @MattBBaker it does close the same memory twice and we are not sure why.  When using `UCX_CUDA_IPC_CACHE=n` it looks like the cache is never cleared out and continually grows.  I was expecting the cache to be purge on some condition.  For example, if data is sent from GPU0->GPU1 and the process on GPU1 deletes the object, that mmep data from GPU0 should be dropped/reused

**Comment by pentschev** [comment]
A small correction to @quasiben's latest comment, the cache is never cleared when `UCX_CUDA_IPC_CACHE=y` (i.e., enabled). I'm adding more trace information to debug the double-free error, it looks like the same mapped memory address is used for all transfers, which seems incorrect, and I haven't found where is that same memory buffer being reused.

**Comment by quasiben** [comment]
Yes!  Thank you @pentschev

**Comment by MattBBaker** [comment]
It looks like cuda_ipc impements the RDMA put/get_zcopy interface. That means that putting/getting to the same address is expected, since it's referencing the remote memory from an rkey. This maybe a bug in the core UCX.

**Comment by pentschev** [comment]
Would you say the bug is in attempting to free that memory multiple times, or in reusing the same address?

**Comment by MattBBaker** [comment]
The multiple frees. With how that part of the API works I would expect that what is going on is that one of the accelerators has gotten an address to the remote accelerator and is doing direct reads and writes, and somewhere in the pipe when cleaning up resources it tries to unmap the same address twice.

**Comment by pentschev** [comment]
Yeah, that makes sense. I'll file a bug report and see what they say before I "fix" something the wrong way.

**Comment by quasiben** [comment]
@pentschev worked a solution in UCX here https://github.com/openucx/ucx/pull/4431 which was then superseded by https://github.com/openucx/ucx/pull/4476

**Comment by pentschev** [comment]
Please note that the solution requires using `UCX_CUDA_IPC_CACHE=n` (UCX-Py default now), if you use `UCX_CUDA_IPC_CACHE=y` (UCX default) there's still a memory leak.
