### ISSUE TITLE
UCX Config changes

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#320]
UCX devs are discussing changes to UCX configuration:

- https://github.com/openucx/ucx/issues/4390
- https://github.com/openucx/ucx/pull/4373#issuecomment-552081984

I don't believe there is anything for us to do now as these changes will not be in 1.7 but it is something we should be aware of when we upgrade UCX

**Comment by pentschev** [comment]
I think there's not much for us to do here, unless we need something specific. FWIW, we've been running UCX 1.8 without requiring any config changes. What do you think @quasiben ?

**Comment by quasiben** [comment]
Agreed.  Let's close
