### ISSUE TITLE
Test ucx-py with v1.8 from UCX

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#323]
We've had some recent CI failures which were fixed by pinning v1.7.  I believe errors started popping up around https://github.com/openucx/ucx/commit/2b8829b2bed58cc3cf3232ca04f7a998b6fcfd45 -- maybe before.   As we move towards an official release we should contemplate what python bindings look like for multiple version of UCX

**Comment by MattBBaker** [comment]
Odd that change would cause issues. What failures was the CI throwing?

**Comment by quasiben** [comment]
not a very helpful error:

```
tests/test_send_recv.py::test_send_recv_cupy[True-<i8-16777216] Fatal Python error: Aborted

Current thread 0x00007f8fcb161700 (most recent call first):
  File "/conda/envs/gdf/lib/python3.6/asyncio/events.py", line 145 in _run
  File "/conda/envs/gdf/lib/python3.6/asyncio/base_events.py", line 1440 in _run_once
```
https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-gpu-build/detail/ucx-py-gpu-build/583/pipeline#log-2502

**Comment by jakirkham** [comment]
Probably need to reproduce it locally and run `gdb`. Should add if you use Python 3.8 it has the debug symbols.

**Comment by quasiben** [comment]
with #511 we can close this issue
