### ISSUE TITLE
[BUG] Error when starting the cluster using the dgx api

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/ucx-py#327]
#### [BUG] Error when starting the cluster using the dgx api

I am just trying to start a cluster in a notebook on `dgx-1` like below  but am running into errors.  

This is probably related  to https://github.com/rapidsai/ucx-py/issues/290 so please feel free to mark it as so if it is duplicate but as i am completely new to ucx, i was not sure.  

```python
from dask_cuda import DGX

enable_tcp_over_ucx=True
enable_infiniband=True
enable_nvlink=False

cluster = DGX(interface="enp1s0f0",
           protocol="ucx",
           enable_tcp_over_ucx=enable_tcp_over_ucx,
           enable_infiniband=enable_infiniband,
           enable_nvlink=enable_nvlink,
             )
```

It fails with the below error

```
ERROR Failed while trying to start scheduler process: Trying to reset UCX but not all Endpoints and/or Listeners are closed(). The following objects are still referencing ApplicationContext: 
  <ucp._libs.core._Listener object at 0x7fc922f5f288>

```

Full stack trace
<details>

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-3e10a2ad3ffb> in <module>
      9            enable_tcp_over_ucx=enable_tcp_over_ucx,
     10            enable_infiniband=enable_infiniband,
---> 11            enable_nvlink=enable_nvlink,
     12              )

~/miniconda3/envs/ucx/lib/python3.7/site-packages/dask_cuda-0.11.0b0-py3.7.egg/dask_cuda/dgx.py in DGX(interface, dashboard_address, threads_per_worker, silence_logs, CUDA_VISIBLE_DEVICES, protocol, enable_tcp_over_ucx, enable_infiniband, enable_nvlink, **kwargs)
    113 
    114     return SpecCluster(
--> 115         workers=spec, scheduler=scheduler, silence_logs=silence_logs, **kwargs
    116     )

~/miniconda3/envs/ucx/lib/python3.7/site-packages/distributed/deploy/spec.py in __init__(self, workers, scheduler, worker, asynchronous, loop, security, silence_logs, name)
    240         if not self.asynchronous:
    241             self._loop_runner.start()
--> 242             self.sync(self._start)
    243             self.sync(self._correct_state)
    244 

~/miniconda3/envs/ucx/lib/python3.7/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    160             return future
    161         else:
--> 162             return sync(self.loop, func, *args, **kwargs)
    163 
    164     async def _logs(self, scheduler=True, workers=True):

~/miniconda3/envs/ucx/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332     if error[0]:
    333         typ, exc, tb = error[0]
--> 334         raise exc.with_traceback(tb)
    335     else:
    336         return result[0]

~/miniconda3/envs/ucx/lib/python3.7/site-packages/distributed/utils.py in f()
    316             if callback_timeout is not None:
    317                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 318             result[0] = yield future
    319         except Exception as exc:
    320             error[0] = sys.exc_info()

~/miniconda3/envs/ucx/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/envs/ucx/lib/python3.7/site-packages/distributed/deploy/spec.py in _start(self)
    266 
    267         self.status = "starting"
--> 268         self.scheduler = await self.scheduler
    269         self.scheduler_comm = rpc(
    270             getattr(self.scheduler, "external_address", None) or self.scheduler.address,

~/miniconda3/envs/ucx/lib/python3.7/site-packages/distributed/deploy/spec.py in _()
     39             async with self.lock:
     40                 if self.status == "created":
---> 41                     await self.start()
     42                     assert self.status == "running"
     43             return self

~/miniconda3/envs/ucx/lib/python3.7/site-packages/dask_cuda-0.11.0b0-py3.7.egg/dask_cuda/scheduler.py in start(self)
     98             return
     99 
--> 100         msg = await self._wait_until_started()
    101         if not msg:
    102             return self.status

~/miniconda3/envs/ucx/lib/python3.7/site-packages/dask_cuda-0.11.0b0-py3.7.egg/dask_cuda/scheduler.py in _wait_until_started(self)
     58                 )
     59                 await self.process.join()
---> 60                 raise msg
     61             else:
     62                 return msg

TypeError: exceptions must derive from BaseException
```
</details>

#### Additional Questions:

If I start my cluster +workers as shown in comment https://github.com/rapidsai/ucx-py/issues/290#issuecomment-547423998, I am able to run my tasks successfully but am not getting any transfer time improvements in my dask-cudf workflow which is essentially a `set_index` on a large table. 

Is there a script i can run to check if the cluster is doing the transfers using the correct protocol ?

#### How I am starting the cluster + workers
```
 scheduler
UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,sockcm,cuda_copy,cuda_ipc UCX_SOCKADDR_TLS_PRIORITY=sockcm python -m distributed.cli.dask_scheduler --interface enp1s0f0 --protocol ucx

# workers
UCX_TLS=tcp,sockcm,cuda_copy,cuda_ipc UCX_SOCKADDR_TLS_PRIORITY=sockcm dask-cuda-worker ucx://10.33.227.163:8786

# client
#### I set below manually as well as in the first cell of my notebook

%env UCX_TLS=sockcm,cuda_copy,cuda_ipc
%env UCX_SOCKADDR_TLS_PRIORITY=sockcm
```

**Comment by pentschev** [comment]
This is actually due to https://github.com/rapidsai/dask-cuda/issues/164 which is being worked by @madsbk in https://github.com/rapidsai/dask-cuda/pull/168. Is that a big blocker to you or could you wait a few more days until the proper fix lands?

**Comment by VibhuJawa** [comment]
> This is actually due to [rapidsai/dask-cuda#164](https://github.com/rapidsai/dask-cuda/issues/164) which is being worked by @madsbk in [rapidsai/dask-cuda#168](https://github.com/rapidsai/dask-cuda/pull/168). Is that a big blocker to you or could you wait a few more days until the proper fix lands?

I dont think it should be a blocker if the  works with the dask-cli and the commands mentioned above are correct. 

Follow up question:

I was not seeing any speed up though when i started cluster that ways . Is  there a test script i can run to ensure the setup is correct  ?

**Comment by pentschev** [comment]
> I was not seeing any speed up though when i started cluster that ways . Is there a test script i can run to ensure the setup is correct ?

From your script, I'm assuming you had TCP and InfiniBand turned on, is that right? With InfiniBand I've seen some speedups, but it largely depends on the problem at hand, is there a lot of memory transfer when you look at the Dask taskstream? If not you're likely not to see any speedups. I think the best speedups I've seen so far are using NVLink, but I highly recommend checking the taskstream and perhaps trying some code that is largely dependent on memory transfer, which I've found hard to come across, even cuDF joins that I expected to see large amounts of memory transfer seems not to be the case when looking at the Dask taskstream.

**Comment by mrocklin** [comment]
People may also be interested in the dashboard plot available at
/individual-bandwidth-workers

**Comment by VibhuJawa** [comment]
> I'm assuming you had TCP and InfiniBand turned on, is that right?

Yes, I believe to be so as i was just following below:
```
UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,sockcm,cuda_copy,cuda_ipc UCX_SOCKADDR_TLS_PRIORITY=sockcm
``` 

@pentschev , The script i was doing this on is essentially just a `set-index` call on a big table with multiple partitions which is memory bound . 

I should have been more clearer about what i mean by speed up. The time for transfer is not seeing any  change.  Essentially on the task graph, i was looking at how much each individual transfer was taking and did not see a speed up there), which lead me to believe my setup may be incorrect. 

Will link the gist +profile+task-graph on our slack channel on our chat as its private currently.

**Comment by pentschev** [comment]
I believe all issues have been solved and questions answered. I'm tentatively closing this, feel free to reopen if needed @VibhuJawa .
