### ISSUE TITLE
CUDA IPC Performance of UCX

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#334]
I am investigating the performance shortcomings of dask/cuda. This is what I got so far.

Measuring the communication bandwidth between GPU device 1 and 2 on a DGX-1 machine (`dgx15`) using https://github.com/rapidsai/ucx-py/pull/331, I get:
```
$ python local-send-recv.py  -n "100MB" --server-dev 1 --client-dev 2  --n-iter 5 --object_type=cupy --reuse-alloc
Roundtrip benchmark
--------------------------
n_iter      | 5
n_bytes     | 100.00 MB
object      | cupy
reuse alloc | True
==========================
Device(s)   | 1, 2
Average     | 25.31 GB/s
--------------------------
Iterations
--------------------------
000         |  9.68 GB/s
001         | 42.73 GB/s
002         | 40.62 GB/s
003         | 43.46 GB/s
004         | 43.09 GB/s
```
The theoretical bandwidth is 50GB/s (two NVLINK2) so 40-43GB/s is good when considering the Python overhead. However, the first iteration is significantly slower at only 9.68 GB/s.

If we run the same benchmark without `--reuse-alloc`, we get consistent low bandwidth:
```
$ python local-send-recv.py  -n "100MB" --server-dev 1 --client-dev 2  --n-iter 5 --object_type=cupy
Roundtrip benchmark
--------------------------
n_iter      | 5
n_bytes     | 100.00 MB
object      | cupy
reuse alloc | False
==========================
Device(s)   | 1, 2
Average     | 9.92 GB/s
--------------------------
Iterations
--------------------------
000         |  9.53 GB/s
001         |  8.90 GB/s
002         | 10.36 GB/s
003         | 10.51 GB/s
004         | 10.50 GB/s
```
This tells me that the overhead associated with the first use of a memory allocation limits the performance drastically and is one of the reason why dask/cuda is not performing.

If we run using the CUDA profiler, **without** memory allocation reuse:
```
$ nvprof --profile-from-start off --profile-child-processes python local-send-recv.py  -n "100MB" --server-dev 1 --client-dev 2  --n-iter 100  --cuda-profile  --object_type=cupy
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  206.35ms       100  2.0635ms  2.0629ms  2.0659ms  [CUDA memcpy PtoP]
      API calls:   82.76%  832.96ms    260808  3.1930us     672ns  694.17us  cuStreamAddCallback
                   15.31%  154.05ms       100  1.5405ms  1.1657ms  3.0899ms  cuIpcOpenMemHandle
```
And **with** memory allocation reuse:
```
$ nvprof --profile-from-start off --profile-child-processes python local-send-recv.py  -n "100MB" --server-dev 1 --client-dev 2  --n-iter 100  --cuda-profile  --object_type=cupy --reuse-alloc
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  206.30ms       100  2.0630ms  2.0625ms  2.0702ms  [CUDA memcpy PtoP]
      API calls:   91.86%  229.12ms     88976  2.5750us     651ns  640.76us  cuStreamAddCallback
                    0.51%  1.2689ms         1  1.2689ms  1.2689ms  1.2689ms  cuIpcOpenMemHandle
```
Notice, how many more calls to `cuStreamAddCallback` and `cuIpcOpenMemHandle` there is when not reusing memory allocations. The actual communication time, `[CUDA memcpy PtoP]`, is the same.

I still haven't figured out if this is something that can be fixed in UCX or if we need to apply some kind of a UCX-friendly-allocation-reuse strategy in dask/cuda. I don't think we can do much in ucxpy since ucxpy doesn't allocate any arrays.

Thoughts are very much welcome :)

cc @quasiben @pentschev @Akshay-Venkatesh

**Comment by quasiben** [comment]
Would using cupy's memory pool be helpful here ?

**Comment by Akshay-Venkatesh** [comment]
IpcOpenMemhandle is a known expensive operation and this is the motivation behind CUDA_IPC cache. When you don't reuse allocation, you end up paying the price for opening memhandle each time and you see an expected degradation. The suggestion that had from early days of ucx-py development was to use persistent communication buffers (for both IB and CUDA-IPC case to avoid registration or memory mapping cost). At some point there was discussion that using rmm would avoid this problem but I don't know where that development stands. So yes, UCX-friendly-allocation will win back performance.

The other alternative that I brought up in the last UCX bi-weekly was that we need to move to a pipelined protocol in UCX from a zero-copy protocol that is currently available. This solves both the memory shortage issue that @pentschev brought up and also remove the cost of opening memhandle. This is slated for early next year after 1.8 release.

**Comment by madsbk** [comment]
@Akshay-Venkatesh, thanks for the explanation. 

Implementing persistent communication buffers or making rmm UCX aware makes sense even with `UCX_CUDA_IPC_CACHE=n`. 

With allocation reuse and `UCX_CUDA_IPC_CACHE=n`, I get half the performance: 23GB/s, which is still better than the 10.36 GB/s I get when not reusing allocations.

**Comment by Akshay-Venkatesh** [comment]
> With allocation reuse and `UCX_CUDA_IPC_CACHE=n`, I get half the performance: 23GB/s, which is still better than the 10.36 GB/s I get when not reusing allocations.

I can't explain this. Can you share the nvprof results for this?

**Comment by madsbk** [comment]
Sure:
**With** reuse but `UCX_CUDA_IPC_CACHE=n` (23GB/s):
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  206.31ms       100  2.0631ms  2.0629ms  2.0635ms  [CUDA memcpy PtoP]
      API calls:   62.44%  333.69ms    124768  2.6740us     660ns  547.25us  cuStreamAddCallback
                   24.91%  133.12ms       100  1.3312ms  1.2802ms  1.5717ms  cuIpcOpenMemHandle
                    9.40%  50.244ms       100  502.44us  462.97us  641.49us  cuIpcCloseMemHandle

```
**With** reuse and `UCX_CUDA_IPC_CACHE=y` (42.87 GB/s):
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  206.30ms       100  2.0630ms  2.0626ms  2.0638ms  [CUDA memcpy PtoP]
      API calls:   92.33%  231.99ms     87656  2.6460us     744ns  551.14us  cuStreamAddCallback
                    5.98%  15.014ms     22235     675ns     376ns  26.794us  cuEventQuery
                    0.55%  1.3720ms       100  13.719us  12.502us  45.064us  cuMemcpyDtoDAsync
                    0.53%  1.3350ms         1  1.3350ms  1.3350ms  1.3350ms  cuIpcOpenMemHandle
                    0.16%  400.11us       200  2.0000us  1.7270us  5.0120us  cuPointerGetAttributes
                    0.13%  327.60us       200  1.6380us  1.1730us  17.872us  cuIpcGetMemHandle

```

**Comment by Akshay-Venkatesh** [comment]
Looking at the 9.92 GB/s vs 23 GB/s, StreamAddCallback seems to be the difference. 
```
$ nvprof --profile-from-start off --profile-child-processes python local-send-recv.py  -n "100MB" --server-dev 1 --client-dev 2  --n-iter 100  --cuda-profile  --object_type=cupy
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  206.35ms       100  2.0635ms  2.0629ms  2.0659ms  [CUDA memcpy PtoP]
      API calls:   82.76%  832.96ms    260808  3.1930us     672ns  694.17us  cuStreamAddCallback
                   15.31%  154.05ms       100  1.5405ms  1.1657ms  3.0899ms  cuIpcOpenMemHandle
```
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  206.31ms       100  2.0631ms  2.0629ms  2.0635ms  [CUDA memcpy PtoP]
      API calls:   62.44%  333.69ms    124768  2.6740us     660ns  547.25us  cuStreamAddCallback
                   24.91%  133.12ms       100  1.3312ms  1.2802ms  1.5717ms  cuIpcOpenMemHandle
                    9.40%  50.244ms       100  502.44us  462.97us  641.49us  cuIpcCloseMemHandle
```
This is a surprising result and I'll create an issue for this in UCX if I can repro the problem. Disabling the ipc_cache to get better perf doesn't make sense especially when you're using a different buffer each time.

**Comment by madsbk** [comment]
Just to be clear, the 23 GB/s result **does** reuse the buffer but have `UCX_CUDA_IPC_CACHE=n` whereas the 9.92 GB/s result use a different buffer each time.

**Comment by Akshay-Venkatesh** [comment]
Sorry. What I meant to say is say is that (UCX_CUDA_IPC_CACHE=n + buffer-reuse) should have equivalent performance as (UCX_CUDA_IPC_CACHE=y + no-buffer-reuse) because both incur the same costs as far as IpcOpenMemhandle and CUDA Memcpy operations are concerned. The additional time spent in StreamAddCallback isn't explained. 

On that note, I've not aware of how things work in ucx-py now but I thought blocking progress (WAKEUP) was not requested during UCP init. Is that that not the case? Do ucxpy still rely on UCP_WAKEUP? If not, StreamAddCallback shouldn't be called. Stream callback serves to notify worker file descriptor which in turn serves UCP_WAKEUP feature.

**Comment by Akshay-Venkatesh** [comment]
Nevermind, I see that enabling blocking mode is optional - https://github.com/rapidsai/ucx-py/blob/branch-0.10/ucp/public_api.py#L74
Do you use a thread to progress communication and notify coroutines if blocking mode is disabled?

**Comment by madsbk** [comment]
Not a thread, for now is it only a coroutine: https://github.com/rapidsai/ucx-py/blob/branch-0.10/ucp/_libs/core.pyx#L270

**Comment by jakirkham** [comment]
> Would using cupy's memory pool be helpful here ?

Would like to underline this point. Not specifically about CuPy's memory pool, but using a memory pool in general. After all `cudaMalloc` itself is really slow.

The second point that seems worth making is today `rmm.device_array` is slow. ( https://github.com/rapidsai/rmm/issues/180 ) This is worth noting as [this is what `distributed` is using today]( https://github.com/dask/distributed/blob/43b2ed77218861c34dd2c98d88ec5153bd35f5c4/distributed/comm/ucx.py#L49 ).

These are both allocation problems that are slow. Certainly reusing the buffer is one solution, but as Ben points out more efficient allocations are also a solution.

**Comment by kkraus14** [comment]
@madsbk @quasiben It would be worth using rmm in pool allocation mode if possible for this benchmarking. This makes it so there's one large allocation upfront and makes future allocations much, much cheaper, similar to reusing the allocations like you're seeing above.

Additionally, as @jakirkham pointed out `rmm.device_array` is really expensive due to Numba control flow code, where using `rmm.DeviceBuffer` will be much, much faster.
