### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#335]
As PR ( https://github.com/rapidsai/ucx-py/pull/332 ) is now merged, would propose that we make a new release and publish new packages to conda-forge. Thoughts?

cc @quasiben

**Comment by quasiben** [comment]
👍 
Folks wanting to engage in benchmark and workflows will appreciate having an easy install experience

**Comment by jakirkham** [comment]
@pentschev @madsbk, any thoughts?

**Comment by pentschev** [comment]
Sounds good to me to simplify their workflows, but it is anyway possible without that if they set the environment variable themselves, which already happens.

**Comment by quasiben** [comment]
> Sounds good to me to simplify their workflows, but it is anyway possible without that if they set the environment variable themselves, which already happens.

@pentschev, correct and they are doing this now but would like to move away from it

**Comment by madsbk** [comment]
Fine with me

**Comment by pentschev** [comment]
> @pentschev, correct and they are doing this now but would like to move away from it

Just to be clear, I'm fine with a release, I was only pointing out that even the current release is usable.

**Comment by pentschev** [comment]
@jakirkham actually it would be nice to have nightlies, forgive my ignorance, but what is missing today for that?

**Comment by jakirkham** [comment]
Thanks all. 🙂 Let's ship it! :shipit:

Have tagged [0.3]( https://github.com/rapidsai/ucx-py/releases/tag/0.3 ) and added PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/44 ) to build the packages. Let's continue the conversation over there. In particular would like to make sure we have captured any OpenUCX patches we need.

**Comment by jakirkham** [comment]
These have since been released. Thanks all! 🙂
