### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#337]
When do we want to start testing on Python 3.8? Also when (though I'm guessing the answer will be the same) do we want to start building packages for Python 3.8?

**Comment by pentschev** [comment]
Do we already have plans for a RAPIDS release with Python 3.8? I would rather not do it until we get closer to that as we still have many open issues that are probably more important to focus on before.

**Comment by pentschev** [comment]
We test and have packages for 3.8 for some time already, closing.
