### ISSUE TITLE
compile error :  fatal error: ucp/api/ucp.h: No such file or directory

### ISSUE THREAD

**Issue by songqiqqq** [rapidsai/ucx-py#338]
```
$ python setup.py build_ext --inplace                                                                                                     
running build_ext
skipping 'ucp/_libs/utils.c' Cython extension (up-to-date)
building 'ucp._libs.utils' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/qsong/anaconda3/include -I/home/qsong/anaconda3/include/python3.5m -c ucp/_libs/utils.c -o build/temp.linux-x86_64-3.5/ucp/_libs/utils.o -std=c99
In file included from ucp/_libs/utils.c:603:0:
ucp/_libs/src/c_util.h:8:25: fatal error: ucp/api/ucp.h: No such file or directory
 #include <ucp/api/ucp.h>
                         ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

when installing ucx-py, I ran into the compile error above. ucx-py version is ucx-py-branch-0.10

**Comment by pentschev** [comment]
Could you check if you have Cython installed?

**Comment by songqiqqq** [comment]
I think I have installed Cython. Actually, I often use it .

**Comment by pentschev** [comment]
Ah right. Sorry, my mistake. I now realize that the header it's looking for is from OpenUCX, that means it can't find that. We normally install it from source when building ucx-py from source as well.

**Comment by songqiqqq** [comment]
got your idea. However I have installed OpenUCX before installing ucx-py. Besides, I could find the missing file at OpenUCX folder as below:
```
$ pwd
/scratch/qsong/mylib/ucx-1.6.1/src/ucp/api
$ ls
ucp_compat.h  ucp_def.h  ucp.h  ucp_version.h  ucp_version.h.in  ucpx.h
```
However, It seems that the ucx-py could not see it. What should I do?

**Comment by madsbk** [comment]
Try to set include dir like:
```
python setup.py build_ext --inplace --include-dirs=/scratch/qsong/mylib/ucx-1.6.1/src/
```

**Comment by quasiben** [comment]
I also noticed you are using 1.6.  We are currently building against UCX 1.7 can you also switch to that branch ?

**Comment by songqiqqq** [comment]
@madsbk your suggestions are great and that error is removed.  
However, another new error shows up:
```
[qsong@scorp2 ucx-py-branch-0.10]$ python setup.py build_ext --inplace
running build_ext
skipping 'ucp/_libs/utils.c' Cython extension (up-to-date)
building 'ucp._libs.utils' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/qsong/anaconda3/include -I/scratch/qsong/mylib/ucx-1.6.1/src -I/home/qsong/anaconda3/include/python3.5m -c ucp/_libs/utils.c -o build/temp.linux-x86_64-3.5/ucp/_libs/utils.o -std=c99
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/qsong/anaconda3/include -I/scratch/qsong/mylib/ucx-1.6.1/src -I/home/qsong/anaconda3/include/python3.5m -c ucp/_libs/src/c_util.c -o build/temp.linux-x86_64-3.5/ucp/_libs/src/c_util.o -std=c99
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/ucp
creating build/lib.linux-x86_64-3.5/ucp/_libs
gcc -pthread -shared -L/home/qsong/anaconda3/lib -Wl,-rpath=/home/qsong/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/ucp/_libs/utils.o build/temp.linux-x86_64-3.5/ucp/_libs/src/c_util.o -L/home/qsong/anaconda3/lib -L/home/qsong/anaconda3/lib -lucp -luct -lucm -lucs -lpython3.5m -o build/lib.linux-x86_64-3.5/ucp/_libs/utils.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lucp
/usr/bin/ld: cannot find -luct
/usr/bin/ld: cannot find -lucm
/usr/bin/ld: cannot find -lucs
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```
It seems some key files are missing.

 @quasiben Thanks for your remind, I would try that.

**Comment by quasiben** [comment]
@songqiqqq in the above post did you switch to 1.7 ?

Also, are you aware there are conda packages for ucx/ucx-py ?

https://ucx-py.readthedocs.io/en/latest/install.html#conda

**Comment by songqiqqq** [comment]
@quasiben 
(1) have not switch to 1.7 and I would do it next step 
(2) I know conda install is always easy but I have no internet at HPC server side  and not familiar with conda,  so I use pip install as my first try.  Next step, I would consider conda as you suggested.

Thanks for the help from all of you, I have to go now. Talk to you latter.

**Comment by madsbk** [comment]
You also need to set `--library-dirs` to the path of `libucp.so`. The path should be UCX install path + `/lib` or `/lib64`
```
python setup.py build_ext --inplace --include-dirs=/scratch/qsong/mylib/ucx-1.6.1/src/ --library-dirs=<path to ucx install path>/lib
```

**Comment by songqiqqq** [comment]
@madsbk you are amazing !  With your instruction, the error  is removed and the ucx-py is successfully installed.
