### ISSUE TITLE
Generate PR for UCX 1.7 patches

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#340]
With https://github.com/openucx/ucx/pull/4476 merged in I believe now is an appropriate time to create a PR of patches ucx-py required for ucx 1.7.  I believe we only need the following three PRs

- https://github.com/openucx/ucx/pull/4476
- https://github.com/openucx/ucx/pull/4137
- https://github.com/openucx/ucx/pull/4366

**Comment by quasiben** [comment]
Looks like @pentschev is already on this:
https://github.com/openucx/ucx/pull/4515

**Comment by pentschev** [comment]
Yeah, we should probably wait and then go back to generating packages from the v1.7.x branch. I believe it will be merged still this week.

**Comment by quasiben** [comment]
Agreed.  I'm testing out the branch now (double checking everything is ok)

**Comment by pentschev** [comment]
Cool, ping me if you find any issues.

**Comment by quasiben** [comment]
Tests pass for me!

**Comment by pentschev** [comment]
Awesome, we should have RC2 in a couple of days, that will be a nice time to have a new package!

**Comment by quasiben** [comment]
cc @jakirkham for awareness

**Comment by quasiben** [comment]
@pentschev did this and the PR is merged in: 
https://github.com/openucx/ucx/pull/4515

**Comment by jakirkham** [comment]
Also new packages were built with this patch.
