### ISSUE TITLE
Update doc environment file to use rapidsai channel

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#349]
Would be good to update [the doc environment file]( https://github.com/rapidsai/ucx-py/blob/486852efbf42b2004f42dc40d07f583301e38db9/conda/environments/builddocs_py37.yml#L3 ) to use the `rapidsai` channel once things are more finalized.

**Comment by quasiben** [comment]
Agreed.  For the time being I have been using my channel:
https://github.com/quasiben/ucx-py/blob/fix-rtd/conda/environments/builddocs_py37.yml#L3

this was done to over come the `libnuma.so.1` issue with UCX

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/rapidsai/ucx-py/pull/393 ) to update the channel ordering.
