### ISSUE TITLE
Use pytest.importorskip

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#352]
As we have a few optional test dependencies, it would be good to use `pytest.importorskip` to import and run those tests only when the dependency is available. We do handle this to some extent, but it's a bit inconsistent ATM. Would be good to tidy this up a bit.

**Comment by pentschev** [comment]
I've recently done some of that in https://github.com/rapidsai/ucx-py/pull/764. I'm unaware of any optional dependencies that do not skip when not installed. I'm closing, but please reopen should anything still be missing.
