### ISSUE TITLE
Fail to initialize ucx-py

### ISSUE THREAD

**Issue by songqiqqq** [rapidsai/ucx-py#361]
I installed ucx(1.7)/ucx-py(0.4) with conda. However, when running the test code as below, error is encountered. I looked up this issus at many places, however little instruction could be found. It would be appreciated for any suggestion !

```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ucp
>>> options = {"MEMTYPE_CACHE": "n"}
>>> ucp.init(options)
[1575739742.264943] [scorp2:4022 :0]    ucp_context.c:671  UCX  WARN  transport 'cuda_copy' is not available, please use one or more of: ib, mm, posix, rc, rc_v, self, shm, sm, sysv, tcp, ud, ud_v
[1575739742.286539] [scorp2:4022 :0]       ib_iface.c:618  UCX  ERROR ibv_create_cq(cqe=4096) failed: Cannot allocate memory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/qsong/conda-env/py37_qsong/lib/python3.7/site-packages/ucp/public_api.py", line 74, in init
    options, blocking_progress_mode=blocking_progress_mode
  File "ucp/_libs/core.pyx", line 363, in ucp._libs.core.ApplicationContext.__cinit__
  File "ucp/_libs/core.pyx", line 30, in ucp._libs.core.assert_ucs_status
ucp.exceptions.UCXError: Input/output error
>>> ucp.__version__
'0.4'
```

**Comment by quasiben** [comment]
The `ibv_create_cq` line perhaps indiccates that `nv_peer_mem` is not loaded ?  Can you check:
>  lsmod | grep nv_peer_mem

```
(base) bzaitlen@dgx15:~$ lsmod | grep nv_peer_mem
nv_peer_mem            16384  0
ib_core               266240  12 rdma_cm,ib_ipoib,mlx4_ib,nv_peer_mem,iw_cm,ib_iser,ib_umad,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm,ib_ucm
nvidia              18194432  3975 nvidia_uvm,nv_peer_mem,nvidia_modeset
```

**Comment by quasiben** [comment]
Could you also show the output of:
> ucx_info -b | grep uct

```
(cudf_dev10.1) bzaitlen@dgx15:~$ ucx_info -b | grep uct
#define uct_MODULES               ":cuda:ib:rdmacm:cma"
#define uct_cuda_MODULES          ""
#define uct_ib_MODULES            ":cm"
#define uct_rocm_MODULES          ""
```

**Comment by songqiqqq** [comment]
Hi, @quasiben . It seems you hit the point.  `lsmod | grep nv_peer_mem` shows nothing. What should i do in this case ?


```
(py37_qsong) [qsong@scorp2 qsong]$ lsmod | grep nv_peer_mem
(py37_qsong) [qsong@scorp2 qsong]$
```
```
(py37_qsong) [qsong@scorp2 qsong]$ ucx_info -b | grep uct
#define uct_MODULES               ":cuda:ib:rdmacm"
#define uct_cuda_MODULES          ""
#define uct_ib_MODULES            ":cm"
#define uct_rocm_MODULES          ""

```

```
(py37_qsong) [qsong@scorp2 qsong]$ lsmod
Module                  Size  Used by
rpcsec_gss_krb5        36864  0 
nfsv4                 643072  0 
dns_resolver           16384  1 nfsv4
beegfs                507904  1 
nfsv3                  49152  7 
nfs                   303104  10 nfsv4,nfsv3
fscache                73728  2 nfsv4,nfs
ib_isert               53248  0 
iscsi_target_mod      339968  1 ib_isert
ib_srpt                49152  0 
target_core_mod       397312  3 iscsi_target_mod,ib_srpt,ib_isert
ib_srp                 57344  0 
scsi_transport_srp     20480  1 ib_srp
rpcrdma               106496  9 
rdma_ucm               32768  2 
ib_uverbs              98304  49 rdma_ucm
ib_iser                53248  0 
ib_umad                28672  4 
rdma_cm                65536  5 beegfs,rpcrdma,ib_iser,ib_isert,rdma_ucm
ib_ipoib              135168  0 
iw_cm                  53248  1 rdma_cm
libiscsi               61440  1 ib_iser
scsi_transport_iscsi   110592  2 ib_iser,libiscsi
ib_cm                  53248  4 rdma_cm,ib_ipoib,ib_srpt,ib_srp
mlx5_ib               212992  0 
ib_core               262144  14 beegfs,rdma_cm,ib_ipoib,rpcrdma,ib_srpt,ib_srp,iw_cm,ib_iser,ib_umad,ib_isert,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm
vfat                   20480  1 
fat                    73728  1 vfat
xfs                  1400832  1 
intel_rapl             24576  0 
libcrc32c              16384  1 xfs
x86_pkg_temp_thermal    16384  0 
intel_powerclamp       16384  0 
coretemp               16384  0 
kvm_intel             233472  0 
ipmi_ssif              28672  0 
kvm                   700416  1 kvm_intel
iTCO_wdt               16384  0 
iTCO_vendor_support    16384  1 iTCO_wdt
dcdbas                 16384  0 
irqbypass              16384  1 kvm
crct10dif_pclmul       16384  0 
crc32_pclmul           16384  0 
ghash_clmulni_intel    16384  0 
intel_cstate           16384  0 
ipmi_si                65536  0 
intel_uncore          131072  0 
mei_me                 45056  0 
ipmi_devintf           20480  0 
joydev                 24576  0 
intel_rapl_perf        16384  0 
ipmi_msghandler        49152  3 ipmi_devintf,ipmi_si,ipmi_ssif
i2c_i801               28672  0 
shpchp                 40960  0 
mei                   118784  1 mei_me
lpc_ich                28672  0 
acpi_power_meter       20480  0 
nfsd                  401408  13 
auth_rpcgss            73728  2 nfsd,rpcsec_gss_krb5
nfs_acl                16384  2 nfsd,nfsv3
lockd                 106496  3 nfsd,nfsv3,nfs
grace                  16384  2 nfsd,lockd
sunrpc                397312  59 nfsd,rpcrdma,nfsv4,auth_rpcgss,lockd,nfsv3,rpcsec_gss_krb5,nfs_acl,nfs
mgag200                53248  1 
i2c_algo_bit           16384  1 mgag200
mlx5_core             552960  1 mlx5_ib
drm_kms_helper        192512  1 mgag200
crc32c_intel           24576  5 
ttm                   114688  1 mgag200
bnxt_en               176128  0 
drm                   438272  4 drm_kms_helper,mgag200,ttm
mlxfw                  24576  1 mlx5_core
tg3                   188416  0 
megaraid_sas          163840  5 
devlink                49152  2 bnxt_en,mlx5_core
ptp                    20480  2 tg3,mlx5_core
pps_core               20480  1 ptp

```

**Comment by songqiqqq** [comment]
It seems that I need to install nv_peer_memory(https://github.com/Mellanox/nv_peer_memory), which is used in GPU-GPU communication.  However, there is no GPU-related computation in my code, is there any easier method/configration to walk around this issue ?

**Comment by quasiben** [comment]
If you aren't doing any GPU transfers you could something like the following:

> UCX_TLS=tcp,sockcm UCX_SOCKADDR_TLS_PRIORITY=sockcm

or

```python
options = {"MEMTYPE_CACHE": "n", 'TLS': 'tcp,sockcm', 'SOCKADDR_TLS_PRIORITY': 'sockcm'}
```

The above would only use TCP -- no IB nor NVLINK.  It should also be noted that ucx-py team has observed TCP performing _worse_ than TCP through Python.  

Can I ask what the larger goal you are trying to accomplish ?  Dask-jobqueue with InfiniBand ?

**Comment by songqiqqq** [comment]
@quasiben Thanks for you valuable comment. 

My own project is based on dask/distributed(jobqueue is not essential) and there is lots of heavy data to be transfered between diffent nodes/processes(using tcp according to my understanding with dask/distributed), which is also the main bottlenect for my computation.  Therefore, I just want to speed it up. 

As mentiones in the office document of dask,  [For high performance networks you can use either TCP-over-Infiniband for about 1 GB/s bandwidth, or UCX (experimental) for full speed communication.](https://docs.dask.org/en/latest/institutional-faq.html#id12).  So,  I thought ucx could provide a great speed improvement for data transfer. (Actually I have little knowledge for the mechanism of ucx and do not know whether my plan is promising).

**Comment by songqiqqq** [comment]
@quasiben As you pointed out, It's really no faster only use tcp.   It's really a pity !

**Comment by quasiben** [comment]
@songqiqqq do your machines have infiniband devies?  If so you will need to add `rc` to the `TLS`.

The isolated TCP issue is disappointing .  I believe the issue lies with UCX core but we don't have a reproducible example yet nor a issue filed.  We've been mostly focused on reliably using the optimized hardware routes: NVLINK and IB

@pentschev is there anything you want add here ?

**Comment by songqiqqq** [comment]
@quasiben yes, machines here is equipped with IB. 
Adding `rc` to `TLS` also require me to install nv_peer_memory((https://github.com/Mellanox/nv_peer_memory))? If not , the same ibv_create_cq error is raised here.

**Comment by songqiqqq** [comment]
@quasiben  a update:
`export LD_LIBRARY_PATH=/scratch/qsong/conda-env/py37_qsong/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`
with the statement above inserted into the .bashrc file, that error disappeared, but it seems the rc transport can not be used. 

```
>>> import ucp
>>> options = {"MEMTYPE_CACHE": "n"}
>>> ucp.init(options)
[1575860460.799710] [scorp2:40272:0]    ucp_context.c:671  UCX  WARN  transport 'rc' is not available, please use one or more of: mm, posix, self, shm, sm, sysv, tcp
[1575860460.827648] [scorp2:40272:0]         parser.c:1568 UCX  WARN  unused env variable: UCX_CUDA_IPC_CACHE (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
>>> assert ucp.get_config()['MEMTYPE_CACHE'] is 'n'
>>> 
```

additional info:
```
[qsong@scorp2 qsong]$ cd /scratch/qsong/conda-env/py37_qsong/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/
[qsong@scorp2 lib64]$ ls
libibverbs.so  libibverbs.so.1  libibverbs.so.1.0.0  librdmacm.so  rsocket
```

**Comment by pentschev** [comment]
For InfiniBand to work correctly you must ensure that you set `UCX_NET_DEVICES` to use the appropriate InfiniBand device in each process. For example, if you have two InfiniBand devices, they're probably called `mlx5_0:1`  and `mlx5_1:`, so each process must ensure it sets the device it wants to use. Perhaps one process will have `UCX_NET_DEVICES=mlx5_0:1` and another `UCX_NET_DEVICES=mlx5_1:1`. If you have a single InfiniBand device, you must set that nevertheless, otherwise you can't ensure UCX is indeed using the InfiniBand device rather than an Ethernet one.

If you don't have the libibcm packages from your distro installed, you may also need to install it from conda-forge:

```
conda install -c conda-forge libibcm-cos6-x86_64
```

Regarding the `nv_peer_memory` module, I'm not sure whether that's needed if you're not using CUDA, I would assume not, but I don't think we have any machines with InfiniBand that we also don't have `nv_peer_memory` installed where we can test that to confirm either. I have tested this on a machine without `nv_peer_memory` but also without InfiniBand interfaces and it doesn't error out.

@songqiqqq I also see that your `uct_MODULES` report `cuda`, which you don't have available, is that correct? It seems like you may have installed with `ucx-proc=*=gpu`. Could you try creating a new repository as shown below and see if you still see the `ibv_create_eq` issue?

```
conda create -n ucx-tmp -c conda-forge -c conda-forge/label/rc_ucx ucx-py ucx ucx-proc=*=cpu`
```

Could you also report the output of `ucx_info -b | grep uct` again with the new environment?

**Comment by songqiqqq** [comment]
hi, @pentschev . Thanks for your reply.
(1)  The internet is forbidden on the machine here. Therefore, I downloaded the tar.tz2 file and installed(use conda locally) that 3 packages  `ucx-py ucx ucx-proc=*=cpu` manually in a new conda environment. But 
1) the ibv_create_eq issue is still  there if the .bashrc file is unrevised (as the post above).
```
(ucx_tmp2) [qsong@scorp3 ~]$ conda list
# packages in environment at /scratch/qsong/conda-env/ucx_tmp2:
#
# Name                    Version                   Build  Channel
ucx                       1.6.1                h51cf6c1_4    file:///home/qsong/upload
ucx-proc                  1.0.0                       cpu    file:///home/qsong/upload
ucx-py                    0.4              py37h51cf6c1_3    <unknown>
(ucx_tmp2) [qsong@scorp3 ~]$ python
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ucp
>>> options = {"MEMTYPE_CACHE": "n"}
>>> ucp.init(options)
[1575904192.247749] [scorp3:147053:0]       ib_iface.c:618  UCX  ERROR ibv_create_cq(cqe=4096) failed: Cannot allocate memory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/qsong/conda-env/py37_qsong/lib/python3.7/site-packages/ucp/public_api.py", line 74, in init
    options, blocking_progress_mode=blocking_progress_mode
  File "ucp/_libs/core.pyx", line 363, in ucp._libs.core.ApplicationContext.__cinit__
  File "ucp/_libs/core.pyx", line 30, in ucp._libs.core.assert_ucs_status
ucp.exceptions.UCXError: Input/output error
>>> exit()
```
2) In this new env, we have:
```
(ucx_tmp2) [qsong@scorp3 ~]$ ucx_info -b | grep uct
#define uct_MODULES               ":cuda:ib:rdmacm"
#define uct_cuda_MODULES          ""
#define uct_ib_MODULES            ":cm"
#define uct_rocm_MODULES          ""
```
(2) I did not use GPU/Cuda. Therefore, I do not think the nv_peer_memory is needed.
(3) As my above post stated,  If  I insert `export LD_LIBRARY_PATH=/scratch/qsong/conda-env/py37_qsong/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}` into .bashrc file, the ibv_create_eq issue disappears.  I do not know the reason  but the file in that folder is listed here:
```
(ucx_tmp2) [qsong@scorp3 ~]$ ls /scratch/qsong/conda-env/py37_qsong/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64
libibcm.so  libibcm.so.1  libibcm.so.1.0.0  libibverbs.so  libibverbs.so.1  libibverbs.so.1.0.0  librdmacm.so  librdmacm.so.1  librdmacm.so.1.0.0  rsocket
```
(4) I am not sure whether (3) is a progress for my personal problem (that ibv_create_eq issue disappered !). I think the `rc` transport is actually what I need, which is related to IB communication.  But, I have no ideal why it told me  `ucp_context.c:671  UCX  WARN  transport 'rc' is not available`  as stated in the above comment: https://github.com/rapidsai/ucx-py/issues/361#issuecomment-563042735.

**Comment by jakirkham** [comment]
It looks like your version of `ucx` is too old. Would either get the package from `conda-forge/label/rc_ucx` or under `rapidsai-nightly`. Also would note we are moving towards having these packages in `rapidsai` and `rapidsai-nightly` going forward. Just haven't quite completed this transition yet.

**Comment by songqiqqq** [comment]
@jakirkham @quasiben  update the ucx could not eliminat the warinig: `ucp_context.c:671  UCX  WARN  transport 'rc' is not available, please use one or more of: mm, posix, self, shm, sm, sysv, tcp`

Could you kindly give me some guides about this warning?  It's related to lacking of module or  something else?  Why it can not use rc transport ?

Thanks!

**Comment by pentschev** [comment]
It still looks like you're not on the correct version of ucx/ucx-py. Make sure you install the following versions:

```
$ conda list | egrep "libib|ucx"
libibcm-cos6-x86_64       1.0.5                h1341992_0    conda-forge
libibverbs-cos6-x86_64    1.1.8                h1341992_0    conda-forge
ucx                       1.7.0rc1             ha5db111_3    conda-forge/label/rc_ucx
ucx-proc                  1.0.0                       cpu    conda-forge
ucx-py                    0.4              py37ha5db111_3    conda-forge/label/rc_ucx
```

Note also the build version (3rd column).

You mentioned earlier that you're setting `LD_LIBRARY_PATH`, you have to be careful not to point to a different conda environment directory, as you may in that case override the libraries and point to an older version that will not work correctly. I would suggest just creating a new conda environment with up-to-date packages and not setting `LD_LIBRARY_PATH` at all to prevent such issues. If the conda environment contains the proper packages, it should automatically find appropriate libraries.

**Comment by songqiqqq** [comment]
@pentschev  I have cleared the .bashrc file and created a new env with the same packages  as you show but the ibv_create_cq issue is still there. 

```
(ucx_tmp) [qsong@scorp3 ucx_tmp]$ ./bin/python3.7
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ucp
>>> options = {"MEMTYPE_CACHE": "n"}
>>> ucp.init(options)
[1575987475.505037] [scorp3:45206:0]       ib_iface.c:618  UCX  ERROR ibv_create_cq(cqe=4096) failed: Cannot allocate memory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/qsong/conda-env/py37_qsong/lib/python3.7/site-packages/ucp/public_api.py", line 74, in init
    options, blocking_progress_mode=blocking_progress_mode
  File "ucp/_libs/core.pyx", line 363, in ucp._libs.core.ApplicationContext.__cinit__
  File "ucp/_libs/core.pyx", line 30, in ucp._libs.core.assert_ucs_status
ucp.exceptions.UCXError: Input/output error
>>> exit()
(ucx_tmp) [qsong@scorp3 ucx_tmp]$ conda list
# packages in environment at /scratch/qsong/conda-env/ucx_tmp:
#
# Name                    Version                   Build  Channel
libibcm-cos6-x86_64       1.0.5                h1341992_0    file:///home/qsong/upload
libibverbs-cos6-x86_64    1.1.8                h1341992_0    file:///home/qsong/upload
python                    3.7.3                h5b0a415_0    file:///home/qsong/upload
ucx                       1.7.0rc1             ha5db111_3    file:///home/qsong/upload
ucx-proc                  1.0.0                       cpu    file:///home/qsong/upload
ucx-py                    0.4              py37ha5db111_3    file:///home/qsong/upload

```

**Comment by quasiben** [comment]
i think this is due to that conda package now having a critial build dependency which was recently added `libibcm` .  @songqiqqq we are getting cpu versions of ucx built with this fix on the rapidsai-nightly channel. i'll ping when this is done.  In the mean time can you check that `libibcm` and/or `libibcm-devel` is installed on the machine ? 

Thank you for baring with us while we work out these issus

**Comment by quasiben** [comment]
@songqiqqq, you already posted libibcm installed on the machine -- please disregard that comment

**Comment by quasiben** [comment]
@pentschev pointed out to me the conda package is entirely valid.

**Comment by quasiben** [comment]
@songqiqqq can you try the following:

```python
In [1]: import ucp                                                                                                                                                                    

In [2]: options = {"MEMTYPE_CACHE": "n", "TLS": "rc,tcp,sockcm", "SOCKADDR_TLS_PRIORITY": "sockcm"}                                                                                   

In [3]: ucp.init(options)     
```

**Comment by songqiqqq** [comment]
@quasiben do you mean the conda packages at rapidsai-nightly channel are updated ?  I can't find the proper version pentschev had listed at that channel.
Besides, following: 
```
In [1]: import ucp                                                                                                                                                                    

In [2]: options = {"MEMTYPE_CACHE": "n", "TLS": "rc,tcp,sockcm", "SOCKADDR_TLS_PRIORITY": "sockcm"}                                                                                   

In [3]: ucp.init(options)    
```
the  ibv_create_cq issue is still there

**Comment by songqiqqq** [comment]
I think I really need the rc transport in ucx and the tcp transport I am using now can not afford heavy data transfering between different nodes. 
Appreciate your help from heart.

**Comment by quasiben** [comment]
@songqiqqq can you also post the output of `ibv_devinfo -vvv` ?  I recall there being an issue once with IB where we say PORT_INACTIVE in the `ibv_devinfo` output

Another thing we could confirm is that the `ucx_perfest` works.  I believe the following should do that:

> UCX_NET_DEVICES=mlx5_0:1 UCX_TLS=rc ucx_perftest -t tag_bw -m host -s 10000000 -n 10 -p 9999 & UCX_NET_DEVICES=mlx5_0:1 UCX_TLS=rc ucx_perftest <HOSTNAME> -t tag_bw -m host -s 100000000 -n 10 -p 9999

If you run the above and monitor packets received:
> watch -d 'cat /sys/class/infiniband/mlx5_*/ports/1/counters/port_rcv_packets'

You should observe the values ticking up during the test

**Comment by songqiqqq** [comment]
Hi, @quasiben . Thanks for your guide. I test that two commands as below:
（1）
```
(ucx_tmp) [qsong@scorp2 myusim]$ ibv_devinfo -vvv
hca_id: mlx5_0
        transport:                      InfiniBand (0)
        fw_ver:                         16.23.1000
        node_guid:                      506b:4b03:00cc:f9e2
        sys_image_guid:                 506b:4b03:00cc:f9e2
        vendor_id:                      0x02c9
        vendor_part_id:                 4119
        hw_ver:                         0x0
        board_id:                       MT_0000000008
        phys_port_cnt:                  1
        max_mr_size:                    0xffffffffffffffff
        page_size_cap:                  0xfffffffffffff000
        max_qp:                         262144
        max_qp_wr:                      32768
        device_cap_flags:               0xe97e1c36
                                        BAD_PKEY_CNTR
                                        BAD_QKEY_CNTR
                                        AUTO_PATH_MIG
                                        CHANGE_PHY_PORT
                                        PORT_ACTIVE_EVENT
                                        SYS_IMAGE_GUID
                                        RC_RNR_NAK_GEN
                                        MEM_WINDOW
                                        UD_IP_CSUM
                                        XRC
                                        MEM_MGT_EXTENSIONS
                                        MEM_WINDOW_TYPE_2B
                                        MANAGED_FLOW_STEERING
                                        Unknown flags: 0xC8480000
        max_sge:                        30
        max_sge_rd:                     30
        max_cq:                         16777216
        max_cqe:                        4194303
        max_mr:                         16777216
        max_pd:                         16777216
        max_ee:                         0
        max_rdd:                        0
        max_mw:                         16777216
        max_raw_ipv6_qp:                0
        max_raw_ethy_qp:                0
        max_mcast_grp:                  2097152
        max_mcast_qp_attach:            240
        max_total_mcast_qp_attach:      503316480
        max_ah:                         2147483647
        max_fmr:                        0
        max_srq:                        8388608
        max_srq_wr:                     32767
        max_srq_sge:                    31
        max_pkeys:                      128
        local_ca_ack_delay:             16
        general_odp_caps:
                                        ODP_SUPPORT
                                        Unknown flags: 0x2
        rc_odp_caps:
                                        SUPPORT_SEND
                                        SUPPORT_RECV
                                        SUPPORT_WRITE
                                        SUPPORT_READ
        uc_odp_caps:
                                        NO SUPPORT
        ud_odp_caps:
                                        SUPPORT_SEND
        completion timestamp_mask:                      0x7fffffffffffffff
        hca_core_clock:                 78125kHZ
        device_cap_flags_ex:            0x1E97E1C36
                                        Unknown flags: 0x100000000
        tso_caps:
        max_tso:                        0
        rss_caps:
                max_rwq_indirection_tables:                     0
                max_rwq_indirection_table_size:                 0
                rx_hash_function:                               0x0
                rx_hash_fields_mask:                            0x0
        max_wq_type_rq:                 0
        packet_pacing_caps:
                qp_rate_limit_min:      0kbps
                qp_rate_limit_max:      0kbps
        max_rndv_hdr_size:              64
        max_num_tags:                   127
        max_ops:                        32768
        max_sge:                        1
        flags:
                                        IBV_TM_CAP_RC
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 1
                        port_lid:               3
                        port_lmc:               0x00
                        link_layer:             InfiniBand
                        max_msg_sz:             0x40000000
                        port_cap_flags:         0x2659e84a
                        port_cap_flags2:        0x0000
                        max_vl_num:             4 (3)
                        bad_pkey_cntr:          0x0
                        qkey_viol_cntr:         0x0
                        sm_sl:                  0
                        pkey_tbl_len:           128
                        gid_tbl_len:            8
                        subnet_timeout:         18
                        init_type_reply:        0
                        active_width:           4X (2)
                        active_speed:           25.0 Gbps (32)
                        phys_state:             LINK_UP (5)
                        GID[  0]:               fe80:0000:0000:0000:506b:4b03:00cc:f9e2

hca_id: mlx5_1
        transport:                      InfiniBand (0)
        fw_ver:                         16.23.1000
        node_guid:                      506b:4b03:00cc:f9e3
        sys_image_guid:                 506b:4b03:00cc:f9e2
        vendor_id:                      0x02c9
        vendor_part_id:                 4119
        hw_ver:                         0x0
        board_id:                       MT_0000000008
        phys_port_cnt:                  1
        max_mr_size:                    0xffffffffffffffff
        page_size_cap:                  0xfffffffffffff000
        max_qp:                         262144
        max_qp_wr:                      32768
        device_cap_flags:               0xe97e1c36
                                        BAD_PKEY_CNTR
                                        BAD_QKEY_CNTR
                                        AUTO_PATH_MIG
                                        CHANGE_PHY_PORT
                                        PORT_ACTIVE_EVENT
                                        SYS_IMAGE_GUID
                                        RC_RNR_NAK_GEN
                                        MEM_WINDOW
                                        UD_IP_CSUM
                                        XRC
                                        MEM_MGT_EXTENSIONS
                                        MEM_WINDOW_TYPE_2B
                                        MANAGED_FLOW_STEERING
                                        Unknown flags: 0xC8480000
        max_sge:                        30
        max_sge_rd:                     30
        max_cq:                         16777216
        max_cqe:                        4194303
        max_mr:                         16777216
        max_pd:                         16777216
        max_qp_rd_atom:                 16
        max_ee_rd_atom:                 0
        max_res_rd_atom:                4194304
        max_qp_init_rd_atom:            16
        max_ee_init_rd_atom:            0
        atomic_cap:                     ATOMIC_HCA (1)
        max_ee:                         0
        max_rdd:                        0
        max_mw:                         16777216
        max_raw_ipv6_qp:                0
        max_raw_ethy_qp:                0
        max_mcast_grp:                  2097152
        max_mcast_qp_attach:            240
        max_total_mcast_qp_attach:      503316480
        max_ah:                         2147483647
        max_fmr:                        0
        max_srq:                        8388608
        max_srq_wr:                     32767
        max_srq_sge:                    31
        max_pkeys:                      128
        local_ca_ack_delay:             16
        general_odp_caps:
                                        ODP_SUPPORT
                                        Unknown flags: 0x2
        rc_odp_caps:
                                        SUPPORT_SEND
                                        SUPPORT_RECV
                                        SUPPORT_WRITE
                                        SUPPORT_READ
        uc_odp_caps:
                                        NO SUPPORT
        ud_odp_caps:
                                        SUPPORT_SEND
        completion timestamp_mask:                      0x7fffffffffffffff
        hca_core_clock:                 78125kHZ
        device_cap_flags_ex:            0x1E97E1C36
                                        Unknown flags: 0x100000000
        tso_caps:
        max_tso:                        0
        rss_caps:
                max_rwq_indirection_tables:                     0
                max_rwq_indirection_table_size:                 0
                rx_hash_function:                               0x0
                rx_hash_fields_mask:                            0x0
        max_wq_type_rq:                 0
        packet_pacing_caps:
                qp_rate_limit_min:      0kbps
                qp_rate_limit_max:      0kbps
        max_rndv_hdr_size:              64
        max_num_tags:                   127
        max_ops:                        32768
        max_sge:                        1
        flags:
                                        IBV_TM_CAP_RC
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 1
                        port_lid:               9
                        port_lmc:               0x00
                        link_layer:             InfiniBand
                        max_msg_sz:             0x40000000
                        port_cap_flags:         0x2659e848
                        port_cap_flags2:        0x0000
                        max_vl_num:             4 (3)
                        bad_pkey_cntr:          0x0
                        qkey_viol_cntr:         0x0
                        sm_sl:                  0
                        pkey_tbl_len:           128
                        gid_tbl_len:            8
                        subnet_timeout:         18
                        init_type_reply:        0
                        active_width:           4X (2)
                        active_speed:           25.0 Gbps (32)
                        phys_state:             LINK_UP (5)
                        GID[  0]:               fe80:0000:0000:0000:506b:4b03:00cc:f9e3


```
（2）

```
(ucx_tmp) [qsong@scorp2 myusim]$ UCX_NET_DEVICES=mlx5_0:1 UCX_TLS=rc ucx_perftest -t tag_bw -m host -s 10000000 -n 10 -p 9999 & UCX_NET_DEVICES=mlx5_0:1 UCX_TLS=rc ucx_perftest -t tag_bw -m host -s 100000000 -n 10 -p 9999
[1] 15620
[1576116675.456492] [scorp2:15620:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 128 cpus). Performance may be impacted.
[1576116675.456503] [scorp2:15621:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 128 cpus). Performance may be impacted.
Waiting for connection...
[1576116675.456630] [scorp2:15620:0]       perftest.c:911  UCX  ERROR bind() failed: Address already in use
```
and then,  in another console:
```
Every 2.0s: cat /sys/class/infiniband/mlx5_*/ports/1/counters/port_rcv_packets                                                                                                                                                                           Thu Dec 12 10:13:08 2019

1216076820
5568826841

```
the two numbers in the last line keep changing

**Comment by songqiqqq** [comment]
I found a similar ibv_create_cq issue here: [Error initializing an UCX / OpenFabrics device](https://github.com/open-mpi/ompi/issues/6300)
I can't figure out how they solved this but it may be helpful to you.

**Comment by songqiqqq** [comment]
or it's related to[ this](https://developer.arm.com/tools-and-software/server-and-hpc/help/porting-and-tuning/building-open-mpi-with-openucx/running-openmpi-with-openucxl) ?

**Comment by songqiqqq** [comment]
@quasiben @pentschev @jakirkham It's solved ！！！！！！！

it's related to the max locked memory. If it's set to be unlimited, the ibv_create_eq issue disappears. I am wondering what's the proper value for our needs. Is it related to the data size to be transferring ?

**Comment by songqiqqq** [comment]
It seems there is no speedup for the data transfer.
(1)The configure for ucxpy is ： 
```
#.bashrc   file
export UCX_MEMTYPE_CACHE=n UCX_TLS=rc,tcp,sockcm UCX_SOCKADDR_TLS_PRIORITY=sockcm
export UCXPY_IFNAME="ib0"
```
(2) then , i start the scheduler with:`dask-scheduler --protocol ucx --interface ib0`
(3) then , i start the worker with ： `opt/anaconda37/bin/python3.7 -m distributed.cli.dask_worker ${scheduler_address} --nthreads 15 --nprocs 1 --memory-limit 400.00GB  --nanny --death-timeout 60 --local-directory /scratch/qsong --name com --interface ib0` at different nodes of the cluster, where $(scheduler_address) is` ucx:\\ ......` like address got from last step.  Besides,the ENV value at different nodes is ensured to be the same with step 1
(4) then, nt the main.py, i use: `client = Client('ucx://172.16.10.12:8786')` to start the calculation.

the data could be transfer from main.py to different nodes, but no speed-up could be observed. Any suggestion ?

**Comment by pentschev** [comment]
This is an interesting find about the `max locked memory`, this is related to a system configuration on your OS, and is most definitely not related to InfiniBand directly, but with the resources it requires. For reference, I checked some of our machines where we're testing InfiniBand, and they have it set to `unlimited`. That said, I would recommend using that, but to be honest, I'm not sure what are other possible consequences, perhaps someone set it to `64` on your machine for a reason, you should probably check if that's the case with other users/sysadmins there.

I have recently noticed on Dask three problems that affect performance with UCX:

1. Small chunk sizes, increasing them usually helps;
1. Communication really not being the bottleneck, which can normally be verified in the Dask's task stream. If there aren't many red parts, you probably won't see much difference with UCX;
1. Transfers seeming to take long periods of time, but in fact are waiting for other tasks to complete while still reporting them as take unreasonably long times (e.g., 1-2 minutes for 100MB transfers).

I'm not sure if we can help much further with Dask right now, as we're still trying to understand these issues ourselves. @quasiben I think you'll agree with this statement of mine here, but feel free to correct me if I'm wrong.

**Comment by songqiqqq** [comment]
I test the time consuming of data transfering as below:
```
time1= time()
client.scatter(data) # two workers total
time2 = time()
time_comsuming = time2 - time1
```
with data size of 100MB, it needs about 1.5s ~ 2s using ucx. This speed is almost the same as before(no ucx).

**Comment by quasiben** [comment]
I agree with what @pentschev has said.  To help gain a better understanding of transfers with dask I would recommend looking at the following plots during job:
- http://DASHBOARD-ADDR:8787/individual-bandwidth-types
- http://DASHBOARD-ADDR:8787/individual-bandwidth-workers

This will show bandwidth plots of types being passed (pandas series/dataframes or numpy arrays) and what the bandwidths are between workers. 

Also, when you are testing ucx+dask with client.scatter are you seeing packets increase at `...counters/port_rcv_packets` ?

**Comment by songqiqqq** [comment]
Hi, @quasiben 
(1) As to the benefit of dashbord, I agree with you. However, the pity is that communications between my local computer and port at cluster is blocked due to security considering. Therefore, I can't show the dashbord. I would try to talk this issue with the administrator if dashboard could provide valuable info. we need. 
(2) When client scattering, I could see packets increase.  Could this confirm the communication is through the ib network ? If So, why the time consuming for scattering  is not as fast as we expect ?

**Comment by songqiqqq** [comment]
Initialization problem has been solved, so I would close this issue. Discussion for speed-up problem would be moved to [Standard workflow for using ucx/ucx-py to speed up datatransfer between nodes/processes](https://github.com/dask/distributed/issues/3315).

Thank all of  you.
