### ISSUE TITLE
Environment variables reference

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#363]
This isn't so much an action item as an FYI, but we could try to document this somewhere. It appears there is [a fairly comprehensive list]( https://github.com/openucx/ucx/blob/430ae7e5220ba3b86bfbcc3821b090d1718242cc/src/ucp/core/ucp_context.c#L55 ) of environment variables with descriptions and options defined.

**Comment by pentschev** [comment]
This information is the same that gets displayed with `ucx_info -f`, and using this command includes information from all modules (UCP, UCT, UCM, ...), not only UCP. IMO, the problem with that list for users like us is that there are too many abbreviations making some of that information helpless until you go look elsewhere for their meaning. As examples I could cite abbreviations such as AM, RC and DC.

I guess what I'm trying to say is that the information we get on that list is useful, but not always as an initial resource, as users will first need to understand what they are looking for and what many of those names really mean.

**Comment by quasiben** [comment]
We have been documenting _relevant_ environment variables here: https://ucx-py.readthedocs.io/en/latest/configuration.html#env-vars 

I am trying to keep this up to date with things well or partially understood options and how to mix them for a particular behavior

**Comment by pentschev** [comment]
I think the documentation pointed to by @quasiben in the comment above is quite comprehensive now. With that said, I'm closing this. Feel free to reopen if you disagree and think we should extend it further.

**Comment by jakirkham** [comment]
SGTM. I think the original intent was to share some other info with the group. So that seems accomplished already (just restating what you said).
