### ISSUE TITLE
IB Connection Support build options

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#364]
Have been going back through the build options we are using and am trying to evaluate other options we might use and what benefit they might have. For instance there are some additional options related to different IB connection types that can be specified (see below). Am curious if it makes sense for us to use these and if so what they might offer.

```
  --with-rc               Compile with IB Reliable Connection support
  --with-ud               Compile with IB Unreliable Datagram support
  --with-dc               Compile with IB Dynamic Connection support
```

**Comment by jakirkham** [comment]
Looking more closely at the configuration files, it appears [these are all enabled by default]( https://github.com/openucx/ucx/blob/430ae7e5220ba3b86bfbcc3821b090d1718242cc/src/uct/ib/configure.m4#L22-L46 ). For reference here is [how autoconf configures `--with-*` options]( https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/External-Software.html ). These IB Connection options map to the 3rd case ("an important feature and that it should be enabled by default"). So we should already be getting this functionality. Closing this out.

**Comment by pentschev** [comment]
Yes, we can configure that with `UCX_TLS=rc,...` (or `dc`, or `ud`). I guess `rc` and `ud` are clear to me what they mean, being analogous to TCP and UDP, respectively. But `dc` still isn't to me. @jakirkham while you're there, maybe you could ask someone to explain what exactly "dynamic" means in that case? :)

**Comment by jakirkham** [comment]
I found this [Mellanox Solution Brief]( http://www.mellanox.com/related-docs/applications/SB_Connect-IB.pdf ) that does a decent job of explaining it. Have also [attached the PDF]( https://github.com/rapidsai/ucx-py/files/3949267/Mellanox_SB_Connect-IB.pdf ) just in case that link breaks.

> The concept with DC Transport is that connections are not nailed down at the beginning of the job, but instead are setup and torn down dynamically by the adapter hardware on an ‘as needed’ basis. A simplified way of looking at it is that the adapter device holds a pool of ‘connection resources’ to use on an ‘as needed’ basis whenever the upper layer software wishes to send data to another process within the cluster.

It goes on like this in case you are interested in reading more. 🙂

**Comment by jakirkham** [comment]
Actually given that description and our intended use case maybe we should be preferring `dc` when using IB (if that is possible). WDYT?

**Comment by pentschev** [comment]
I think you're right. It seems that there's a potential overhead to that, but I guess with `rc` the memory problem will be intractable when we start seeing scalable systems with InfiniBand. It probably makes sense that we start investigating how they affect memory and performance with dask.

**Comment by pentschev** [comment]
I filed https://github.com/rapidsai/dask-cuda/issues/215 for that.

**Comment by jakirkham** [comment]
Thanks Peter! 😄
