### ISSUE TITLE
Small transfers with NVLink are slower than TCP

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucx-py#370]
I first observed this with Dask, in general any transfers smaller than 8MB-10MB with NVLink are slower than with TCP over UCX. Here are some comparisons of TCP over UCX and NVLink with UCX-Py (using `ucp/benchmarks/recv-into-client.py`, CuPy objects, no Dask involved):

TCP:
* 1MB: 373MB/s
* 5MB: 364MB/s
* 10MB: 342MB/s
* 100MB: 400MB/s
* 1000MB: 406MB/s
* 10000MB: Too long to run, but certainly not going to defer much from previous results

NVLink:
* 1MB: 160MB/s
* 5MB: 326MB/s
* 10MB: 795MB/s
* 100MB: 6.7GB/s
* 1000MB: 50GB/s
* 10000MB: 122 GB/s (suspicious, doesn't look accurate)

The purpose of this issue is just to track what we can do to improve it, but I don't believe this is not really possible, most likely the overhead of NVLink makes it inefficient for such small transfers. There were some discussions during the UCX hackathon around this issue, and I believe the solution will be something like falling back to a different transport (e.g., TCP) for small transfers.

cc @randerzander @quasiben @jakirkham

**Comment by mrocklin** [comment]
This slide from @Akshay-Venkatesh has different numbers.  I'm curious what the difference is here.

<img width="1589" alt="Screen Shot 2019-12-12 at 4 44 11 PM" src="https://user-images.githubusercontent.com/306380/70757979-b4dee980-1cfe-11ea-8a6a-3d11fc98f266.png">

**Comment by pentschev** [comment]
I did some more testing with `ucx_perftest` as following:

```
# server
CUDA_VISIBLE_DEVICES=0 UCX_TLS=tcp,sockcm,cuda_copy UCX_SOCKADDR_TLS_PRIORITY=sockcm ucx_perftest -t tag_bw -m cuda -s SIZE -n 10 -p 8999

# client
CUDA_VISIBLE_DEVICES=1 UCX_TLS=tcp,sockcm,cuda_copy UCX_SOCKADDR_TLS_PRORITY=sockcm ucx_perftest HOSTNAME -t tag_bw -m cuda -s SIZE -n 10 -p 8999
```

The above is for CUDA+TCP, for NVLink the only change was appending `cuda_ipc` to `UCX_TLS`.

For TCP, I get consistently a bandwidth of 400-500MB/s for any sizes between 10MB and 1GB, with 10GB transfers being at 2.7GB/s.

For NVLink, I see 97GB/s for 10MB, 132GB/s for 100MB, 138GB/s for 1GB, and 980GB/s for 10GB.

I'm not really sure if the results I see are right. All the tests I mentioned here were on a DGX-2, including those at the issue description.

**Comment by Akshay-Venkatesh** [comment]
> This slide from @Akshay-Venkatesh has different numbers. I'm curious what the difference is here.
> 

Also, If I'm not wrong, this result is between two GPUs (either 2 dgx-1 nodes or 2 summit nodes) so  we're looking at IB bandwidth saturation. What @pentschev is pointing to is between two GPUs connected by NVLINKs within the same node. For DGX-2 NVLINK bandwidth shouldn't exceed 6 X NVLINK2 bandwidth of 150 GB/s

**Comment by quasiben** [comment]
I tried with IB and no NVLINK and saw a 3GB/s transfer bandwidth with 1MB arrays:

```
(ucx-src-100) bzaitlen@exp01:~/GitRepos/ucx-py$ UCX_NET_DEVICES=mlx5_0:1 UCXPY_IFNAME=enp134s0f1 CUDA_VISIBLE_DEVICES=1,0 UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,rc,cuda_copy,sockcm python benchmarks/recv-into-client.py -r recv_into -o cupy --n-b
ytes 1Mb -p 13338 -s 172.22.1.26 --n-iter 1000
CUDA RUNTIME DEVICE:  0
Roundtrip benchmark
-------------------
n_iter   | 1000
n_bytes  | 1000.00 kB
recv     | recv_into
object   | cupy
inc      | False

===================
3.02 GB / s
===================
```

This is also on a DGX2

**Comment by quasiben** [comment]
This PR https://github.com/openucx/ucx/pull/3479 seems to indicate IPC is preferred over IB

**Comment by Akshay-Venkatesh** [comment]
> Naively, this seems like UCX is preferring the IPC transport

Got polled on email to comment on this again but @quasiben didn't report if this behaviour shows up with ucx_perftest. 

I don't have access to a DGX-2 at the moment but results on DGX-1 look sane to me (with the exception of 10GB because there's an overflow error there and the benchmark isn't meant to 
necessarily run with such a large buffer). Here are the results I got with up to 4GB sized transfers with master ToT https://github.com/openucx/ucx/commit/dd286b84ba60ada766b6d651ac83a3453503e9b1:

```
1MB:
====
$ UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -
t tag_bw -m cuda -n 100 -s 1000000 &
[2] 45682
...
           100     0.000    97.220    97.220    9809.45    9809.45       10286       10286

[1]-  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest -t tag_bw -m cuda -n 100 -s 1000000
[2]+  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 1000000
```

```
10MB:
=====
$ UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -
t tag_bw -m cuda -n 100 -s 10000000 &
[2] 45721
           100     0.000   449.970   449.970   21194.19   21194.19        2222        2222

[1]-  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest -t tag_bw -m cuda -n 100 -s 10000000
[2]+  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 10000000
```

```
100MB:
======
$ UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 100000000 &
[2] 45795
           100     0.000  4164.889  4164.889   22897.95   22897.95         240         240

[1]-  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest -t tag_bw -m cuda -n 100 -s 100000000
[2]+  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 100000000
```

```
1GB:
====
$ UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -
t tag_bw -m cuda -n 100 -s 1000000000 &
[2] 45835
            26     0.000 39687.542 39687.542   24029.56   24029.56          25          25
            51     0.000 41293.640 40474.845   23094.94   23562.15          24          25
            76     0.000 41262.121 40733.817   23112.59   23412.35          24          25
           100     0.000 42980.830 41273.100   22188.36   23106.44          23          24

[1]-  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest -t tag_bw -m cuda -n 100 -s 1000000000
[2]+  Done                    UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 1000000000
```

```
4GB:
=====
$ UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest -t tag_bw -m cuda -n 100 -s 4000000000 &
[1] 45912

$ UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 4000000000 &
[2] 45916
             8     0.000 144299.895 144299.895   26435.90   26435.90           7           7
            15     0.000 164906.127 153916.136   23132.54   24784.26           6           6
            22     0.000 164904.424 157412.410   23132.78   24233.78           6           6
            29     0.000 164923.429 159225.415   23130.11   23957.84           6           6
            36     0.000 164908.137 160330.388   23132.26   23792.73           6           6
            43     0.000 164905.855 161075.232   23132.58   23682.71           6           6
            50     0.000 164916.447 161613.002   23131.09   23603.90           6           6
            57     0.000 164913.995 162018.387   23131.43   23544.84           6           6
            64     0.000 164905.003 162334.111   23132.70   23499.05           6           6
            71     0.000 164905.718 162587.649   23132.60   23462.40           6           6
            78     0.000 164903.981 162795.525   23132.84   23432.45           6           6
            85     0.000 164912.598 162969.873   23131.63   23407.38           6           6
            92     0.000 164911.985 163117.642   23131.72   23386.17           6           6
            99     0.000 164904.015 163243.951   23132.83   23368.08           6           6
           100     0.000 329859.972 164910.111   11564.60   23131.98           3           6
```

As you can see, unlike what @pentschev reported, I don't see bad behaviour up to 100MB with this *debug*-enabled build that I'm using. @pentschev can you confirm if you see the slow perf on dgx-1 as well? In the meantime I'll wait to get my hands on a dgx-2 and see if I can actually repro what you report.

**Comment by pentschev** [comment]
Thanks @Akshay-Venkatesh . I just realized it fails for me if I don't set `UCX_MEMTYPE_CACHE=n`, but strangely only for small buffers. Is that expected?

After some discussions I had with others today, we realized the reason we see incredibly slow NVLink transfers is due to IPC cache being turned off:

```
$ UCX_CUDA_IPC_CACHE=n UCX_MEMTYPE_CACHE=n
UCX_TLS=tcp,cuda_copy,cuda_ipc ucx_perftest dgx202 -t tag_bw -m cuda -n 100 -s 1000000
[1576279130.353841] [dgx202:12000:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 96 cpus). Performance may be impacted.
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
           100     0.000  1935.580  1935.580     492.71     492.71         517         517
```

When turning it on, we see a much different bandwidth:

```
$ UCX_CUDA_IPC_CACHE=y UCX_MEMTYPE_CACHE=n
UCX_TLS=tcp,cuda_copy,cuda_ipc ucx_perftest dgx202 -t tag_bw -m cuda -n 100 -s 1000000
[1576279230.163662] [dgx202:12885:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 96 cpus). Performance may be impacted.
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
           100     0.000    36.051    36.051   26453.28   26453.28       27738       27738
```

We decided to set `UCX_CUDA_IPC_CACHE=n` in UCX-Py by default because if we don't it OOMs for any significantly large problem (e.g., anything that runs for a few minutes and largely depend on data transfers). But obviously having no cache is not an option for us. That said, https://github.com/openucx/ucx/issues/4410 is now a definite blocker for us. How can we help with that to make sure we have a fix for it soon @Akshay-Venkatesh ?

**Comment by Akshay-Venkatesh** [comment]
@pentschev please providing a C repro for the OOM with ipc cache turned on is the fastest way to get the issue fixed.

**Comment by Akshay-Venkatesh** [comment]
Also,

> I just realized it fails for me if I don't set UCX_MEMTYPE_CACHE=n, but strangely only for small buffers. Is that expected?

I shouldn't be the case. I just set this by default. If you have a C repro for that as well, please open an issue on openucx and tag me.

**Comment by pentschev** [comment]
> @pentschev providing a C repro for the OOM with ipc cache turned on is the fastest way to get the issue fixed.

I thought this was clear already, no? The issue is that the CUDA IPC cache doesn't ever get cleared. I don't know immediately how I can reproduce this in C, I'll have to work on that. @quasiben in case you have ideas

> I shouldn't be the case. I just set this by default. If you have a C repro for that as well, please open an issue on openucx and tag me.

The easiest is just to do that with `ucx_perftest`:

```
$ UCX_TLS=tcp,cuda_copy,cuda_ipc ucx_perftest dgx202 -t tag_bw -m cuda -n 100 -s 1000000
[1576283094.456728] [dgx202:48856:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 96 cpus). Performance may be impacted.
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[1576283098.828763] [dgx202:48856:0]           sock.c:224  UCX  ERROR sendv(fd=93) failed: Bad address
```

**Comment by Akshay-Venkatesh** [comment]
> I thought this was clear already, no?

You're right. The issue is clear but a C repro would help me get started sooner.
 
> The easiest is just to do that with `ucx_perftest`:
> 
> ```
> $ UCX_TLS=tcp,cuda_copy,cuda_ipc ucx_perftest dgx202 -t tag_bw -m cuda -n 100 -s 1000000
> [1576283094.456728] [dgx202:48856:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 96 cpus). Performance may be impacted.
> +--------------+-----------------------------+---------------------+-----------------------+
> |              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
> +--------------+---------+---------+---------+----------+----------+-----------+-----------+
> | # iterations | typical | average | overall |  average |  overall |   average |   overall |
> +--------------+---------+---------+---------+----------+----------+-----------+-----------+
> [1576283098.828763] [dgx202:48856:0]           sock.c:224  UCX  ERROR sendv(fd=93) failed: Bad address
> ```

I'm unable to repro your issue
```
$ UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest -t tag_bw -m cuda -n 100 -s 1000000 &
[1] 58885
$ UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 1000000 &
[2] 58889
           100     0.000    77.860    77.860   12248.52   12248.52       12844       12844[1]-  Done                    UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest -t tag_bw -m cuda -n 100 -s 1000000
[2]+  Done                    UCX_TLS=tcp,cuda_copy,cuda_ipc ./bin/ucx_perftest prm-dgx-13 -t tag_bw -m cuda -n 100 -s 1000000
```

**Comment by pentschev** [comment]
> You're right. The issue is clear but a C repro would help me get started sooner.

We'll see if we can get something to reproduce this.

> I'm unable to repro your issue

Are you on master branch? I've just had clean builds for master and v1.7.x branches, I can confirm it works in master but it still fails for me in v1.7.x on a clean build.

**Comment by jakirkham** [comment]
Does that mean we need a backport to fix this?

**Comment by pentschev** [comment]
> Does that mean we need a backport to fix this?

I don't think so. In UCX-Py we have `UCX_MEMTYPE_CACHE=n` hardcoded because we don't support the default anyway. It was my mistake in not having that variable set in the benchmarks above, and since that's already fixed in 1.8.0, I don't think it matters for us.

**Comment by quasiben** [comment]
@Akshay-Venkatesh I know this is not a C repro but that I should still mention it as a test .  I think we (ucx-py) can use this as UCX work around IPC work proceeds

```
# server
UCX_CUDA_IPC_CACHE=y UCXPY_IFNAME=enp1s0f0 CUDA_VISIBLE_DEVICES=0,1 \
UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm \
UCX_SOCKADDR_TLS_PRIORITY=sockcm python tests/debug-tests/send.py

# client
UCX_CUDA_IPC_CACHE=y UCXPY_IFNAME=enp1s0f0 CUDA_VISIBLE_DEVICES=0,1 \
UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm \
UCX_SOCKADDR_TLS_PRIORITY=sockcm python tests/debug-tests/recv.py
```

The server fails with:
```
CREATING CUDA OBJECT IN SERVER...
ERROR Call to cuMemAlloc results in CUDA_ERROR_OUT_OF_MEMORY
ERROR Call to cuMemAlloc results in CUDA_ERROR_OUT_OF_MEMORY
ERROR Ignored except: <class 'numba.cuda.cudadrv.driver.CudaAPIError'> [2] Call to cuMemAlloc results in CUDA_ERROR_OUT_OF_MEMORY
```

When `UCX_CUDA_IPC_CACHE=n` the tests proceed.

**Comment by Akshay-Venkatesh** [comment]
@quasiben I wrote a small mpi program to recreate the problem here https://gist.github.com/Akshay-Venkatesh/bdeab6c7f47e38ac39fd9f0d45419c96

Able to repro now. Will update soon.

**Comment by quasiben** [comment]
@Akshay-Venkatesh, thank you for doing that.  We were having trouble getting that done

**Comment by Akshay-Venkatesh** [comment]
@quasiben @paulhendricks uncovered a bug that needs to be addressed before providing a workaround for OOM issue. I've filed a PR here https://github.com/openucx/ucx/pull/4599

Workaround will be a follow-up.

**Comment by quasiben** [comment]
Thanks for the update @Akshay-Venkatesh

**Comment by Akshay-Venkatesh** [comment]
Talked with Ben, Peter offline:
Workaround branch to test: https://github.com/Akshay-Venkatesh/ucx/tree/topic/ipc-cache-threshold

Log of OOM issue going away with the above branch.
https://gist.github.com/Akshay-Venkatesh/bdeab6c7f47e38ac39fd9f0d45419c96#file-workaround-txt

We need to test if this suffices to get rid of the OOM issue with Dask and still maintain reasonable perf. We'll need to check with different values of UCX_CUDA_IPC_CACHE_LIMIT (which is currently set to 32mb -- i.e all mappings of size > 32mb will not be reserved in IPC cache)

**Comment by beckernick** [comment]
Is this now considered resolved due to the nightly package setting and use the CUDA IPC cache?

**Comment by pentschev** [comment]
Only partially. We can consider this resolved iff you use a memory pool (e.g., RMM pool). However, the more general problem is open in two aspects when:

1. No memory pool can be used;
1. Managed memory is required.

That said, I think we should leave this open for now.

**Comment by pentschev** [comment]
I've filed #408 and #409 to track the two issues I mentioned on my previous comment and be able to close this in the meantime. Thanks everyone for chiming in on this issue.
