### ISSUE TITLE
UCX_TLS=all works sometimes?

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#373]
Am noticing that there are some cases where `UCX_TLS=all` works. While this still does not work with the tests, it does work in some cases. For instance running `benchmarks/local-send-recv.py` seems to work correctly. 

```bash
$ UCX_MEMTYPE_CACHE=n UCX_TLS=all python benchmarks/local-send-recv.py -o cupy --server-dev 0 --client-dev 0 --reuse-alloc
Roundtrip benchmark
--------------------------
n_iter      | 10
n_bytes     | 10.00 MB
object      | cupy
reuse alloc | True
==========================
Device(s)   | 0, 0
Average     | 2.34 GB/s
--------------------------
Iterations
--------------------------
000         |624.76 MB/s
001         |  3.21 GB/s
002         |  3.29 GB/s
003         |  3.15 GB/s
004         |  3.05 GB/s
005         |  3.08 GB/s
006         |  3.15 GB/s
007         |  3.43 GB/s
008         |  3.30 GB/s
009         |  5.54 GB/s
```

**Comment by quasiben** [comment]
Interesting.  What kind of machine was this on ?

**Comment by jakirkham** [comment]
A DGX-1

**Comment by jakirkham** [comment]
Maybe not surprising, but running with `UCX_TLS=all` was an order of magnitude faster than using `UCX_TLS=tcp,cuda_copy,sockcm`.

**Comment by pentschev** [comment]
`UCX_TLS=all` works in many cases. I remember seeing some where it didn't give us best performance, which is likely correlated to which channels data is going through. The order of magnitude faster is certainly due to InfiniBand and/or NVLink being activated too.

**Comment by jakirkham** [comment]
Was curious to see if things fell apart here somewhere when increasing the size. To my surprise not only did that not happen, but it looks like we are getting ~330GB/s.

```bash
UCX_MEMTYPE_CACHE=n UCX_TLS=all python benchmarks/local-send-recv.py -o cupy --server-dev 0 --client-dev 0 --reuse-alloc --n-bytes '6 Gb'
Roundtrip benchmark
--------------------------
n_iter      | 10
n_bytes     | 6.00 GB
object      | cupy
reuse alloc | True
==========================
Device(s)   | 0, 0
Average     | 147.98 GB/s
--------------------------
Iterations
--------------------------
000         | 24.81 GB/s
001         |332.55 GB/s
002         |334.69 GB/s
003         |334.48 GB/s
004         |317.22 GB/s
005         |332.58 GB/s
006         |329.45 GB/s
007         |334.58 GB/s
008         |334.13 GB/s
009         |321.08 GB/s
```

**Comment by pentschev** [comment]
Another data point is `UCX_TLS=all` won't work on a DGX-2 today: https://github.com/rapidsai/ucx-py/issues/336

**Comment by pentschev** [comment]
I'm not sure if this thread adds much to the previous https://github.com/rapidsai/ucx-py/issues/245 . To keep the number of issues down, I'm tentatively closing this. If you feel we should keep it, please reopen it, or better yet move the relevant discussion to #245 so we can try and keep it all in one place.

**Comment by jakirkham** [comment]
Sounds good. Thanks Peter! 😄
