### ISSUE TITLE
UCX-Py Unintended Restart Troubles (Dask)

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#376]
When using dask + ucx and a worker restarts (timeouts/OOM/etc) I've observed poor behavior for workers trying to reconnect.  I don't have a reproducible example yet but dask has tests for [failed_workers](https://github.com/dask/distributed/blob/master/distributed/tests/test_failed_workers.py) which I think we should run with ucx-py in the loop

**Comment by pentschev** [comment]
Is this still relevant @quasiben ?

**Comment by quasiben** [comment]
No, I think we've generally resolved issues now.  Should something pop up again I'll re-file
