### ISSUE TITLE
Multinode IB Failure

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#449]
@pentschev and I are tracking a failure when running a multinode IB tests.  We see the cluster die and errors like the following

> [prm-dgx-23:16433:1:16433] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)

## Setup
4 Nodes -- each node is a DGX-1 with 8 GPUs and 4 IBs

## Code
https://gist.github.com/quasiben/73cf6d7c2131fe41370014ddc21ecb56

We currently don't know what the issue is but we have tried increasing timeouts:
```
export DASK_DISTRIBUTED__WORKER__MEMORY__Terminate="False"
export DASK_DISTRIBUTED__COMM__TIMEOUTS__CONNECT="60s"
export DASK_DISTRIBUTED__COMM__TIMEOUTS__TCP="600s"
export UCX_RC_TIMEOUT=4s
```

What is especially frustrating about this bug is that sometimes everything proceeds smoothly, though not always

**Comment by quasiben** [comment]
I was able to consistently get for three new clusters after I added timeouts to the scheduler as well:

Could have been lucky -- i'll try more tomorrow

```
export DASK_DISTRIBUTED__COMM__TIMEOUTS__CONNECT="60s"
export DASK_DISTRIBUTED__COMM__TIMEOUTS__TCP="600s"
LOCAL_DIRECTORY=/gpfs/fs1/bzaitlen/dask-local-directory
UCX_RC_TIMEOUT=7s UCX_NET_DEVICES=enp1s0f0 DASK_UCX__TCP=True DASK_RMM__POOL_SIZE=1GB DASK_UCX__ENABLE_INFINIBAND="False" DASK_UCX__ENABLE_NVLINK="False"
/gpfs/fs1/bzaitlen/miniconda3/envs/20200310.2/bin/python -m distributed.cli.dask_scheduler --protocol ucx \
        --scheduler-file $LOCAL_DIRECTORY/dask-scheduler.json >/gpfs/fs1/bzaitlen/sched-out.txt 2>&1 &
```

**Comment by pentschev** [comment]
> I was able to consistently get for three new clusters

Consistently get the error or consistently get the cluster to function properly?

**Comment by quasiben** [comment]
Sorry, consistently get the cluster to fiction properly.

**Comment by quasiben** [comment]
Update:  @pentschev recently resolved a synchronization issue between UCX and cuDF/RMM: https://github.com/dask/distributed/pull/3598 .  This was an issue due assumption for how UCX and cuDF work on the GPU:

cuDF: 
- will not explicitly synchronize before returning

UCX:
- does not use the default stream and IPC transfers are not stream ordered


Again, while PR https://github.com/dask/distributed/pull/3598 resolved synchronization issues, we still have is an issue with IB transfers.  _Errors generally manifests with 4+ nodes_.  We have narrowed the problem down to using GPU RDMA with IB though we currently don't know what the underlying issues is.  Tests assing passing when setting `UCX_IB_GPU_DIRECT_RDMA=no` .  We have not made this a default option in UCX-Py as it greatly impacts performance.

**Comment by pentschev** [comment]
I think this has been resolved, we haven't seen those in a while, closing.
