### ISSUE TITLE
`ucp_helper.h` in cuML no longer able to send / receive UCX messages that need to go through callback

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/ucx-py#460]
At some point, between updates to UCX or UCX-py, the UCX layer of the cuML comms appears to have broken. Unfortunately, even if we had a multi-GPU CI running, it wouldn't have caught this issue since it only seems to occur on >2 GPUs. 

The behavior is very odd, but after a couple days troubleshooting, I think I've narrowed the problematic code path, though I'm still not sure why it's happening for how to fix it. cuML's comms layer blocks after several UCX send and receive requests are created so that we can wait for their completion. This blocking wait function runs a while loop, calling `ucp_worker_progress`, then checking the request objects for `request->completed=true`. For some reason, requests are not passed through the callbacks that were provided to the ucp `tag_send_nb` & `tag_recv_nb` functions and, instead, our blocking wait function eventually begins to see `Not connected` errors returned by `UCS_PTR_STATUS` for these requests. 

What I've noticed is that the reason we were not encountering this error with 2 GPUs is that the requests appear to complete instantly, without having to use the callbacks. As a result, I'm not sure how long this issue has persisted. I'm pretty confident I was running successful tests w/ 8 GPUs in the fall time. 

A good reproducer for this issue can be found in the cuml pytests (but will require removing the xfail annotation):

```
py.test -s $CUML_HOME/python/cuml/test/dask/test_comms.py::test_send_recv
```

I noticed ucx-py is using a slightly different struct to represent request objects. I modified cuML's current struct to only use the `finished` field, but it didn't stop this behavior. I'm wondering if there might be something else in ucx-py which is modifying this request before cuML gets a chance to handle it. Oddly, out of 8 different endpoints, I only see a few pass through the callback and it's usually only on a single endpoint (I've only ever seen it on endpoint #8). 

The send and receive code in ucx-py looks really clean. I'm wondering if some recent changes to either ucx-py, perhaps default configuration settings or its own message handlers may have required some changes on the cuML side that still need to be made.

Here's the C code on the cuML side that executes the UCP send/recv logic: https://github.com/rapidsai/cuml/blob/branch-0.13/cpp/comms/std/src/ucp_helper.h

**Comment by cjnolet** [comment]
Tagging @pentschev and @madsbk in hopes you might have some thoughts / ideas. I'm pretty stumped at this point. I'm thinking it could even potentially be thread-related, though I'm not completely sure how.

**Comment by cjnolet** [comment]
I've added some additional assertions, and an explicit while-loop to call `ucp_worker_progress` while the number of bytes returned is != 0. I've opened a PR for troubleshooting this: https://github.com/rapidsai/cuml/pull/1893/files#diff-a761bf1fe2517cb62196533197dd37a3R373

Here's a printout of running `test_comms.py::test_send_recv` w/ 4x GPUs on a DGX:

```
Done initializing UCX endpoints. Took: 0.013943 seconds.
Building handle
Done building handle.
Done initializing UCX endpoints. Took: 0.008027 seconds.
Building handle
Done initializing UCX endpoints. Took: 0.006709 seconds.
Building handle
Done building handle.
Done building handle.
Done initializing UCX endpoints. Took: 0.008888 seconds.
Building handle
Done building handle.
Initialization complete.
Trial 0 Commsize: 4
0 Receive Request Id: 0
0 Receive Request Id: 1
0 Receive Request Id: 2
0 Send Request ID: 3
0 Send Request ID: 4
0 Send Request ID: 5
About to wait 
0: request completed: 0x7f3fe8001700 5 requests to go
0: request completed: 0x7f3fe8001810 4 requests to go
0: request completed: 0x7f3fe8001870 3 requests to go
Trial 0 Commsize: 4
1 Receive Request Id: 0
1 Receive Request Id: 1
1 Receive Request Id: 2
1 Send Request ID: 3
1 Send Request ID: 4
1 Send Request ID: 5
About to wait 
1: request completed: 0x7fb768001700 5 requests to go
1: request completed: 0x7fb768001810 4 requests to go
1: request completed: 0x7fb768001870 3 requests to go
Trial 0 Commsize: 4
2 Receive Request Id: 0
2 Receive Request Id: 1
2 Receive Request Id: 2
2 Send Request ID: 3
2 Send Request ID: 4
2 Send Request ID: 5
About to wait 
2: request completed: 0x7f031c001700 5 requests to go
2: request completed: 0x7f031c001810 4 requests to go
2: request completed: 0x7f031c001870 3 requests to go
Trial 0 Commsize: 4
3 Receive Request Id: 0
Recv Completed 
3 Receive Request Id: 1
Recv Completed 
3 Receive Request Id: 2
Recv Completed 
3 Send Request ID: 3
3 Send Request ID: 4
Recv Completed 
2 executing ucp_progress 
2: request completed: 0x7f031c001720 2 requests to go
3 Send Request ID: 5
Recv Completed 
2 executing ucp_progress 
About to wait 
2 executing ucp_progress 
2: request completed: 0x7f031c001760 1 requests to go
3 executing ucp_progress 
3: request completed: 0x7ff5300016c0 5 requests to go
3: request completed: 0x7ff530001720 4 requests to go
3: request completed: 0x7ff530001760 3 requests to go
3: request completed: 0x7ff530001700 2 requests to go
3: request completed: 0x7ff530001810 1 requests to go
3: request completed: 0x7ff530001870 0 requests to go
Done. Calling barrier
```

Notice only workers 2 and 3 print `executing ucp_progress`. This means the calls to `ucp_worker_progress` only returned nonezero results for those two workers.

**Comment by cjnolet** [comment]
Also want to tag @jakirkham and @quasiben for thoughts.

**Comment by quasiben** [comment]
We recently added some new defaults:

```
if not os.environ.get("UCX_RNDV_THRESH", False):
    os.environ["UCX_RNDV_THRESH"] = "8192"

if not os.environ.get("UCX_TCP_TX_SEG_SIZE", False):
    os.environ["UCX_TCP_TX_SEG_SIZE"] = "8M"

if not os.environ.get("UCX_TCP_RX_SEG_SIZE", False):
    os.environ["UCX_TCP_RX_SEG_SIZE"] = "8M"
```

But I don't think they are relevant here.  Do you think this is related to the CUDA_IPC_CACHE issues you have mentioned previously ?  Lastly, are you using RMM in these tests ?

**Comment by madsbk** [comment]
First observation is that we need to coordinate the initialization of `ucp_request`. 
UCX-Py sets [`ucp_request_reset()`](https://github.com/rapidsai/ucx-py/blob/84776ec430edff520182a5c7ccd83f790b60cd08/ucp/_libs/core_dep.pxd#L249) as  [`ucp_request_init_callback_t`](https://github.com/rapidsai/ucx-py/blob/84776ec430edff520182a5c7ccd83f790b60cd08/ucp/_libs/core.pyx#L350), which, by coincidence, sets the first 32bits of  `ucp_request` to `0`: https://github.com/rapidsai/ucx-py/blob/84776ec430edff520182a5c7ccd83f790b60cd08/ucp/_libs/core_dep.pxd#L251
Thus, it should work as long as UCX-Py doesn't change this and cuML only use:
```c
struct ucx_context {
  int completed;
};

**Comment by cjnolet** [comment]
@madsbk, that was the first thing I noticed as I was looking through the recent changes in UCX-py. 

I made some changes to the cuml side to use the ucx_context exactly as it is in the hello world example. Since we need to return something from each call to isend and irecv, I created a wrapper struct that carries extra information about the request that doesn’t need to be updated w/ the request.

Unfortunately, the messages are still not going through. I am no longer getting strange error codes but the requests seem to stay in the INPROGRESS state indefinitely (which also seems to be the default, even when the request pointer is invalid, from what I’ve been encountering). 

Is it possible the continuous_ucp_progress() function could somehow be interfering with or the Python endpoint somehow intercepting these messages? I’ll try checking the UCX-py logs.

**Comment by cjnolet** [comment]
I figured out the issue and have fixed it in  https://github.com/rapidsai/cuml/pull/1893.  Piecing back together what happened, it now makes total sense- originally when UCX-py's API was updated, I had updated cuML to match the new format for getting the pointers to underlying ucx endpoints. It looks like it's been recently updated again and cuml was not updated for those changes.

**Comment by Akshay-Venkatesh** [comment]
Good to know. I'm surprised why things worked with two GPUs as we discussed
on Friday.

**Comment by cjnolet** [comment]
Yeah, strangely, there was an extra conversion that no longer needs to be done now that UCX-py is directly returning the `ucp_ep_h`. 

After the initial set of UCX-py changes, we were using `PyLong_AsVoidPtr` and some strange behavior in cython was causing [this line](https://github.com/rapidsai/cuml/pull/1893/files#diff-3c0350c2871553cfc4b4b92f0569e425L137) to always equal the last pointer in the list of endpoints. This means all messages from each worker were always being sent and received  to/from the last worker only. 

Not sure why cython was doing this and it’s indeed very strange and unexpected behavior. I believe the case of two endpoints worked only because the last endpoint in each list which was being used was a different endpoint (since each worker only had 1 endpoint to use).

Anyways, UCX-py is now directly returning the `ucp_ep_h`, which we are able to consume directly, so everything works again. I have also verified things work fine with UCX enabled in Dask. I did notice some strange behavior when using IB, but I think that’s related to my configuration.

**Comment by madsbk** [comment]
Nice catch @cjnolet! 
Sorry for not telling you about the change but since it worked with two GPUs I never thought that endpoint pointers could be the problem.

**Comment by pentschev** [comment]
Glad to hear everything worked out @cjnolet ! I guess we're coming to a more stable interface with UCX-Py now, and hopefully it will get easier for us to communicate users about potentially breaking changes.

> I did notice some strange behavior when using IB, but I think that’s related to my configuration.

We're still trying to debug issues with IB, particularly with RDMA enabled. It seems that IB mostly works if we disable RDMA, so if you're still experiencing issues, I would suggest trying to see if `UCX_IB_GPU_DIRECT_RDMA=no` works for you, if it does then it may be that you're hitting the same issues that we are working on fixing.

**Comment by cjnolet** [comment]
No problem at all, Mads. And thank you for chatting with me on Thursday to help isolate potential causes! 

Ideally, I should been running the cuml tests more frequently and on more than 2 GPUs so I’d have seen the change much earlier. I don’t think it’s reasonable, nor feasible, that you should have to alert all the consumers of the UCX-api every time simple changes are made. 

It also seems like the change in UCX-py shouldn’t have caused this behavior, and I’m still dumbfounded why Cython is behaving the way it is. I’m currently trying to figure out if I need to create a cython issue for it. 

In the end, I think this was an important exercise for cuml. Im going to execute the multi-gpu tests on >2 workers regularly, and push to automate them. Ideally this would even be done against the bleeding edge UCX-py branch so that changes are found more quickly. We do this with Dask already, so it shouldn’t be too hard to do.
