### ISSUE TITLE
[BUG] Error in sys.excepthook on process exit

### ISSUE THREAD

**Issue by randerzander** [rapidsai/ucx-py#468]
In the latest conda nightlies, when terminating a Python process in which a UCX client connection was established, a confusing error is printed:
```
>>> from dask.distributed import Client
>>> client = Client('ucx://10.150.162.155:8786')
>>> client
<Client: 'ucx://10.150.162.155:8786' processes=136 threads=136, memory=1.02 TB>
>>> exit()
Error in sys.excepthook:

Original exception was:
```

This does not happen for TCP clusters.

**Comment by quasiben** [comment]
Thanks @randerzander .  I was able to confirm the issue.

**Comment by jakirkham** [comment]
Was this solved by PR ( https://github.com/rapidsai/ucx-py/pull/469 )?

**Comment by quasiben** [comment]
yes, i believe.  @randerzander if you are still seeing the issue, please re-open.
