### ISSUE TITLE
Repeated and frequent shutdown and creation of UCX cluster causes IO errors

### ISSUE THREAD

**Issue by beckernick** [rapidsai/ucx-py#491]
When I shutdown/create a dask cluster with UCX within 5-15 seconds of another one I seem to error quite a bit more than I used to in the past. This makes it hard to run consecutive workflows that include bringing up / spinning down a LocalCUDACluster.

Routinely the error is something like:
```
File "ucp/_libs/core.pyx", line 426, in ucp._libs.core._Endpoint.close
ucp.exceptions.UCXError: Comm Error "[Send shutdown] ep: 0x7fc1b9bc3728, tag: 0x17fc61825a8b67ec, close_after_n_recv: 4": Input/output error
```

which causes the following through dask’s dispatching:
```
  File "/raid/nicholasb/miniconda3/envs/rapids--20200415-cuda101-1112/lib/python3.7/site-packages/ucp/public_api.py", line 270, in close
    await self._ep.close()
  File "ucp/_libs/core.pyx", line 435, in close
ValueError: Unknown format code 'd' for object of type 'str'
```

This may be related to an issue @pentschev @quasiben and @madsbk were discussing earlier. Will provide a full traceback in a comment.

**Comment by beckernick** [comment]
cc @VibhuJawa

**Comment by cjnolet** [comment]
We are encountering this issue in our Pytests on cuML as well.

**Comment by VibhuJawa** [comment]
FWIW, i encountered this at 10k too but surprisingly if i run the kill command multiple times with sleep it goes away.

**Comment by jakirkham** [comment]
This appears to be [the relevant line]( https://github.com/rapidsai/ucx-py/blob/8a9a10ee30f1fa163194cae19cc8635db6810e2a/ucp/_libs/core.pyx#L426 ). May be related to PR ( https://github.com/rapidsai/ucx-py/pull/485 ).

**Comment by jakirkham** [comment]
The logging error has been fixed, but not necessarily the underlying error causing the problem. Given this, going to reopen.

That said, it would be useful to have some kind of reproducer here to better understand when and why this happens.

**Comment by pentschev** [comment]
Over the past 6 months there was a lot of rework on many things. I haven't seen this error for probably even longer than that, I strongly believe it has been resolved. I'm closing this, please feel free to reopen should this be found again or if anybody know of any current instances of it.
