### ISSUE TITLE
Possible failure in `exchange_peer_info` (discussion)

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#495]
During  `exchange_peer_info` we use `stream_send/recv`:
https://github.com/rapidsai/ucx-py/blob/6b7d529a1fe1543159434d497114d58b3b0ae1ac/ucp/core.py#L34-L37

This in turn calls `ucp_stream_send_nb` which has an [interesting note](http://openucx.github.io/ucx/api/v1.5/html/group___u_c_p___c_o_m_m.html
):

>  If the send operation is completed immediately the routine returns UCS_OK and the call-back function cb is not invoked. If the operation is not completed immediately and no error reported, then the UCP library will schedule invocation of the call-back cb upon completion of the send operation. In other words, the completion of the operation will be signaled either by the return code or by the call-back.

Should we not return `UCS_OK`, our callback looks like the following:
https://github.com/rapidsai/ucx-py/blob/6b7d529a1fe1543159434d497114d58b3b0ae1ac/ucp/_libs/ucx_api.pyx#L431-L456

Is it possible that we proceed in the `exchange_peer_info` routine *without* completing a tag exchange  ?

**Comment by pentschev** [comment]
After looking further at this, I think everything is indeed correct @quasiben . The returned `status` of `ucp_stream_send_nb` is a `ucp_request` (when it's not `UCS_OK` or an error). In that case, the callback requirements are populated by https://github.com/rapidsai/ucx-py/blob/6b7d529a1fe1543159434d497114d58b3b0ae1ac/ucp/_libs/ucx_api.pyx#L415-L427 which will ensure that the callback has the appropriate information on time.

However, for `tag_send` I think we may still have a problem. It works the same way as I wrote above, but if the user code doesn't immediately `await` on the future, it may happen that the `ucp_request` may not be available when the callback is executed. Not sure if I'm missing something here still, but it's something worth to double-check.

**Comment by pentschev** [comment]
This was fixed in https://github.com/rapidsai/ucx-py/pull/509, closing.
