### ISSUE TITLE
[FEA] Communication tags 

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#502]
Add support for specifying tags on send and receive. 

One motivation is in Dask where we have to [`await` all sends immediately](https://github.com/dask/distributed/blob/35dc9409f8cf99f82c354b97302846705dfbcc4a/distributed/comm/ucx.py#L181).  
With tags support, Dask could initiate all the sends using different tags before `await`'ing on them.

**Comment by pentschev** [comment]
I'm guessing this would require also some work in Dask, as I think it's not currently supported to make communication completely async, TCP also awaits for transfers to complete.

**Comment by jakirkham** [comment]
I think the idea is to do an `asyncio.gather` on all the futures.

It should only affect a handful of lines in the send/recv code paths. No API changes needed in Dask.

**Comment by pentschev** [comment]
You're right @jakirkham , I misread, sorry for the noise.

**Comment by madsbk** [comment]
Implemented by  #515
