### ISSUE TITLE
[FEA] Support `UCP_EP_CLOSE_MODE_FORCE` 

### ISSUE THREAD

**Issue by madsbk** [rapidsai/ucx-py#505]
Add support for the `UCP_EP_CLOSE_MODE_FORCE` option when creating endpoint. 
This option requires the `UCP_ERR_HANDLING_MODE_PEER` option when initializing UCX, which combined with a UCX error handler should make UCX-Py more resilient: https://github.com/rapidsai/ucx-py/issues/500

**Comment by pentschev** [comment]
> This option requires the UCP_ERR_HANDLING_MODE_PEER option when initializing UCX, which combined with a UCX error handler should make UCX-Py more resilient: #500

Just FYI, I began working on this already, but not the `UCP_EP_CLOSE_MODE_FORCE`.

**Comment by pentschev** [comment]
This is supported now, but currently disabled by default. We may reenable it starting with UCX 1.11 and after https://github.com/rapidsai/ucx-py/pull/693 is merged. I'm closing for now.
