### ISSUE TITLE
Endpoint to client times out in dask-scheduler

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucx-py#510]
The dask-scheduler is currently crashing when its endpoint to the client times out:

```
[dgx12:42167:0:42167] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[dgx12:42167:0:42167] ib_mlx5_log.c:139  RC QP 0x13d6b wqe[232]: SEND --e [inl len 26]
[dgx12:42167:0:42167] Process frozen...
```

This is happening a few seconds after the client finishes its job and disconnects from the scheduler. We used to have the same issue some days ago and I think it was fixed and probably reintroduced somehow.

The issue can be reproduced with current branch-0.14, https://github.com/rapidsai/ucx-py/commit/5e41a02226f85e6960ad521a8635a6194126dd22 at the time of writing.

cc @madsbk @quasiben

**Comment by pentschev** [comment]
This can be reproduced on a single DGX-1 with InfiniBand _enabled_ and the following code:

```python
import cudf
import dask.dataframe as dd
import dask.array as da

from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait

def create_random_data(n_rows=1_000,n_parts = 10, n_keys_index_1=100_000,n_keys_index_2=100,n_keys_index_3=100, col_prefix = 'a'):
    chunks = n_rows//n_parts

    df = dd.concat([
        da.random.random(n_rows, chunks = chunks).to_dask_dataframe(columns= col_prefix + '_non_merge_1'),
        da.random.random(n_rows, chunks = chunks).to_dask_dataframe(columns= col_prefix + '_non_merge_2'),
        da.random.random(n_rows, chunks = chunks).to_dask_dataframe(columns= col_prefix + '_non_merge_3'),
        da.random.randint(0, n_keys_index_1, size=n_rows,chunks = chunks ).to_dask_dataframe(columns= col_prefix + '_0'),
        da.random.randint(0, n_keys_index_2, size=n_rows, chunks = chunks ).to_dask_dataframe(columns= col_prefix +'_1'),
        da.random.randint(0, n_keys_index_3, size=n_rows, chunks = chunks ).to_dask_dataframe(columns= col_prefix +'_2'),

    ], axis=1).persist()

    gdf = df.map_partitions(cudf.from_pandas)
    gdf =  gdf.persist()
    _ = wait(gdf)
    return gdf


if __name__ == "__main__":
    client = Client("ucx://SCHEDULER_IP:8786")

    mult = 1
    rows_1, parts_1 = 140_176_770*mult, 245*mult
    rows_2, parts_2 = 21_004_393*mult, 171*mult

    df_1 = create_random_data(n_rows= rows_1, n_parts = parts_1, col_prefix = 'a')
    df_2 = create_random_data(n_rows= rows_2,  n_parts = parts_2, col_prefix = 'b')

    merged_df = df_1.merge(df_2, left_on = ['a_0','a_1','a_2'], right_on = ['b_0','b_1','b_2'])
    res = merged_df.persist()
```

**Comment by pentschev** [comment]
This remains an issue, one simple workaround is to add the following just before the end of the script:

```python
client.close()
time.sleep(1)
```

**Comment by jakirkham** [comment]
Maybe worth running `git bisect` to isolate the commit that introduced it?

**Comment by pentschev** [comment]
> Maybe worth running git bisect to isolate the commit that introduced it?

That's an issue that has been fixed and reintroduced a couple of times now, probably in one of the most recent cleanups. It's not going to be easy to git bisect, as we'll likely need some of the fixes that have been introduced along the way.

**Comment by jakirkham** [comment]
`git bisect` is able to identify the most recent commit reintroducing the issue if it was working recently. Otherwise it may not have actually been fixed.

**Comment by pentschev** [comment]
What I mean is that by bisecting we may reintroduce other issues that have been fixed along the way and will make it hard to debug, given such issues are not always reproducible in the exact same manner.

**Comment by jakirkham** [comment]
`git bisect` simply finds a commit where a problem was introduced. It doesn’t change the code itself. So I’m not sure I follow the concern.

**Comment by pentschev** [comment]
This has been resolved in recent times, but can still be seen if a process segfaults for example. This is nevertheless not a UCX problem (at least not in recent times), but rather an error when that occurs when something really fails. Closing.
