### ISSUE TITLE
[DOC] NVLINK + IB config may be incorrect

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/ucx-py#516]
In the [docs](https://github.com/rapidsai/ucx-py/blob/branch-0.14/docs/source/configuration.rst#ib----yes-nvlink
) we state below as config :

```
UCX_RNDV_SCHEME=put_zcopy UCX_MEMTYPE_CACHE=n UCX_TLS=rc,cuda_copy,cuda_ipc
```

On based of a slack discussion with @pentschev , we may want it  `UCX_TLS` to be below : 
```
UCX_TLS=rc,tcp,sockcm,cuda_copy,cuda_ipc
```

I may be reading the docs wrong, please feel free to close if that the case.

**Comment by pentschev** [comment]
I filed #518 to fix that, thanks @VibhuJawa for pointing it out.
