### ISSUE TITLE
Closing Race Condition Test

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#517]
UCX-Py has a race condition if await `ucx_api.tag_send()` doesn't return immediately and another worker aborts the endpoint.

We currently have only experienced this race condition at a large number of workers which makes testing challenging.  @madsbk 
 suggested that perhaps we could use the rendezvous protocol to force this ?

**Comment by madsbk** [comment]
Just to be clear, the race condition has been fixed by #513, it is just that we don't have a test of the specific scenario.

**Comment by quasiben** [comment]
Yes!  Sorry, I didn't make that clear.  We just need the test

**Comment by pentschev** [comment]
I'm closing this, it seems this was resolved and no new reports since.
