### ISSUE TITLE
Multinode IB Performance Tracking

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#519]
We have recently resolved usability of IB and IB/NVLink and upgraded to UCX 1.8.  We have since then moved onto measuring performance.  Unfortunately, we have loosely observed that when performing a multi-node multi-gpu merge (with 4 nodes) while using IB and NVLink, we do not see performance gains and sometimes degradations.   The workflow we are measuring against is based on a [merge of dataframes](https://gist.github.com/quasiben/73cf6d7c2131fe41370014ddc21ecb56) with random data.

Ideas to experiment with and/or track down:

## put/get-zcopy
`put_zcopy` does not seem to work with 1.8 and we have  hardcoded [get_zcopy](https://github.com/rapidsai/ucx-py/blob/bc6a43664c5390b1930cc3178a7991a99cd54967/ucp/__init__.py#L33-L34). 
 It would be good to have a more developed understanding of what these config option control and if they have any performance implications. 
 For example, in the [Rendezvous-Protocol 
](https://github.com/openucx/ucx/wiki/Rendezvous-Protocol) page, `get_zcopy` has uses a different latency calculation (note: `put_zcopy` is not listed there)

## UCX_TCP_TX/RX_SEG_SIZE
Previously we have hardcoded [UCX_TCP_TX/RX_SEG_SIZE](https://github.com/rapidsai/ucx-py/blob/bc6a43664c5390b1930cc3178a7991a99cd54967/ucp/__init__.py#L36-L40 to be `8M` .  Can this config option dramatically change performance at the MNMG scale ?

## UCX_RC_VERBS_*
There are complementary TCP config option for InfiniBand such as `UCX_RC_VERBS_SEG_SIZE`.  Should these also be tuned ?

## RDMACM 
Our default setup uses `sockcm` for `UCX_SOCKADDR_TLS_PRIORITY`.   Perhaps in IB environments using `rdmacm` makes more sense and also has performance implications

## Single node test of benchmark
We should rerun the single node [merge benchmark](https://github.com/rapidsai/dask-cuda/blob/4ed7ae6b7420a67fd6f98cb38580cf795b14bdcd/dask_cuda/benchmarks/local_cudf_merge.py) with latest ucx/ucx-py and confirm performance numbers recently posted

## Two Node Test
Rerun tests with two nodes and try to back out data sent via IB and data sent with NVLink:
- NVLink measuring: `nvidia-smi nvlink -g 0`
- IB Measuring -- we are less familiar here but perhaps using /sys/class/infiniband/mlx5_*/ports/1/counters/port_xmit_data would work ?  (xref https://community.mellanox.com/s/article/understanding-mlx5-linux-counters-and-status-parameters)

**Comment by quasiben** [comment]
We tested the single node case and saw no major differences in performance between ucx-1.7 and ucx-1.8

## UCX 1.8
```
ucx                       1.8.0+g5a306c1      cuda10.2_15    rapidsai-nightly
ucx-py                    0.14.0a0+192.gbc6a436          pypi_0    pypi
```

<details>

```
Merge benchmark
-------------------------------
backend        | dask
rows-per-chunk | 100000000
protocol       | ucx
device(s)      | 0,1,2,3,4,5,6,7
rmm-pool       | True
frac-match     | 0.3
tcp            | True
ib             | True
nvlink         | True
data-processed | 25.60 GB
===============================
Wall-clock     | Throughput
-------------------------------
4.94 s         | 5.18 GB/s
1.48 s         | 17.24 GB/s
1.66 s         | 15.39 GB/s
1.34 s         | 19.06 GB/s
1.60 s         | 15.99 GB/s
===============================

Merge benchmark
-------------------------------
backend        | dask
rows-per-chunk | 100000000
protocol       | ucx
device(s)      | 0,1,2,3,4,5,6,7
rmm-pool       | True
frac-match     | 0.3
tcp            | True
ib             | False
nvlink         | True
data-processed | 25.60 GB
===============================
Wall-clock     | Throughput
-------------------------------
14.14 s        | 1.81 GB/s
5.96 s         | 4.30 GB/s
7.34 s         | 3.49 GB/s
7.64 s         | 3.35 GB/s
6.50 s         | 3.94 GB/s
===============================
```
</details>


## UCX 1.7
```
ucx                       1.7.0+g9d06c3a       cuda10.1_0    rapidsai-nightly
ucx-py                    0.14.0a200414+g9d06c3a         py37_90    rapidsai-nightly
```

<details>
```

Merge benchmark
-------------------------------
backend        | dask
rows-per-chunk | 100000000
protocol       | ucx
device(s)      | 0,1,2,3,4,5,6,7
rmm-pool       | True
frac-match     | 0.3
tcp            | True
ib             | True
nvlink         | True
data-processed | 25.60 GB
===============================
Wall-clock     | Throughput
-------------------------------
17.19 s        | 1.49 GB/s
1.46 s         | 17.50 GB/s
1.78 s         | 14.39 GB/s
1.39 s         | 18.45 GB/s
1.48 s         | 17.28 GB/s
===============================


Merge benchmark
-------------------------------
backend        | dask
rows-per-chunk | 100000000
protocol       | ucx
device(s)      | 0,1,2,3,4,5,6,7
rmm-pool       | True
frac-match     | 0.3
tcp            | True
ib             | False
nvlink         | True
data-processed | 25.60 GB
===============================
Wall-clock     | Throughput
-------------------------------
9.14 s         | 2.80 GB/s
7.12 s         | 3.59 GB/s
8.19 s         | 3.13 GB/s
6.65 s         | 3.85 GB/s
7.32 s         | 3.50 GB/s
===============================
```
</details>

**Comment by pentschev** [comment]
I have some proposed answers/closures for some of the topics above, see below.

> ## put/get-zcopy

Tests above (UCX 1.7 vs 1.8) seem to confirm there's no noticeable performance difference on changing `put_zcopy` to `get_zcopy`. Note that this was a change made when UCX was upgraded to 1.8, we used to have `put_zcopy` as default and now we replaced it `get_zcopy` due to some issues with TCP.

*In short: both perform the same.*

> ## UCX_RC_VERBS_*

The default in UCX is `UCX_RC_VERBS_SEG_SIZE=8256`. I played a bit with these values and changing that to `8K` and `1M` has no noticeable effect in performance. Switching to `8M` causes processes never to connect to each other, which seems to indicate this value goes beyond IB limits. Regardless, I don't think this is of any help right now.

*In short: no noticeable performance changes.*

> ## RDMACM

Running with `RDMACM` on 4 DGX-1 nodes seems to have a marginal improvement in performance, see details below:

<details>
```
IB
Create time: 53.888248920440674
Merge time: 83.2080008983612
Create time: 53.25632405281067
Merge time: 84.0105676651001
Create time: 53.42793893814087
Merge time: 83.17894244194031

IB (RDMACM)
Create time: 54.45754384994507
Merge time: 78.65560245513916
Create time: 53.199059009552
Merge time: 77.84190249443054
Create time: 52.77104949951172
Merge time: 76.58169960975647

IB - Distributed Pack Frames
Create time: 24.87168312072754
Merge time: 56.29615259170532
Create time: 24.89400362968445
Merge time: 57.5418541431427
Create time: 24.720890998840332
Merge time: 57.817102670669556

IB (RDMACM) - Distributed Pack Frames
Create time: 25.35990262031555
Merge time: 58.856733560562134
Create time: 25.007176637649536
Merge time: 53.327295780181885
Create time: 25.060538053512573
Merge time: 54.162463426589966
```
</details>

However, we've noticed that RDMACM is not supported or incorrectly configured in several clusters, which may make this not feasible to use in the short-term.

*In short: marginally improves performance, may hit configuration issues in certain clusters.*

**Comment by jakirkham** [comment]
Am I reading this right? It looks like RDMACM is ~0.5s slower than without.

**Comment by pentschev** [comment]
> Am I reading this right? It looks like RDMACM is ~0.5s slower than without in create time.

Yeah, interestingly using `sockcm` seems to spend less time in transferring data and compute time than `rdmacm`, yet final timings for merge seems to be lower for `rdmacm`. I can't explain any of that, but some details follow.

<details>

```
# IB (RDMACM) -- Create only
Create time: 25.362544059753418
Spent time: defaultdict(<class 'int'>, {'compute': 419.23007917404175, 'transfer': 535.0577464103699})
Create time: 24.26438283920288
Spent time: defaultdict(<class 'int'>, {'compute': 406.45365691185, 'transfer': 510.0277910232544})
Create time: 24.368610858917236
Spent time: defaultdict(<class 'int'>, {'compute': 403.97691464424133, 'transfer': 515.5055191516876})

# IB (SOCKCM) -- Create only
Create time: 24.527733325958252
Spent time: defaultdict(<class 'int'>, {'compute': 382.85888934135437, 'transfer': 492.8274972438812})
Create time: 24.4702889919281
Spent time: defaultdict(<class 'int'>, {'compute': 367.4359884262085, 'transfer': 468.1648790836334})
Create time: 24.494860887527466
Spent time: defaultdict(<class 'int'>, {'compute': 360.0715916156769, 'transfer': 444.0930664539337})

# IB (RDMACM) -- Create + Merge
Create time: 25.291167497634888
Merge time: 55.47050356864929
Spent time: defaultdict(<class 'int'>, {'compute': 503.93750381469727, 'transfer': 3057.6658987998962})
Create time: 24.80266761779785
Merge time: 54.58209538459778
Spent time: defaultdict(<class 'int'>, {'compute': 474.21338176727295, 'transfer': 2487.0608882904053})
Create time: 25.63095188140869
Merge time: 56.572834968566895
Spent time: defaultdict(<class 'int'>, {'compute': 474.57287859916687, 'transfer': 2597.6170439720154})

# IB (SOCKCM) -- Create + Merge
Create time: 24.662564992904663
Merge time: 59.5018150806427
Spent time: defaultdict(<class 'int'>, {'compute': 455.5273778438568, 'transfer': 2917.335283279419})
Create time: 24.57557511329651
Merge time: 56.79560732841492
Spent time: defaultdict(<class 'int'>, {'compute': 429.57089591026306, 'transfer': 2220.180385351181})
Create time: 25.298842191696167
Merge time: 57.65154409408569
Spent time: defaultdict(<class 'int'>, {'compute': 423.69893288612366, 'transfer': 2281.695979833603})
```

</details>

**Comment by quasiben** [comment]
@pentschev should we close this issue ? We (you) added RDMACM to dask-cuda.  I don't think there are lingering ucx-py issues with IB, correct ?

**Comment by pentschev** [comment]
I'm fine closing this, I think everything is mostly stable at this time.

**Comment by pentschev** [comment]
As per the latest discussions, I'm closing this.
