### ISSUE TITLE
Distributed GPU Metric test

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#523]
Add distributed/tests/test_gpu_metrics.py in the ucx-py CI

**Comment by pentschev** [comment]
Probably makes more sense to move tests that are not specific to communications to dask-cuda ?

**Comment by quasiben** [comment]
I would be infavor of moving distributed tests to dask-cuda including `distributed/tests/test_gpu_metrics.py` happy to pick this up
