### ISSUE TITLE
CPU Conda Package

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#525]
Previously, we didn't need to load libcuda when importing ucx-py.  With the addition of the [ib_registration_cache.patch](https://github.com/rapidsai/ucx-split-feedstock/blob/master/recipe/meta.yaml#L26) this is no longer the case. I believe we now need to build a CPU conda package and use something like `ucx-proc` to select between CPU and GPU versions.

**Comment by jakirkham** [comment]
The possibility for such a build [exists]( https://github.com/rapidsai/ucx-split-feedstock/blob/2c741245e8c0d4e050854388e352987dcbc878bf/.ci_support/linux_cuda_compiler_versionNone.yaml ). Would need help from OPS to enable it though

cc @mike-wendt

**Comment by pentschev** [comment]
rapidsai/ucx-split-feedstock#24 should tackle this.

**Comment by quasiben** [comment]
This has now been resolved:

```
130 ❯ conda create -n ucx-cpu -c rapidsai-nightly -c conda-forge ucx=1.8 ucx-proc=*=cpu dask-core ucx-py
Collecting package metadata (current_repodata.json): done
Solving environment: done


## Package Plan ##

  environment location: /home/quasiben/miniconda3/envs/ucx-cpu-2

  added / updated specs:
    - dask-core
    - ucx-proc[build=cpu]
    - ucx-py
    - ucx=1.8
```
