### ISSUE TITLE
CPU only patch

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#528]
If we are going to build cpu only version of ucx I think we need to fix the patches in [ucx-split-feedstock](https://github.com/rapidsai/ucx-split-feedstock/tree/master/recipe)

When applying `add-page-alignment.patch` we currently get an error:

```
(base) bzaitlen@dgx12:/datasets/bzaitlen/GitRepos/ucx$ git apply ../ucx-split-feedstock/recipe/add-page-alignment.patch
error: patch failed: src/ucs/memory/rcache.c:496
error: src/ucs/memory/rcache.c: patch does not apply
```

I think the `add-page-alignment.patch` is also only necessary for GPU builds.  If that is the case we can amend the meta.yaml with `[cuda_compiler_version != "None"]` for the page alignment patch.

https://github.com/rapidsai/ucx-split-feedstock/blob/2c741245e8c0d4e050854388e352987dcbc878bf/recipe/meta.yaml#L26-L27

@jakirkham @pentschev if you have time can you comment ?

**Comment by pentschev** [comment]
Sorry, I think I've missed this here. Is it still relevant @quasiben ? I think this may have already been solved by https://github.com/rapidsai/ucx-split-feedstock/pull/24 .

**Comment by quasiben** [comment]
If you have a strong preference for closing I am fine with that.  We haven't merge in rapidsai/ucx-split-feedstock#24 so it may be good to keep this open?

**Comment by pentschev** [comment]
Sure, we can keep it open, I'm mainly asking whether the question has been answered or is still an open one.
