### ISSUE TITLE
Thoughts on high level API

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#56]
I thought it would help a bit if I were to describe what an ideal API would be from my perspective.  This is high level and I'm happy to change things.

### Establishing connections

Ideally we have a server that is able to accept many connections and handle them appropriately

```python
def on_new_connection(connection):
    """ This gets called whenver anyone connects to us

    Probably we have some while loop in here that asynchronously waits for messages
    processes them, and then sends back responses
    """

server = ucxpy.listen(server_address, ..., on_new_connection=on_new_connection)
```

A client might connect to this server, producing some sort of communication object that can send an recieve messages.

```python
connection = connect(server_address)
```

### Connection objects

This connection can send bytestrings (or their device equivalent

```python
msg = b'1234'
connection.send(msg)
```

It could also receive messages asynchronously with a callback (I plan to use an async framework like Tornado or asyncio, but I suspect that adding connections there would be more complex than you want to get into.  I can probably add these pieces if the following is possible).

```python
def callback(future):
    assert future.done()
    msg = future.result()
    ... handle resulting message

# get the next message sent by the other side
future = connection.recv()  # This returns immediately
future.add_done_callback(callback)
```

### Host and Device Memory

Ideally the connection objects handles host-memory and device-memory buffers transparently.  I would prefer not to have to pre-allocate buffers.  I plan to typecheck on the result of `recv` in user code.

```python
def callback(future):
    msg = future.result()
    if isinstance(msg, (bytes, memoryview)):  # on host memory
        ...
    elif isinstance(msg, some_device_memory_thing): # on device memory
        ...
```

### Final thoughts

This is just what makes sense to me as a Python user.  I only have half of the picture though.  I thought that expressing this is more concrete terms might help to stimulate conversation and future work.

**Comment by madsbk** [comment]
Both `devel` and `branch-0.10` implements most of the idea here. Let's open a new issue if we need further API discussion.
