### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by TomAugspurger** [rapidsai/ucx-py#57]
Collecting some thoughts on automated testing for ucx-py here. I'd be curious to hear others' thoughts here.

1. Infrastructure: right now to do any kind of testing we need a machine with a GPU, cuda, and infiniband. Is that correct? What parts of those are necessary as part of a basic Continuous Integration workflow? IIUC, infiniband is currently required because of https://github.com/openucx/ucx/issues/3042. An eventual goal is to have something that can be run as part of Distributed's regular CI (either on each pull request, or perhaps nightly). Getting there sounds challenging, but I've never tried to set up CI with specific machine requirements beyond the choosing the OS.

2. Assuming the (hard problems) in 1 have been addressed, what how do we setup a server, client, and everything else for a unit test? Right now I think we need to manually start up the server before running any of the scripts in `tests/`. Dask (along with much of the python ecosystem) uses `pytest` as its test runner. It'd be nice to have fixtures for everything we need. Something like

```python
@pytest.fixture
def ucx_server():
    ...

@pytest.fixture
def ucx_client():
    ...


def test_ping(ucx_client, ucx_server):
    result = await ucx_client.ping(address)
```

@mrocklin are there any patterns or examples from distributed's test suite that would be helpful here?

**Comment by madsbk** [comment]
Standalone tests and TCP support exist for both `devel` and `branch-0.10`
