### ISSUE TITLE
Failure with RMM (post CNMeM deprecation)

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#578]
Have been seeing the following failures on CI and locally with [the benchmarks]( https://github.com/rapidsai/ucx-py/tree/branch-0.15/benchmarks ) since PR ( https://github.com/rapidsai/rmm/pull/466 ) was merged. A fair bit of history is documented in PR ( https://github.com/rapidsai/ucx-py/pull/575 ), a style PR, where this first came up. Though it can be reproduced outside of that PR.

Tried specifying the memory pool size to be close to the amount of memory on the GPU (with some space still free for other miscellaneous usage). However that still fails. Tried a pool size of `0`, which also fails. Changing the chunk size also fails. All with the same error.

In the send/recv case using different devices for server and client avoids the issue. Also using the CuPy memory pool instead of RMM's works fine in send/recv.

At a bit of a loss for what is happening here, would be great to have another set of eyes 🙂 

<details>
<summary>Dataframe merge benchmark failure:</summary>

```bash
python benchmarks/cudf-merge.py --chunks-per-dev 4 --chunk-size 10000
```

```python
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/ucp/utils.py", line 163, in _worker_process
    ret = loop.run_until_complete(run())
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/ucp/utils.py", line 158, in run
    return await func(rank, eps, args)
  File "/datasets/jkirkham/devel/ucx-py/benchmarks/cudf-merge.py", line 169, in worker
    df1 = generate_chunk(rank, args.chunk_size, args.n_chunks, "build", args.frac_match)
  File "/datasets/jkirkham/devel/ucx-py/benchmarks/cudf-merge.py", line 114, in generate_chunk
    "key": cupy.arange(start, stop=stop, dtype="int64"),
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/cupy/creation/ranges.py", line 55, in arange
    ret = cupy.empty((size,), dtype=dtype)
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/cupy/creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 544, in cupy.cuda.memory.alloc
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/rmm/rmm.py", line 270, in rmm_cupy_allocator
    buf = librmm.device_buffer.DeviceBuffer(size=nbytes)
  File "rmm/_lib/device_buffer.pyx", line 70, in rmm._lib.device_buffer.DeviceBuffer.__cinit__
MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp68: cudaErrorMemoryAllocation out of memory
```

</details>

<details>
<summary>Send/Recv benchmark failure:</summary>

```bash
python benchmarks/local-send-recv.py -o rmm --server-dev 0 --client-dev 0 --reuse-alloc
```

```python
Server Running at 10.33.225.165:48726
Client connecting to server at 10.33.225.165:48726
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<_listener_handler_coroutine() done, defined at /datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/ucp/core.py:144> exception=MemoryError('std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp68: cudaErrorMemoryAllocation out of memory')>
Traceback (most recent call last):
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/ucp/core.py", line 196, in _listener_handler_coroutine
    await func(ep)
  File "/datasets/jkirkham/devel/ucx-py/benchmarks/local-send-recv.py", line 68, in server_handler
    t = np.zeros(args.n_bytes, dtype="u1")
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/cupy/creation/basic.py", line 204, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 544, in cupy.cuda.memory.alloc
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/rmm/rmm.py", line 270, in rmm_cupy_allocator
    buf = librmm.device_buffer.DeviceBuffer(size=nbytes)
  File "rmm/_lib/device_buffer.pyx", line 70, in rmm._lib.device_buffer.DeviceBuffer.__cinit__
MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp68: cudaErrorMemoryAllocation out of memory
```

</details>

**Comment by jakirkham** [comment]
Have been using the RMM packages produced with PR ( https://github.com/rapidsai/rmm/pull/493 ) included and the issue still occurs. So think this is orthogonal to issue ( https://github.com/rapidsai/dask-cuda/issues/364 ) from yesterday.

**Comment by jakirkham** [comment]
Potentially related issue ( https://github.com/rapidsai/rmm/issues/496 ).

**Comment by jakirkham** [comment]
So it looks like PR ( https://github.com/rapidsai/rmm/pull/498 ) fixed this on CI. However I seem to still be running into this issue locally unfortunately. Guessing there is another problem we haven't uncovered here. Will continue to investigate and report back.

**Comment by harrism** [comment]
Could it be good old memory fragmentation due to your usage pattern?

**Comment by jakirkham** [comment]
I don't think so because it works on CI (thanks to your recent fix 🙂), which has less memory to work with.

**Comment by jakirkham** [comment]
FWIW here is the [cuDF merge RMM log]( https://github.com/rapidsai/ucx-py/files/5077707/cudf-merge-rmm.dev0.log ). Also here is [the CuPy send/recv server RMM log]( https://github.com/rapidsai/ucx-py/files/5077715/server-local-send-recv-rmm.dev0.log ), but it appears the client doesn't produce a log (so maybe the client fails before then?).

**Comment by jakirkham** [comment]
Should add the cuDF merge case allocates `1.65 MB` (ignoring `free`s). Additionally if we specify the pool size, we are able to bypass this issue. For example, using a pool size of `1 MB` runs into the issue. However a pool size of `2 MB` does not. What is also interesting is we use the default pool size if not specified (which on a `32 GB` machine would expect is `16 GB`); however, that fails (even though it should be much larger than `2 MB`).

**Comment by jakirkham** [comment]
Ok, have rerun with large enough pool sizes that allow these to run to completion and collected the logs. Here are [the working cuDF merge RMM logs]( https://github.com/rapidsai/ucx-py/files/5077833/cudf-merge-rmm-working.dev0.log ) and [the working send/recv RMM logs]( https://github.com/rapidsai/ucx-py/files/5077832/local-send-recv-rmm-working-logs.zip ).

**Comment by harrism** [comment]
Can you try explicitly setting the pool size to 16GiB? Could have introduced a new init bug.

Looking at the successful log it has 55 allocs and 55 frees so no obvious memory leak.

**Comment by harrism** [comment]
Is this a multithreaded test? I noticed that the log is corrupted: 

```
73064,16:47:59:728833,free,0x7fc970800000,80000,0
73064,16:47:59:728836,free,0x7fc970827200,80000,0
73064,16:47:59:728839,free,0x7fc970867000,80000,0
73064,16:47:59:728842,free,0x7fc97087aa00,80000,0
73064,16:47:59:728844,free,0x7fc97083ab00,80000,0
6e42b5500,80000,0
73078,16:47:59:725597,free,0x7f66e42a1c00,80000,0
73078,16:47:59:725600,free,0x7f66e428e300,80000,0
73078,16:47:59:725608,free,0x7f66e42f0000,80000,0
73078,16:47:59:725610,free,0x7f66e42dc700,80000,0
73078,16:47:59:725612,free,0x7f66e42c8e00,80000,0
```
At the point of the truncated line, the thread ID changes from 73064 to 73078...

I'm not sure if our logging is thread safe. The memory_resources should be, though. It's possible there is a thread safety bug though!

**Comment by harrism** [comment]
I believe logging should be thread safe (it uses the `_mt` version of the spdlog class.

**Comment by jakirkham** [comment]
Mark and I debugged this during a call earlier. The conclusion that we came too is RMM is doing the right thing here, but the benchmark script is using RMM in weird way.

In particular when we call [`rmm.reinitialize`]( https://github.com/rapidsai/ucx-py/blob/ad32206a9182ff3a91ad847063fa56be1e53f5b2/benchmarks/cudf-merge.py#L162-L164 ), we rely on RMM's default pool size, `~1/2` GPU memory. However we do this from multiple workers on the same device. As a result if we create more than 2 workers, they can try to allocate more memory than is available on the device. Instead we should change the default in the benchmark script to pick an appropriate fraction of GPU memory in relation to the number of workers spun up (like `1/n` for `n` workers).

It's unclear why this worked with CNMeM previously, but it seems it should not have worked there either.

The next step here should be to update the benchmark script to choose a more sensible default.

**Comment by harrism** [comment]
> As a result if we create more than 2 workers, they can try to allocate more memory than is available on the device.

Actually even if you only create 2 workers this is likely to be a problem. Because there's a good chance that 2 processes both trying to allocate 1/2 of available GPU memory will not both succeed, due to per-process / per-context overhead.

**Comment by pentschev** [comment]
Maybe it would make sense to ensure we `rmm.reinitialize` per GPU at the beginning rather than the per-worker?

**Comment by harrism** [comment]
You have to do it once per process. The processes don't share a memory_resource.

**Comment by pentschev** [comment]
> You have to do it once per process. The processes don't share a memory_resource.

You're right, sorry, I missed that each worker was being created as a separate process by https://github.com/rapidsai/ucx-py/blob/ad32206a9182ff3a91ad847063fa56be1e53f5b2/ucp/utils.py#L168 .

**Comment by pentschev** [comment]
This works fine today, provided you specify different devices for each process:

```python
$ python benchmarks/local-send-recv.py -o rmm --server-dev 0 --client-dev 1 --reuse-alloc
Server Running at 10.33.225.165:47005
Client connecting to server at 10.33.225.165:47005
Roundtrip benchmark
--------------------------
n_iter      | 10
n_bytes     | 9.54 MiB
object      | rmm
reuse alloc | True
==========================
Device(s)   | 0, 1
Average     | 577.27 MiB/s
--------------------------
Iterations
--------------------------
000         |60.73 MiB/s
001         | 9.98 GiB/s
002         | 9.77 GiB/s
003         |11.39 GiB/s
004         |10.31 GiB/s
005         | 9.99 GiB/s
006         |11.23 GiB/s
007         |10.06 GiB/s
008         | 8.97 GiB/s
009         |11.13 GiB/s
```

If both processes are on the same device then RMM will attempt to allocate half of the GPU for each, resulting in the allocation error.

I'm closing this, but please reopen if there's more to discuss.
