### ISSUE TITLE
Usage of `nbytes` limits

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#604]
In both `send` and `recv`, we have the option to specify `nbytes` if we only want to send or receive part of `buffer`. Am curious how often this is used in practice. Asking in part because NumPy and CuPy arrays can typically be sliced to provide a view onto a smaller part of the array when needed. Would it be reasonable to drop these options? Or are there reasons we might still need these?

https://github.com/rapidsai/ucx-py/blob/c60f43b3cd9c304053e50a0e4d6d06500e450b1d/ucp/core.py#L554

https://github.com/rapidsai/ucx-py/blob/c60f43b3cd9c304053e50a0e4d6d06500e450b1d/ucp/core.py#L603

**Comment by jakirkham** [comment]
cc @madsbk

**Comment by pentschev** [comment]
I think they're useful if the application knows the size beforehand, that would save a little bit of time on UCX trying to figure that out. In practice, I don't think we're using it anywhere, but it's hard to say given the largest use case nowadays is still Dask.

**Comment by jakirkham** [comment]
Ah but it isn't for the size of `buffer`. It is an upper bound for the allowed size of `buffer`. If `buffer` is above that, it errors. So what I'm asking is why do we need that check here (especially if users can do that themselves)?

**Comment by madsbk** [comment]
Removing the option is fine with me. I added them initially just-because-I-could, I don't think anyone are using them.

> I think they're useful if the application knows the size beforehand, that would save a little bit of time on UCX trying to figure that out.

In principle it would make sense to have a feature like this but with @jakirkham's recent work on reducing the overhead of retrieving buffer information I don't think it is worth the effort.

**Comment by jakirkham** [comment]
Thanks Mads :) Ok will add a PR removing this.
