### ISSUE TITLE
PyTorch support

### ISSUE THREAD

**Issue by eric-haibin-lin** [rapidsai/ucx-py#623]
I see that ucx-py uses __cuda_array_interface__ under the hood for cupy support. Does it mean that it can also support PyTorch tensors? Thanks!

**Comment by jakirkham** [comment]
In theory yes. Though I don't think we've really put it through the paces yet. Is this something that you would be interested in trying? If so, we'd be interested in hearing about your experience 🙂

**Comment by quasiben** [comment]
+1
