### ISSUE TITLE
Performance / Profiling 

### ISSUE THREAD

**Issue by TomAugspurger** [rapidsai/ucx-py#63]
Using this issue to debug performance issues.

https://gist.github.com/TomAugspurger/899add168d97ff394be03f093829d6c6 has a few files. Working off https://github.com/TomAugspurger/distributed/tree/ucx and ucx-py devel.

I don't have LocalCluster working with ucx-py yet, so it's assumed that something like

```
$ dask-scheduler --host=ucx://10.33.225.160 --port=13337
$ dask-worker ucx://10.33.225.160:13337 --host=ucx://10.33.225.160:13338  --no-nanny
```

have been run.

Using `py-spy` I notice that the "idle" profile of UCX scheduler is quite different from a TCP-backed scheduler. Compare the

UCP: https://gist.github.com/TomAugspurger/899add168d97ff394be03f093829d6c6#file-ucx-svg
TCP: https://gist.github.com/TomAugspurger/899add168d97ff394be03f093829d6c6#file-tcp-svg

---

**Comment by quasiben** [comment]
We've adding performance benchmarks in dask-cuda for the time being:

https://github.com/rapidsai/dask-cuda/pull/192
https://github.com/rapidsai/dask-cuda/pull/179
