### ISSUE TITLE
Conda Packages

### ISSUE THREAD

**Issue by TomAugspurger** [rapidsai/ucx-py#65]
It'd be nice to have conda packages for UCX and uxc-py.

I have a start at 
https://github.com/TomAugspurger/ucx-py/tree/conda-recipes in https://github.com/TomAugspurger/ucx-py/blob/conda-recipes/conda-recipes/ucx/meta.yaml.

You should be able to `conda install -c tomaugspurger ucx` into a new environment (`conda create -n ucx-dev python=3.7`) and then activate. Then things like `ucx_perftest` will be on your PATH.

A few questions

1. Where do we want these recipes to live? I think we should eventually submit them to conda-forge, but I've found it's helpful for projects to also maintain their own, especially for relatively complex projects. I'd be happy if these ended up in UCX, and I'm happy to help maintain them going forward.
2. CUDA/GPU support: I've never built a conda package that uses CUDA. My first attempt at including CUDA failed with

```
checking for cuPointerGetAttribute in -lcuda... no
configure: error: CUDA support is requested but cuda packages can't found
Traceback (most recent call last):
  File "/home/nfs/an.taugspurger/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/nfs/an.taugspurger/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/home/nfs/an.taugspurger/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/home/nfs/an.taugspurger/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/nfs/an.taugspurger/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/home/nfs/an.taugspurger/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/home/nfs/an.taugspurger/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/nfs/an.taugspurger/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_envi$on
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/nfs/an.taugspurger/miniconda3/conda-bld/ucx_1550491030832/work/conda_bui$d.sh']' returned non-zero exit status 1.
```

I'm guessing others from Anaconda or NVIDIA will be able to help here. Does UCX require just CUDA runtime, or does it need the driver API?

3. Ensure we're handling the networking libraries properly: I'm not sure how things like libibverbs are supposed to be handled from conda's side of things.

**Comment by mrocklin** [comment]
@jakirkham can you give an update here about the current challenges to packaging UCX and UCX-Py along with any suggestions you may have about what we can do to make progress?

**Comment by jakirkham** [comment]
It's been a little bit since I've touched these recipes as other tasks have bumped them. That said, my recollection is we started to make CDTs using [`conda skeleton rpm`]( https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-skeleton.html#conda-skeleton ). This seems to work ok if the package isn't too complicated, but can run into issues if things go slightly off the beaten path. For example, one particular issue I recall is one RPM contained a broken symlink. Diagnosing and fixing these errors in the CDTs would be the next step. The recipes are in [this branch]( https://github.com/jakirkham/staged-recipes/tree/add_ucx_dev/recipes ) if anyone wants to take a look.

**Comment by mrocklin** [comment]
@seibert is this something that conda devs would have interest in?  This
would help a number of HPC users use InfiniBand in Python (a common request
when talking to IT departments in science or ML groups) and would also help
out with conda deployment of RAPIDS.

**Comment by mrocklin** [comment]
@jakirkham can you recommend a path forward here?  Are people other than you able to do this work?  How long would it take you?  Is it possible to interleave this with other work that you're doing?

**Comment by jakirkham** [comment]
> can you recommend a path forward here?

I think these are already answered in [the comment above]( https://github.com/Akshay-Venkatesh/ucx-py/issues/65#issuecomment-496645009 ). Though please feel free to ask more questions if something remains unclear.

> Are people other than you able to do this work?

No objections to other people doing the work. Again hopefully the comment above answers how this would be handled.

> How long would it take you? Is it possible to interleave this with other work that you're doing?

I'm not sure as I haven't looked at this in a while. I could probably pick this up in a couple of days if needed. Please let me know.

Should add how much time is spent on the recipes generally depends on how we handle upstreaming this work. ( https://github.com/Akshay-Venkatesh/ucx-py/issues/113 )

**Comment by mrocklin** [comment]
> No objections to other people doing the work. Again hopefully the comment above answers how this would be handled.

Do we know anyone who you think is capable of doing this?

> I'm not sure as I haven't looked at this in a while. I could probably pick this up in a couple of days if needed. Please let me know.

It would be useful to have this in a week or two if that's easy to do.  You're also doing other things that are valuable though.  It sounds like we need a bit more information here in order to make decisions about prioritization.  If you can spend a small amount of time to determine how expensive this is, that would be helpful.

**Comment by quasiben** [comment]
I might be able to resume work on conda packaging ucx this week.  But it would be good if others were interested as well

**Comment by mrocklin** [comment]
@quasiben I suspect that you have your hands full with dask-cudf issues.

**Comment by jakirkham** [comment]
Closing as completed.
