### ISSUE TITLE
Update docs for UCX-enabled LocalCUDACluster

### ISSUE THREAD

**Issue by beckernick** [rapidsai/ucx-py#652]
The example in the documentation for a UCX-enabled LocalCUDACluster is now out of date, as we don't need to initialize before spinning up the cluster. We should update this for the new process.

https://ucx-py.readthedocs.io/en/latest/dask.html#inline

**Comment by pentschev** [comment]
To be honest, I'm not 100% confident in that yet. It's true that we don't need it for the cluster itself, but we usually need to ensure that the client is also using the same configuration, which is the reason why `initialize` is used in that example. I know most people are not using that, but it's not currently clear whether not setting those impacts the client negatively.

**Comment by beckernick** [comment]
Understood. What would you want to verify to be confident in this step not being necessary?

**Comment by quasiben** [comment]
I also thought we could get rid of the `initialize` in the documentation but I forgot that client often is configured.  @beckernick I think we still setup the client for TPCxBB runs, correct ?

**Comment by beckernick** [comment]
Currently, we simply [create](https://github.com/rapidsai/tpcx-bb/blob/42e0c5cb3846c0c0b272aeded3083909374a66bc/tpcx_bb/xbb_tools/cluster_startup.py#L72) a Client and attach to a running cluster. This is generally the same way we've always done it in the past.

**Comment by pentschev** [comment]
Actually @beckernick is right. We don't need it _iff_ we also create the `LocalCUDACluster` before instantiating `Client`, because then `LocalCUDACluster` will implicitly have the current (client) process properly configured for UCX. However, we need either `initialize` or `DASK_UCX__*` if we have `Client` connecting to an external cluster, as we don't have any references to the appropriate UCX configuration. We can definitely update docs to reflect this.

**Comment by beckernick** [comment]
Hmm, we [use](https://github.com/rapidsai/tpcx-bb/blob/42e0c5cb3846c0c0b272aeded3083909374a66bc/tpcx_bb/cluster_configuration/cluster-startup.sh#L47) the `DASK_UCX__*` environment variables only locally when setting up the "external" cluster scheduler, but then not when starting up the workers. Then, when we attach to the cluster and create the `Client` we are not setting those environment environment variables.

Is this then technically in undefined territory land?

**Comment by pentschev** [comment]
> Hmm, we [use](https://github.com/rapidsai/tpcx-bb/blob/42e0c5cb3846c0c0b272aeded3083909374a66bc/tpcx_bb/cluster_configuration/cluster-startup.sh#L47) the `DASK_UCX__*` environment variables only locally when setting up the "external" cluster scheduler, but then not when starting up the workers.

The workers are a special case, `dask-cuda-worker ... --enable-{transport} --ucx-net-devices="device/auto"` will internally set those variables.

> Then, when we attach to the cluster to run queries and create the `Client`, we are not setting those environment environment variables.
> 
> Is this then technically in undefined territory land?

Yes, UCX devs have told us in the past (sorry, I can't remember where, but may have been on Slack) that we should use the same configurations on all UCX processes. Given the client is usually doing little work, we may not run into problems currently, but that doesn't necessarily guarantee everything will work well on a different setup, maybe we've been lucky and I would definitely not like users to believe not setting anything will always work.

**Comment by quasiben** [comment]
Would it be possible to handle the initialization differently as an option to `LocalCUDACluster` ?  os.environ could be configured in `LocalCUDACluster` when something like `initialize_local=True`.  If this is done, when the client is constructed, the client should be pick up the newly set env vars.  Thoughts ?

**Comment by pentschev** [comment]
As I said in https://github.com/rapidsai/ucx-py/issues/652#issuecomment-713845984, the client _will_ pick the variables from `LocalCUDACluster` if they're on the same process, but we can't if the client has to connect to a CUDA cluster (no matter if `LocalCUDACluster` or a cluster started with `dask-scheduler`+`dask-cuda-worker`) in a different process, as we need to know what transports to use to connect in the first place.

**Comment by pentschev** [comment]
This has been addressed by many recent changes from @charlesbluca , I'm closing this but please reopen if there's anything still missing.
