### ISSUE TITLE
Maintain Changelog

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#658]
I think we should start a changelog for ucx-py.  I think we have some stability now between major transports (TCP, NVLink, IB) and it would be good to track what is changing.  Thoughts ?

**Comment by pentschev** [comment]
> I think we should start a changelog for ucx-py. I think we have some stability now between major transports (TCP, NVLink, IB) and it would be good to track what is changing. Thoughts ?

That's probably a good idea.

**Comment by pentschev** [comment]
Duplicate of #305 .
