### ISSUE TITLE
Linking issue in our shared object

### ISSUE THREAD

**Issue by TomAugspurger** [rapidsai/ucx-py#68]
When building from source, and importing `ucp_py` from another directory, I see

```
(ucx-dev) an.taugspurger@dgx05:~/ucx-dev-env/distributed$ python -c "import ucp_py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nfs/an.taugspurger/ucx-dev-env/ucx-py/ucp_py/__init__.py", line 2, in <module>
    from ._libs.ucp_py import *  # noqa
ImportError: libucp.so.0: cannot open shared object file: No such file or directory
```

Setting `LD_LIBRARY_PATH` fixes this

```
(ucx-dev) an.taugspurger@dgx05:~/ucx-dev-env/distributed$ LD_LIBRARY_PATH=/home/nfs/an.taugspurger/ucx-dev-env/ucx/install/lib/ python -c "import ucp_py"
```

I believe that's because the necessary files like `libuc` aren't in the normal search path for python (something like `${CONDA_PREFIX}/lib`.

I'll look a how other libraries handle this.

This shouldn't affect our conda packages, as `conda install ucx` will place the required files there.

**Comment by jakirkham** [comment]
These days I’d encourage users working with dev builds to use the `compilers` package from conda-forge.  This will set the right flags basically out-of-the-box and use modern compilers for the build.
