### ISSUE TITLE
RTD page is outdated

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucx-py#681]
I remember looking last week at https://ucx-py.readthedocs.io/en/latest/install.html where instructions for building UCX 1.9 from source already existed, but for some reason today they're not there anymore, although the source file is indeed correct https://github.com/rapidsai/ucx-py/blob/branch-0.18/docs/source/install.rst . Is this something you can check @quasiben or do we have to raise that with devops?

**Comment by quasiben** [comment]
Thanks for raising @pentschev .  I also have the same recollection.  I triggered a new build and I'll update when it finishes

**Comment by quasiben** [comment]
After rebuilding 1.8/1.9 build docs are back:

https://ucx-py.readthedocs.io/en/latest/install.html#ucx-1-9

**Comment by pentschev** [comment]
Thanks Ben!
