### ISSUE TITLE
Move Distributed tests elsewhere

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucx-py#709]
There are currently some tests from Distributed running in UCX-Py's CI due to the lack of GPU CI in the Dask org. This is suboptimal because completely unrelated tests can block the CI of this repo, and at the same time not really being very informative to authors of Distributed PRs. Ideally, we should add gpuCI support to the Dask org which is something @quasiben has been working lately, but otherwise we should consider moving those tests perhaps to a different repo that would run them nightly and alert us should anything break.

**Comment by madsbk** [comment]
Maybe you are right, it might be time to move the distributed tests out of ucx-py. Our own CI tests might not be as thorough as the one in Distributed but having a flaky CI is even worse!

Alternatively, we could limit the Distributed tests to only a few essentials. Right now we are running:
```
py.test --cache-clear -vs `python -c "import distributed.protocol.tests.test_cupy as m;print(m.__file__)"`
py.test --cache-clear -vs `python -c "import distributed.protocol.tests.test_numba as m;print(m.__file__)"`
py.test --cache-clear -vs `python -c "import distributed.protocol.tests.test_rmm as m;print(m.__file__)"`
py.test --cache-clear -vs `python -c "import distributed.protocol.tests.test_collection_cuda as m;print(m.__file__)"`
py.test --cache-clear -vs `python -c "import distributed.comm.tests.test_ucx as m;print(m.__file__)"`
py.test --cache-clear -vs `python -c "import distributed.tests.test_nanny as m;print(m.__file__)"`
py.test --cache-clear -m "slow" -vs `python -c "import distributed.comm.tests.test_ucx as m;print(m.__file__)"`
```
@pentschev do you know if any of them are especially problematic?

**Comment by pentschev** [comment]
I think all of them are potentially problematic. @quasiben is currently working with our devops to provide gpuCI to Dask and Distributed. Hopefully in the next few weeks this will be done and we can then let Distributed itself run tests. In the meantime, perhaps it's better to leave things as they are, but if it takes too long to get gpuCI then we should definitely consider a separate project to run select 3rd-party tests within the rapidsai org to prevent CI in UCX-Py and Dask-CUDA from breaking as it happened yesterday.

**Comment by pentschev** [comment]
This is now being tested in Distributed. However, because we still don't have UCX 1.11 conda packages, we're intentionally leaving tests running here for a little longer, as we test UCX 1.9 and 1.11 in UCX-Py's CI at the moment. Once we have UCX 1.11 packages, we can remove those tests from here.
