### ISSUE TITLE
Drop explicit unpacking of NumPy/CuPy/Numba objects?

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#71]
From listening to a talk by @Akshay-Venkatesh it sounds like we unpack NumPy arrays, CuPy arrays, and so on.  This seems great, especially if we can leverage general protocols like the buffer protocol or the `__cuda_array_interface__` protocol.

However, I was surprsied that we also recreate these objects on the receiving end.  I would expect ucx-py to mostly pass around bytes-like things (or objects that we know how to turn into bytes-like things).  So if I passed ucx-py a numpy array I would expect it to either err (which would be fine with me) or to get out the `memoryview`, and then send that.  I would expect to receive a `memoryview` on the other end.  I would not expect to receive a NumPy array.

I suspect that one of the reasons for this choice is that we don't have a GPU `memoryview`, and that we're using CuPy arrays or Numba DeviceArrays as the memoryview-like object.  We might consider making a memoryview object ourselves.

**Comment by madsbk** [comment]
As the only bindings, the new Python bindings supports `memoryview`, `__array_interface__`, and `__cuda_array_interface__` but it does not reconstruct anything. The receiver provides the container to write to.
