### ISSUE TITLE
Return different status for `UCS_INPROGRESS` in `assert_ucs_status()`

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucx-py#722]
`UCS_INPROGRESS` was being treated as error in `assert_ucs_status()`, which was then fixed to pass in #717 , as per @MattBBaker 's discovery. However, this can be misleading with a user understanding this could mean "ready to consume". Since `assert_ucs_status` is meant to be used with `ucs_status_t`, we cannot block until progress is completed as we would do with `ucs_status_ptr_t`. Perhaps in the future we should think of a different interface for `assert_ucs_status()` with the return status informing the user whether the operation is still in progress or not.

**Comment by MattBBaker** [comment]
What about renaming it to something like `assert_ucs_ok()` and defining it as, "Returns `True` if the underlying op completed in place, `UCS_OK`. Return `False` is the operation in in progress, `UCS_INPROGRESS`. Raises an UCXException if an error is indicated, `UCS_ERR_*`. This is how I am translating it for my RMA NBI functions. That way a blocking operation can be implemented like,
```
if not rmem.put_nbi(data):
    blocking_flush(ep)
```

**Comment by pentschev** [comment]
Yes, I think that's a good solution.

@madsbk what do you think of the above? Any other ideas?

**Comment by madsbk** [comment]
Sounds good to be!
