### ISSUE TITLE
Add blocking progress support for NVLINK in UCX (not UCX-PY)

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [rapidsai/ucx-py#74]
UCX-py relies on `ucp_worker_arm`, `ucp_worker_get_efd` and `ucp_worker_signal` to wait for send/recv event completion especially in the context of unblocking coroutines. It's the responsibility of different UCTs like IB, TCP, cuda-ipc, to provide this capability. IB and TCP have native capability to notify completion of events through file descriptor whereas CUDA doesn't. In addition, `cuda_ipc` was never conceived with blocking progress in mind and we will have to rely on stream callbacks or invoking host functions to support this. Current status is to overcome high overheads in stream callbacks when event query occurs on the same stream as the one when where callbacks are issued.

**Comment by Akshay-Venkatesh** [comment]
- Additions on this branch address this issue: https://github.com/Akshay-Venkatesh/ucx/tree/topic/cuda-ipc-event-notif-fd
- Able to improve performance from 350 MB/s -> 7 GB/s but still not peak.

**Comment by Akshay-Venkatesh** [comment]
- UCX-py is still not seeing the benefits of adding blocking progress in CUDA-IPC. Looks like some other capability needs to be added but this may not be a huge delta but about figuring out why CUDA-IPC UCT isn’t being picked up with server-client mode.

**Comment by Akshay-Venkatesh** [comment]
- Worked with UCX developer @bureddy to narrow down the cause of this issue to configuring `cuda_ipc` iface (https://github.com/openucx/ucx/pull/3479) and to the test itself
- We're able to reach close to expected perf now

**Comment by quasiben** [comment]
I believe we can close this.  The new bindings support blocking and non-blocking API calls.  We can reoopen if cuda_ipc transfers is not performant
