### ISSUE TITLE
Low bandwidth in TCP/Managed memory transfers in UCX

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [rapidsai/ucx-py#76]
- These transfers rely on active message protocol and don't show full bandwith
- We need a 3-stage pipeline to overcome this

**Comment by mrocklin** [comment]
Checking in on this.  What is our status on TCP support?

**Comment by mrocklin** [comment]
Also cc'ing @randerzander , who may want to track conversation heere

**Comment by quasiben** [comment]
closing as this relates to the previous version of ucx-py.  ucx-py now full supports TCP and we are actively benchmarking.  Should should still be an issue we will re-open
