### ISSUE TITLE
How should libraries clean up?

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#80]
As a library user of this library, how should I clean things up?  Am I responsible for calling the global `ucp.fin` function?  What if some other library is also running that wants to use UCX?

**Comment by Akshay-Venkatesh** [comment]
At the moment, cleanup is explicit. This is kind of inline with the MPI world. The main program is responsible for initiating `MPI_Init/ucp.init()`; other libraries may be used in the main program and MPI/UCX handles are passed to it; libraries wouldn't clear/initiate resources; finally, on completion of library routines the main program cleans up through `MPI_Finalize/ucp.fin()` 

Is this contrary to how python applications generally work?

**Comment by mrocklin** [comment]
Well its tricky because we're making a Python library rather than a Python application.  I guess we could require users to call `ucp.init()` and `ucp.fin()` on their own, but honestly I wouldn't mind hiding this from them.  Most of them won't know what UCX is.

What are the costs of calling `ucp.init` when we import `ucp`?  Or alternatively can we make `ucp.init` idempotent so that Dask can do this (perhaps Dask can be more opinionated here than UCX is).

What happens if a user doesn't finalize `ucp` before they exit the process?  In particular, I wouldn't expect interactive users to be very diligent about doing this.

**Comment by Akshay-Venkatesh** [comment]
> Well its tricky because we're making a Python library rather than a Python application. I guess we could require users to call `ucp.init()` and `ucp.fin()` on their own, but honestly I wouldn't mind hiding this from them. Most of them won't know what UCX is.
> 

I suppose we could go about calling `ucp.init()` when `ucp` module is imported. What would be a good time to cleanup resources? Is it safe to detect `ucp` module being unloaded and have `ucp.fin()` be called there?

> What are the costs of calling `ucp.init` when we import `ucp`? Or alternatively can we make `ucp.init` idempotent so that Dask can do this (perhaps Dask can be more opinionated here than UCX is).
> 

`ucp.init()` is a fairly light-weight operation. 

IIUC, we could also make `ucp.init` idempotent and maintain a _refcount_ so that we all resources are cleaned up when a series of `ucp.fin` calls have the desired effect when _refcount_ reaches 0. Am I understanding this right?

> What happens if a user doesn't finalize `ucp` before they exit the process? In particular, I wouldn't expect interactive users to be very diligent about doing this.

If the process which used `ucp` is killed then we don't have problems (ideally). Otherwise, the process may continue to eat up port space, cuda memory handles, etc.

**Comment by mrocklin** [comment]
It sounds like, short term, a lightweight solution might be to ...

-  Make ucp.init idempotent (or give us a way to see if it has been run)
-  Call ucp.init in Dask's UCP comm file
-  Not worry users too much about calling `ucp.fin`, and not worry about this in Dask

**Comment by jakirkham** [comment]
Are both of you familiar with [RAII]( https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization )? If so, I think that might clean this up a bit and help meet Python users where they want to work, but still handle the explicit setup/teardown that C/C++ libraries do. My guess is this is not too difficult to do. It sounds like you are both dancing around this idea already. Thoughts? 🙂

**Comment by Akshay-Venkatesh** [comment]
+1 to Matt's suggestion. 

@jakirkham I'm not familiar with RAII but if there's are established ways of dealing with this problem, I'm for that route.

**Comment by jakirkham** [comment]
Yes, RAII is an established practice to handle acquisition of some resource at initialization and release during object destruction. The practice comes from C++, but has spread more broadly. We could have a small Cython object that handles both of these bits and assign one global instance of it in the module (e.g. happens during import). This would hopefully move away from having a Python user think about any of this.

**Comment by jakirkham** [comment]
Just to make this a bit more concrete, I'm imagining something like the following...

```cython
# filename: ucp_py/_libs/ucp_py.pyx

cdef class _ucp_hdl:
    cdef __cinit__():
         ucp_py_init()

    cdef __dealloc__():
         ucp_py_finalize()


_ucp_hdl_obj = _ucp_hdl()
```

That way when this module is imported, the setup is done during the import. Python will cache imported modules so we don't really need to worry about this happening more than once. It will also be cleaned up whenever the process terminates.

Thoughts? Happy to tweak this or even scrap it if this snippet doesn't capture things. 🙂

**Comment by Akshay-Venkatesh** [comment]
This is really concrete. Now that I think about it, I remember Tom Augspurger having used a similar approach in distributed code that he wrote a while ago. I'll give this a shot tomorrow.

**Comment by jakirkham** [comment]
Well one thing I've left out is error handling. Had looked at `ucp_py_init` and `ucp_py_finalize` and saw they are returning error codes. We probably want to check if the error code is non-zero in either of those places and raise some kind of error (maybe a `RuntimeError`?). Though happy to defer to you on this point. Particularly as I'm not too aware of what error codes might show up or what they mean.

**Comment by jakirkham** [comment]
cc @quasiben (as we discussed this earlier)

**Comment by mrocklin** [comment]
Also, just to be clear, this is not a high priority.  Things are fine
today.  I didn't necessarily want everyone to focus on this, just bringing
it up for eventual discussion.

**Comment by jakirkham** [comment]
Sure, just wanted to provide the missing context for our earlier conversation. 🙂

**Comment by jakirkham** [comment]
Should add I'd also like to check and see if [my earlier suggestion]( https://github.com/Akshay-Venkatesh/ucx-py/issues/80#issuecomment-484750504 ) would work ok with the idea proposed in issue ( https://github.com/Akshay-Venkatesh/ucx-py/issues/83 ).

**Comment by quasiben** [comment]
removing now that #180 is merged in
