### ISSUE TITLE
Programmable env vars 

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#83]
Often we are setting env vars like:
- `UCX_MEMTYPE_CACHE`
- `UCX_NET_DEVICES
- `UCX_RNDV_SCHEME`

Being able to programmatically set these values would make for a nicer experience.  One suggestion might be to build a Context object prior to importing ucp_libs and set/get values from that object

```python
context = ucp.Context(UCX_MEMTYPE_CACHE='n', ...)
ucp.init()
...
```

**Comment by Akshay-Venkatesh** [comment]
+1

**Comment by mrocklin** [comment]
@Akshay-Venkatesh is this something that someone other than you could do?  

If so, can you provide pointers on how to do this?

Also, rather than a context I could imagine passing these values directly to the `ucp.init` call.
