### ISSUE TITLE
Testsuite statefully modifies `os.environ`

### ISSUE THREAD

**Issue by wence-** [rapidsai/ucx-py#842]
A number of tests in the testsuite modify `os.environ` to control some aspect of UCX for the purpose of a specific test. They should restore the original value afterwards in case of potential bad interactions with later tests. This could be done by hand in each test that modifies the environment, but this is prone to being missed when new tests are introduced.

I would therefore suggest to save a copy of the environment in `pytest_setup` and then restore it in `pytest_teardown` in `conftest.py`: if this is not too magic, I will take this approach.

**Comment by pentschev** [comment]
A simpler approach would be using `patch.dict`, some examples:

https://github.com/rapidsai/dask-cuda/blob/22e9c75c496c3ab455cab5243fc195207792d702/dask_cuda/tests/test_dask_cuda_worker.py#L24

https://github.com/rapidsai/dask-cuda/blob/22e9c75c496c3ab455cab5243fc195207792d702/dask_cuda/tests/test_dask_cuda_worker.py#L241

**Comment by wence-** [comment]
Thanks
