### ISSUE TITLE
Improve Dockerfile for cluster deployment

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucx-py#846]
With the great work from @wence- in https://github.com/rapidsai/ucx-py/pull/840, we now have a reference Dockerfile + run script that supports IB and CUDA IPC and runs tests and benchmarks. This is a great way for users to get started with UCX-Py deployment and test that the system is in good state.

Besides that, we could think getting that recipe even more useful. I imagine we could make that more general to replace recipes that people have out there, for example, I know @ayushdg has one that's being used for deployment in some clusters (which we actually copied from for building MOFED in https://github.com/rapidsai/ucx-py/pull/840), I think @quasiben also had some in the past without MOFED.

The idea here is to get information on how we can make this useful for different needs, which people can hopefully just copy and do minimal changes to get started. We would then maintain the Dockerfile and keep it always up-to-date, releasing users from figuring out what's new and what they should update their current environments.

@ayushdg @beckernick @VibhuJawa @randerzander @quasiben when you have a chance, could you please let us know if this is something that would be generally useful? I think the best way to do so would be reading https://github.com/rapidsai/ucx-py/tree/branch-0.26/docker#infinibandnvlink-enabled-docker-file and checking files referred there to see what we already have and what could be improved.

In the future we may have it all within RAPIDS docker containers, but it's not clear when this will happen as we still need to figure out `rdma-core>=28` as a conda-forge package, and we also want to be mindful of UCX-Py users that may want to use it without RAPIDS.

**Comment by pentschev** [comment]
I think @jacobtomlinson may also provide great ideas here.

**Comment by ayushdg** [comment]
Thanks for kicking off this discussion! 

The containers for environments I've typically worked with usually does 3 things:
1. install ofed and related dependencies
2. Create a conda environment based on a custom environment file
3. Install ucx from source in that environment. 
The new container already does step 1 and implements steps 2-3 for a specific conda environment. 

One improvement could be to split out the sections that install ucx (with ib & rdmacm) and ucx-py from source into separate scripts which are added to the container. With this approach downstream users who inherit from these images can build their own conda environments and use the same set of scripts in the container to install ucx, while the current container can invoke these scripts specifically for the `ucx` conda environment.

**Comment by randerzander** [comment]
> In the future we may have it all within RAPIDS docker containers

Is that a nearer future than publishing these existing container images as is to Dockerhub or elsewhere?

**Comment by pentschev** [comment]
> > In the future we may have it all within RAPIDS docker containers
> 
> Is that a nearer future than publishing these existing container images as is to Dockerhub or elsewhere?

That is a good question. The problem for the reference Dockerfile is we would have to publish different containers for different MOFED versions, that is where the Dockerfile is useful.

As a more generic solution, we could explore utilizing `rdma-core` instead, and then we could publish only one container built with `rdma-core==28` and that should work for any MOFED 5.x. `rdma-core` compatibility is currently untested but we could definitely try it out, and if that works well for your use case we could then discuss integrating that into RAPIDS containers.

**Comment by jacobtomlinson** [comment]
Is there value in publishing this image? It sounds like a useful development tool that you would just build as and when you need it. The `Dockerfile` looks pretty lightweight with most of the work being run at runtime in the `run.sh` script.

**Comment by wence-** [comment]
> Is there value in publishing this image? It sounds like a useful development tool that you would just build as and when you need it. The `Dockerfile` looks pretty lightweight with most of the work being run at runtime in the `run.sh` script.

Are we looking at the same one? The base [dockerfile](https://github.com/rapidsai/ucx-py/blob/branch-0.26/docker/Dockerfile) does everything at runtime, but the [IB-enabled one](https://github.com/rapidsai/ucx-py/blob/branch-0.26/docker/UCXPy-CUDA.dockerfile) installs and builds everything via docker command steps and then just runs some benchmarking at the end.

I'm not really sure of best practices for reusable images, one question is how much needs to be specialised. AIUI, the MOFED version in the container needs to match that available on the host system. So if publishing, we would definitely need to include that in the name. The question is how many versions we would want to support, and if not that many, how best to make it easy for others to override.

@ayushdg Can you point at some example dockerfiles that implement the three-step process you describe?

**Comment by pentschev** [comment]
We can replace MOFED with `rdma-core`, and `rdma-core==28` should implement ibverbs that is compatible with `MOFED>=5.0` and should be forward-compatible as well, meaning any `MOFED>=5.0` should work with `rdma-core==28`. It would be of extreme value if we could try creating a Dockerfile that installs `rdma-core==28`, which should be available in Ubuntu 20.04 and testing it against multiple MOFED versions, since this is something we haven't done before, and if that works we could publish a generic UCX-Py docker image and/or integrate that into RAPIDS images.. Do you think you could work on that @wence- ?

**Comment by wence-** [comment]
> We can replace MOFED with `rdma-core`, and `rdma-core==28` should implement ibverbs that is compatible with `MOFED>=5.0` and should be forward-compatible as well, meaning any `MOFED>=5.0` should work with `rdma-core==28`. It would be of extreme value if we could try creating a Dockerfile that installs `rdma-core==28`, which should be available in Ubuntu 20.04 and testing it against multiple MOFED versions, since this is something we haven't done before, and if that works we could publish a generic UCX-Py docker image and/or integrate that into RAPIDS images.. Do you think you could work on that @wence- ?

I will have a go, can you assign me? (I can't self-assign in this repo).

**Comment by ayushdg** [comment]
> @ayushdg Can you point at some example dockerfiles that implement the three-step process you describe?

Here's the [dockerfile](https://github.com/rapidsai/gpu-bdb/blob/main/gpu_bdb/benchmark_runner/slurm/Dockerfile) that does steps 1-2 and I have a seperate script for 3 that is pretty much identical to these [lines](https://github.com/rapidsai/ucx-py/blob/branch-0.26/docker/UCXPy-CUDA.dockerfile#L54-L70). I was thinking if the existing docker file included a script for step 3, that other images could just inherit, this could be a single source of truth for ucx installation that other projects could use
