### ISSUE TITLE
pynvml dependency?

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#847]
Currently it appears `pynvml` is an optional dependency as it is [`import`ed in this `try...except...`]( https://github.com/rapidsai/ucx-py/blob/13a7046b8f9d9c2fd86440d6dff2d802c8991e55/ucp/__init__.py#L37-L61 ).

However some of [the exceptions caught]( https://github.com/rapidsai/ucx-py/blob/13a7046b8f9d9c2fd86440d6dff2d802c8991e55/ucp/__init__.py#L57-L59 ) depend on `pynvml` being imported. This results an interesting situation where `pynvml` is effectively required as seen by the following exception when running `import ucp`.

```python
Traceback (most recent call last):
  File "$PREFIX/lib/python3.9/site-packages/ucp/__init__.py", line 38, in <module>
    import pynvml
ModuleNotFoundError: No module named 'pynvml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/conda-bld/ucx-py_1651251230000/test_tmp/run_test.py", line 2, in <module>
    import ucp
  File "$PREFIX/lib/python3.9/site-packages/ucp/__init__.py", line 57, in <module>
    pynvml.NVMLError_LibraryNotFound,
NameError: name 'pynvml' is not defined
```

How should we handle this?

1. Require `pynvml`
2. Adjust exception handling so it doesn't depend on `pynvml`
3. ?

**Comment by pentschev** [comment]
Requiring `pynvml` isn't an option, not everyone using UCX-Py has CUDA. I'm not sure what you mean by exception handling not depending on `pynvml`, since we actually depend on those exceptions being caught in case something else is wrong. Perhaps what you mean is something like below?

```python
try:
    import pynvml
except ImportError:
    pynvml = None

if pynvml is not None and "UCX_CUDA_COPY_MAX_REG_RATIO" not in os.environ and get_ucx_version() >= (1, 12, 0):
    try:
        # do stuff ...
    except (
        pynvml.NVMLError_LibraryNotFound,
        pynvml.NVMLError_DriverNotLoaded,
        pynvml.NVMLError_Unknown,
    ):
        pass
```

I'm ok with this solution above, if there's a better one, I'm up for it too.

**Comment by jakirkham** [comment]
Yep something like that is what I had in mind for 2

**Comment by pentschev** [comment]
Thanks John, submitted https://github.com/rapidsai/ucx-py/pull/848 to fix it.
