### ISSUE TITLE
Meta Issue: Track CUDA virtual memory support in UCX

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#890]
- [x] https://github.com/openucx/ucx/pull/8623

We can populate with other PRs/Issues as they arise

**Comment by pentschev** [comment]
I seem to have missed/forgotten you opened this and I ended up duplicating this in https://github.com/rapidsai/ucx-py/issues/892, sorry about that. I'm closing this in favor of that one which is more up-to-date now.
