### ISSUE TITLE
Enable skipped tests in CI when dependencies are available

### ISSUE THREAD

**Issue by divyegala** [rapidsai/ucx-py#946]
While going through the CI logs of https://github.com/rapidsai/ucx-py/pull/945, we figured out that due to imports being handled with `pytest.importorskip`, some tests are being skipped entirely, and silently if the dependency is unavailable. This happens especially in wheels as the dependencies on `rmm` and `cudf` wheels is not explicitly expressed at the moment.

**Comment by wence-** [comment]
So I think this is "as designed", but the fix is that so that we have coverage we should install rmm and cudf in the wheel testing environment?

**Comment by ajschmidt8** [comment]
Regarding wheels, the testing process is a bit opaque at the moment.

@vyasr and I have been collaborating to simplify it.

For now, it looks like the wheel testing commands are below.

- https://github.com/rapidsai/ucx-py/blob/e2f5a27e5cfeb00ea133f3b969758940dda9dde5/.github/workflows/pr.yaml#L47-L57

To add the `rmm`/`cudf` dependencies, I assume we'd have to put `pip install rmm/cudf` commands there.

But I'm not sure how that works with our current nightly registry setup with wheels.

This will likely become clearer in the coming weeks as we get a new nightly registry and also continue to refine the wheel building/testing process.

I'll defer to @vyasr for additional comments, but my hunch is that we should hold off on this for now until the work I mentioned above is complete.
