### ISSUE TITLE
Dask comm performance benchmarking

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#98]
I'm running a benchmark on UCX-powered Dask comms here: https://github.com/TomAugspurger/dask-perf/blob/b09680b7001fcf14e1d0e2f657ab9bb83febc772/bench_comm.py (modified from @TomAugspurger 's benchmark)

I get only about 1GB/s bandwidth, and suspect that I might be able to get more.

When I profile things with the cProfile module I get the following output

```python
from bench_comm import run_bench
import asyncio
loop = asyncio.get_event_loop()
%prun loop.run_until_complete(run_bench('ucx', nbytes=20000000, niters=50))  # note, I'm running this in ipython to get the `prun` magic
```

```
         35703 function calls in 1.449 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      301    0.994    0.003    0.995    0.003 {method 'recv_obj' of 'ucp_py.Endpoint' objects}
      509    0.209    0.000    0.209    0.000 {method 'poll' of 'select.epoll' objects}
        1    0.089    0.089    0.089    0.089 {method 'randint' of 'mtrand.RandomState' objects}
      705    0.047    0.000    0.048    0.000 {method 'send_obj' of 'ucp_py.Endpoint' objects}
        1    0.019    0.019    0.019    0.019 {ucp_py.get_endpoint}
      509    0.007    0.000    1.448    0.003 base_events.py:1679(_run_once)
      819    0.007    0.000    1.222    0.001 {method 'run' of 'Context' objects}
      302    0.005    0.000    1.021    0.003 ucx.py:171(read)
      404    0.005    0.000    0.005    0.000 {method 'recv_future' of 'ucp_py.Endpoint' objects}
      509    0.003    0.000    0.213    0.000 selectors.py:451(select)
      302    0.003    0.000    0.067    0.000 ucx.py:149(write)
      101    0.003    0.000    0.007    0.000 core.py:111(loads)
```

Most of the time is in the `Endpoint.recv_obj` method, reproduced below:

https://github.com/Akshay-Venkatesh/ucx-py/blob/03b8a79ef27b6345c006e05d8cf456b5209af03a/ucp/_libs/ucp_py.pyx#L288-L295

My first guess is that this is maybe allocation?  I don't know though.  Any thoughts on what might be going on here and how it might be improved?

cc @Akshay-Venkatesh

**Comment by TomAugspurger** [comment]
To isolate allocation, you could try using recv_into.

**Comment by mrocklin** [comment]
I suspect that somewhere @Akshay-Venkatesh already has benchmarks comparing `recv_into` and `recv_obj`.  Is 1GB/s what I should be expecting for `recv_obj`?

My guess is that `recv_into` isn't feasible for Dask comms (we're probably not the right level of project to manage memory).  I would also expect better memory bandwidth on the host side than 1GB/s, though I'm a bit out of my depth here.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin Am I reading things right when I see that you're running the bench with 20MB data? I see this for `recv_obj` with host/cuda buffers (4MB-32MB)
```shell
4194304         3403.52         1.23
8388608         5532.60         1.52
16777216        9519.24         1.76
33554432       21288.04         1.58 # notice the drop here
```
So the performance you're seeing is not unreasonable IMO.

This is much lower in perf compared to `recv_into`:
```shell
Roundtrip benchmark
-------------------
n_iter   | 10
n_bytes  | 10.00 MB
recv     | recv_into
object   | cupy
inc      | False

===================
5.51 GB / s
===================

Roundtrip benchmark
-------------------
n_iter   | 10
n_bytes  | 20.00 MB
recv     | recv_into
object   | cupy
inc      | False

===================
7.39 GB / s
===================
```

Like you said, the allocation in the critical path is hurting performance.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin Moving to a memory manager is something would directly impact performance here. Do you know of the applicability of the memory manager used elsewhere in RAPIDS in this context?

**Comment by mrocklin** [comment]
OK, yes you're right, it looks like I'm only able to allocate at about 2GB/s

```python
In [1]: import numpy as np

In [2]: %time _ = np.ones(100000000, dtype='uint8')  # 100 MB
CPU times: user 4 ms, sys: 64 ms, total: 68 ms
Wall time: 67.7 ms

In [3]: %time _ = np.ones(1000000000, dtype='uint8')  # 1000 MB
CPU times: user 92 ms, sys: 468 ms, total: 560 ms
Wall time: 561 ms
```

This is slower than I expected.  

> Am I reading things right when I see that you're running the bench with 20MB data? 

Yes, but it only improves marginally when I increase from here.

> Moving to a memory manager is something would directly impact performance here. Do you know of the applicability of the memory manager used elsewhere in RAPIDS in this context?

My assumption is that the RAPIDS memory manager would be GPU-only.  I don't know though.

**Comment by mrocklin** [comment]
@seibert do you have any thoughts here?  It seems like we're bound by allocating numpy arrays.  This allocation speed is slower than I would have expected.  Does this match your intuition?

(sorry to engage you on this numba-unrelated matter, but my guess is that you'll find this interesting and have things to say)

Also, does it make sense for NumPy to grow a memory manager?

**Comment by Akshay-Venkatesh** [comment]
> My guess is that recv_into isn't feasible for Dask comms (we're probably not the right level of project to > manage memory). 

@mrocklin Can you elaborate a little bit more on this? Is it possible to have Dask maintain some persistent communication buffers and just use those? (so that we can use `recv_into`). This is also how HPC codes generally deal with the issue.

**Comment by mrocklin** [comment]
> Is it possible to have Dask maintain some persistent communication buffers and just use those? This is also how HPC codes generally deal with the issue.

We could do something like this, yes, but our situation is a bit less structured than a typical HPC code, so we would need to be more careful about when data is safe to reuse.  We don't really know what will happen to the bytes that come through here.  They get passed into Python objects and then are handed off to user code.  Sometimes they're short lived, sometimes they're not.  The user can do whatever they want to with them.  We don't have apriori knowledge of the lifecycle of these bytes.

So my sense is that if we wanted to do something like this then we would be implementing our own memory manager.  This might be something we want to do; I'm not sure.  It probably depends on the tradeoffs on how hard this is to build and what kinds of speedups we might anticipate.

Previously, my sense was that the complexity-to-performance tradeoff made a lot more sense for device memory than for host memory.  I'd be happy to learn that this was useful in both contexts though.  cc @kkraus14

**Comment by quasiben** [comment]
@mrocklin i tired running @TomAugspurger 's bench_comm test.  And it failed (more or less expected) as you know we have been benchmarking dask-cudf/cupy things as of late.  Is this something you want to keep open and continue pushing on with dask-perf ?

**Comment by mrocklin** [comment]
I defer entirely to you

**Comment by quasiben** [comment]
I believe dask has started building out a benchmark suite here:
https://github.com/dask/dask-benchmarks

I'd be happy to help contribute patches to that benchmark suite if that is of interest.  For now, I'm going to close this issue
